### ISSUE TITLE
Single node and multi node instructions mistake

### ISSUE THREAD

**Issue by jkeenest** [EMCECS/ECS-CommunityEdition#1]
Both the single node and multi node instructions state that there are 3 main steps but it seems that only steps 1 and 3 are listed.
![2015-06-23_10-37-01](https://cloud.githubusercontent.com/assets/10226529/8308632/e6e6a72e-1993-11e5-9965-557635dfe3c6.png)

**Comment by pbutlerm** [comment]
Thanks for the information. The documentation has been updated.
