### ISSUE TITLE
Single Node Vagrant

### ISSUE THREAD

**Issue by ryandotclair** [EMCECS/ECS-CommunityEdition#10]
Vagrant is broken. It attempts to leverage the python scripts but it doesn't pass any of the variables identified in the VagrantFile to the python scripts.

Also, requiring to install anything but Vagrant/Vagrant Management Servers plugin defeats the purpose of Vagrant. 

Lastly, including steps in how to install the Vagrant and Vagrant Management Servers plugin in the README.md file would be very helpful.

**Comment by padthaitofuhot** [comment]
@ryandotclair Thanks for the bugreport. I've marked this as a bug. If you have a solution in mind for any of these issues, please feel free to share.

**Comment by ryandotclair** [comment]
Finally have some time to work on this. I'm thinking a common yaml config file that can be shared between Vagrant and the existing python scripts. That way only one file has to get modified and it would replace the python arguments. It's probably not the most elegant way of doing it but should work. I'll play around with it this weekend.

**Comment by ryandotclair** [comment]
I've come to the conclusion that the Vagrant option just isn't worth it. As it stands, at least for my hack, you have to install wget, ruby, vagrant,  and nano (never did like vi), wget vagrant from their official site, because it's not in yum default repos(Google App Engine specific?), install vagrant from yum, git the ECS repo and the vagrant managed server plugin. Install the vagrant server plugin, nano the config.yaml file, then finally vagrant up.... not that I can get ssh to work on Google App Engine between two instances, even within an instance group.

At the end of the day, you realize its a lot of effort to get (in this case) a glorified rsync tool to work. Might as well just stick to the tried and true python script :pensive:

**Comment by padthaitofuhot** [comment]
Hrm.  Well, thank you for the effort you put into it.  Vagrant doesn't appear to be in the EPEL-release yum repo either, so I'm not sure it's going to show up in RHEL & clones anytime soon.  IIRC there's a Debian package for Vagrant, so that might be a pathway when Community Edition supports Debian.

**Comment by padthaitofuhot** [comment]
I've put this onto the Wishlist so it can be tracked for future work should the entry barriers be reduced.
