### ISSUE TITLE
Can we create multiple vdc and pools on single node

### ISSUE THREAD

**Issue by saurabhharit** [EMCECS/ECS-CommunityEdition#102]

**Comment by jasoncwik** [comment]
No, ECS Community Edition cannot support multiple VDCs and Storage Pools on a single node.  However, if you have enough RAM you could create multiple VMs on one physical host.  I've had reports that creating three VDCs with three single-node installs works.  When installing multiple VDCs, you'll need to use --skipVdcProvision for step2 on all VDCs after the first and then add them to the first VDC through the GUI.
