### ISSUE TITLE
Single Node Docker

### ISSUE THREAD

**Issue by ryandotclair** [EMCECS/ECS-CommunityEdition#11]
A few minor issues.

1) In the ECS-SingleNode-Instructions.md file, the Python script already installs most of the packages you're asking the user to install as well as does an update for them. I'd only require them to install git to pull down the files.

2) I would call out in the ECS-SingleNode-Instructions.md file the fact that the python script UNINSTALLS any existing Docker package and reinstalls a specific version. If user already has docker installed, this can be disruptive. 

3) Within the step1 python script, you download a file called 'additional_prep.sh'. For those of us paranoid, I'd appreciate it if you could include that script in your git repo instead of hiding it.

4) Is there a specific reason why the changes in modify_container_conf_func() aren't included in the original image that gets pulled down?

**Comment by jasoncwik** [comment]
Pull request 12 resolves item 3 above.

**Comment by padthaitofuhot** [comment]
Regarding point 4, the Docker image used by single node is a generic ECS Community Edition base image that is not specific to single-node installation. Future releases may have a specific image for single-node installs.
