### ISSUE TITLE
GUI is quite slow, and with error 'An error occurred while encoding/decoding of tokens'

### ISSUE THREAD

**Issue by walkerzhang** [EMCECS/ECS-CommunityEdition#111]
not sure if this is bug or something? the GUI seems quite slow to me sometimes.   

ecsportalsvc.log

2016-03-21 13:18:17,353 [play-thread-1] ERROR  ExceptionOnErrorFilter.java (line 51) Error 10001 (http: 401): An error occurred while encoding/decoding of tokens. Unable to decode token.
2016-03-21 13:18:17,353 [play-thread-1] ERROR  Logger.java (line 426) Error 10001 (http: 401): An error occurred while encoding/decoding of tokens. Unable to decode token.

**Comment by walkerzhang** [comment]
Looks like the error has nothing to do with the GUI performance. After restarted the docker container, the GUI back to normal speed, but those error still exist.

**Comment by APeter0807** [comment]
Try the following solution:

> 1. Log into UI and leave browser open
> 2. Reset DB on each node using ./deployment.sh ResetDb
> 3. Refresh the browser page; you should get a "session timed out or password has chaged" message
>  Login should now be successful.

Other reports indicate that this issue is more common when using IE, so you may try using a different browser.

**Comment by walkerzhang** [comment]
Where is deployment.sh? searched whole system couldn't find it. FYI, I'm using the single node system.

**Comment by APeter0807** [comment]
Hmm... you're right; it doesn't appear to exist in CE.

My next best guess is that it could be the Authentication Provider or VNeST; you can delete your existing authentication provider and create a new one through the GUI, and clean the latter with `rm -rf /data/vnest/vnest-main/*`.

**Comment by padthaitofuhot** [comment]
@APeter0807 @jasoncwik Can we get `deployment.sh` for use in ECS CE?

**Comment by mpushpalatha** [comment]
i face the same issue in ECS-CommunityEdition-2.2.0.3

**Comment by bodhankaryogesh** [comment]
Facing same issue with ECS-CE 3.0

**Comment by padthaitofuhot** [comment]
I am assuming this is an issue affecting the Management API.  How are you closing sessions when talking to ECS management API?  Are you re-using the same token for every request?  Are you properly destroying tokens when you're done using them?  The best way to use the management API is through a module that handles all gotchas, such as python-ecsclient https://github.com/EMCECS/python-ecsclient .

**Comment by padthaitofuhot** [comment]
Please reopen this issue if we can be of further assistance.  Thank you.
