### ISSUE TITLE
Can we use nfs protocol in latest version ?

### ISSUE THREAD

**Issue by itot555** [EMCECS/ECS-CommunityEdition#117]
I have already checked following license file
https://github.com/EMCECS/ECS-CommunityEdition/blob/master/ecs-multi-node/license.xml

However, I haven't find ecs nfs license, so can't we use nfs protocol in latest version ?

Best regards.

**Comment by padthaitofuhot** [comment]
Good question.  I'll check in with the powers-that-be and see what the status is on enabling this for ECS Community Edition.  Thanks for asking!

**Comment by itot555** [comment]
Thanks!! I'm looking forward to use nfs service with community edition.
Best regards.

**Comment by jasoncwik** [comment]
Yes, you can use NFS with community edition, but you should probably wait for the upcoming Service Pack 1 release that includes many NFS improvements.

**Comment by bennypi** [comment]
As I am also struggling to access ECS either via an nfs share or via s3fs, could you tell when to expect the release of the service pack?

**Comment by APeter0807** [comment]
Service Pack 1 should be available for community edition by the end of next week.

**Comment by itot555** [comment]
Service Pack 1 was released, so can we use NFS protocol for community edition ?

**Comment by APeter0807** [comment]
Yes; Service Pack 1 is available for use with Community Edition, and can currently be installed using the /develop branch (a few settings have changed that make the installation scripts currently in the master branch infeasible).

**Comment by itot555** [comment]
Thanks!! I'll check that.
