### ISSUE TITLE
We need a proper usericon for EMCECS organization.

### ISSUE THREAD

**Issue by padthaitofuhot** [EMCECS/ECS-CommunityEdition#120]
Really, though, we have such good at EMC in general, does anyone @EMCECS/ecs-communityedition or @EMCECS/ecs-cloudfoundry have a lead on getting a proper logo/usericon for our github organization?

**Comment by padthaitofuhot** [comment]
@captntuttle Are you any good with mspaint?

**Comment by adrianmo** [comment]
I updated the icon to the current one a some time ago because there wasn't any. But any other options and designs are welcome!

**Comment by padthaitofuhot** [comment]
Oh, wow, that looks pretty good @adrianmo .  I hadn't checked in a long time (April 2016).  We can close this issue.  In 3... 2... 1...
