### ISSUE TITLE
"Remote I/O Error" when writing to a mounted NFS Export

### ISSUE THREAD

**Issue by dancaps** [EMCECS/ECS-CommunityEdition#123]
I've been working with someone on the forums but I think we are both at a loss here. Some help would be appreciated.

https://community.emc.com/thread/227549

I installed a 4 node install using the step[1,2] scripts. I'm able to mount the export and create a directory but I get a remote I/O error when trying to create a file.

**Comment by APeter0807** [comment]
Resolved on community thread.

NFS is currently not supported for retention on buckets; this will be supported in 2.2.1 (May) for read-only, and 3.0 (September) for full-write.

**Comment by cnu405** [comment]
Can I have clear solution to fix this issue please
