### ISSUE TITLE
block docker_pull when image loaded #124 

### ISSUE THREAD

**Issue by bottkars** [EMCECS/ECS-CommunityEdition#125]
When docker _load_image is specified, the image is also downloded because pull function is run.
 pull is only exluded on no internet
 changing to elif will block the pull function when imagefile is loaded
see
Update step1_ecs_singlenode_install.py to block docker_pull when image loaded #124 
https://github.com/EMCECS/ECS-CommunityEdition/pull/124

**Comment by APeter0807** [comment]
Addressed in f83aa3d & 1cd2a98; docker_pull and docker_load functions now mutually exclusive.
