### ISSUE TITLE
file upload returns status code 507, dashboard shows enough available space

### ISSUE THREAD

**Issue by bennypi** [EMCECS/ECS-CommunityEdition#126]
Hello, 
although the dashboard shows 410GB of available space, it's not possible to upload a 900MB file via the Amazon S3 Java SDK or using the Cloudberry Explorer.
The Amazon SDK returns:
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The server cannot process the request because there is not enough space on disk (Service: Amazon S3; Status Code: 507; Error Code: Insufficient Storage; Request ID: 0ad2f80f:153e6610ee6:2a3c:57), S3 Extended Request ID: null
There is no quota enabled for the namespace or the bucket that is used.
I've attached a screenshot of the dashboard which might help you:
![emc_ecs_dashboard](https://cloud.githubusercontent.com/assets/2631090/15012297/dab8d21c-11f7-11e6-83bc-7cdf4f7ff102.PNG)

**Comment by bennypi** [comment]
Although I did not change anything, somehow uploading is working now again. However, the dashboard shows some strange values, for example -1 alerts:
![emc_ecs_minus1](https://cloud.githubusercontent.com/assets/2631090/15144791/f4d69850-16b1-11e6-8c72-dd03c5cdc53d.PNG)
If this cannot be fixed easily, I will just wait for the service pack to be released followed by a new clean installation as this instance is used only for testing.

**Comment by APeter0807** [comment]
There are a few known issues with dashboard reporting (particularly capacity) 2.2.0. A few improvements have been made to its accuracy in 2.2.1, and we will continue to improve the usage reporting features in the future releases.
