### ISSUE TITLE
Change IP and restart contaniner

### ISSUE THREAD

**Issue by rbgoda** [EMCECS/ECS-CommunityEdition#134]
Hello, how to bind same ECS instance to different IP address. Current challenge is re-running Python script format data disks and remount it. Its best if it gives option to allow to run by changing just IP or hostname without affecting any configuration nor test data lost.

**Comment by jasoncwik** [comment]
Unfortunately, ECS does not currently support changing the hostname or IP address.  This will come in a future release.
