### ISSUE TITLE
ECS Multinode fails to come back on restart

### ISSUE THREAD

**Issue by jasoncwik** [EMCECS/ECS-CommunityEdition#135]
After restarting ECS multinode systems, we've had multiple customers report that the system either becomes unresponsive after a while or does not come back on reboot.

We have tracked this down to a thread deadlock in vnest due to an improper thread configuration.  We will release new docker images for 2.2.1.0-a and 2.2.0.3-a to fix.

**Comment by APeter0807** [comment]
This relevant change is implemented in the current `latest` image for both 2.2.1 and 2.2, as well as the noted `2.2.1.0-a` and `2.2.0.3-a`
