### ISSUE TITLE
Installer step1 fails if there is proxy in front of the nodes

### ISSUE THREAD

**Issue by anikundesu** [EMCECS/ECS-CommunityEdition#140]
Installer step1 fails if there is forward proxy in front of the nodes. This is because step1 installer doesn't support proxy. The details of issue are the following.

* Proxy setting of docker for "docker pull" to be able to download images.
* Proxy environment variables doesn't set when executing "docker run" the container.

**Comment by wangzhizheng** [comment]
hi anikundesu

I believe that adding proxy parameter should be better to cover the situation that proxy is used.
but could you get the docker image by adding the proxy manually?

**Comment by anikundesu** [comment]
Hi wangzhizheng

About the first point, I have successfully gotten the docker image by adding following settings at the end of /etc/sysconfig/docker file manually.

```
[end of /etc/sysconfig/docker]
http_proxy=http://(proxy url):(port)
https_proxy=http://(proxy url):(port)
HTTP_PROXY=http://(proxy url):(port)
HTTPS_PROXY=http://(proxy url):(port)
```

 And comment out line 459 of step1_ecs_multinode_install.py.

```
[diff of step1_ecs_multinode_install.py part2]
458,459c458,459
<         logger.info("Copy files /etc/sysconfig/docker to /etc/sysconfig/dockerold.")
<         subprocess.call(["cp", "/etc/sysconfig/docker", "/etc/sysconfig/dockerold"])
---
>         #logger.info("Copy files /etc/sysconfig/docker to /etc/sysconfig/dockerold.")
>         #subprocess.call(["cp", "/etc/sysconfig/docker", "/etc/sysconfig/dockerold"])
```

About the second point, even if I fixed the upper settings, step1_ecs_multinode_install.py failed to install ECS nodes. This is because the script execute "curl" command in the container at modify_container_conf_func() function but https_proxy environment doesn't be configured in the container at the "docker run" timing. So I fixed step1_ecs_multinode_install.py to configure proxy settings.

```
[diff of step1_ecs_multinode_install.py part2]
486c486
<         docker_command = ["docker", "run", "-d", "-e", "SS_GENCONFIG=1"]
---
>         docker_command = ["docker", "run", "-d", "-e", "SS_GENCONFIG=1", "-e", "HTTP_PROXY=http://(proxy IP):(port)", "-e", "HTTPS_PROXY=http://(proxy IP):(port)"]
```

**Comment by wangzhizheng** [comment]
That's great!
Thank you for the helpful info

**Comment by anikundesu** [comment]
You're welcome!  ^^
