### ISSUE TITLE
Install Issue - "Problem reaching authentication server"

### ISSUE THREAD

**Issue by dbbyleo** [EMCECS/ECS-CommunityEdition#148]
I'm following the installation guide to install multi-node ecs via Docker. I've turned off the firewall (service firewalld stop) on all the nodes.

My attempt to run step1 script (on node 1) is continues to be stuck at this stage (see below).  I'be waited up to 30minutes...  
```
[29/Jun/2016 14:49:02] INFO [root:631] Problem reaching authentication server. Retrying shortly.
Executing getAuthToken: curl -i -k https://192.168.40.140:4443/login -u root:ChangeMe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to 192.168.40.140:4443; Connection refused
[29/Jun/2016 14:49:32] INFO [root:631] Problem reaching authentication server. Retrying shortly.

```

Here's my command:
`python step1_ecs_multinode_install.py --ips 192.168.40.140 192.168.40.141 192.168.40.142 192.168.40.143 --hostnames ecs01 ecs02 ecs03 ecs04 --disks sdb --ethadapter ens32`

If I try to install just a single-node, Step1 completes successfully (after about 12 minutes of trying the authentication server).

Please help.

**Comment by dbbyleo** [comment]
It eventually ends with this:
```
[29/Jun/2016 15:09:04] CRITICAL [root:634] Authentication service not yet started.
[29/Jun/2016 15:09:04] INFO [root:763] Step 1 Completed.  Navigate to the administrator website that is available from any of the ECS data nodes.         The ECS administrative portal can be accessed f                                   rom port 443. For example: https://ecs-node-external-ip-address.         The website may take a few minutes to become available.
```

**Comment by APeter0807** [comment]
Can you check out the `/host/data/network.json` within the container (`` nsenter -i -m -p -u -t `pidof blobsvc` `` ) and make sure the the IPs match your host? Sounds like the multi-node installation might have malformed that config.

**Comment by dbbyleo** [comment]
@APeter0807 Sorry for the delayed response, but I got pulled off to another project.  I'm back to this project now though.  

Thanks for the reply.  Here's what's inside my network.json file:

`{"private_interface_name":"ens32","public_interface_name":"ens32","hostname":"ecs01","data_ip":"192.168.40.140","mgmt_ip":"192.168.40.140","replication_ip":"192.168.40.140"}`

The names are correct and IP address is correct, but this is only showing one node.

**Comment by dbbyleo** [comment]
@APeter0807 I tried it again, without making any changes.  I went home for the day.  Came back the next morning and found everything is up.  I'm not sure how long exactly it took, but it eventually got up and running.  I'm redoing the install today and using a script to do a simple netstat check so I can see when exactly the service (at 4443) came online.

**Comment by dbbyleo** [comment]
It turned it was my firewall.  I followed the steps to ensure my firewall was configured right, but I guess it there was something I missed - thought it is still unknown to me.  At any rate, for now I just disabled my firewall prior to running step1 script of the install.  And this time, the install completed successfully within minutes.
