### ISSUE TITLE
web page not getting started

### ISSUE THREAD

**Issue by vijayscsa** [EMCECS/ECS-CommunityEdition#149]
netstat -lptn | grep 443 is not at all listing

and http://<IP> nor https://ip are not at all working again and again..

**Comment by APeter0807** [comment]
Are firewalld or iptables enabled and running on your system? If so, do they have the [necessary exceptions](https://github.com/EMCECS/ECS-CommunityEdition/blob/master/Documentation/ECS-Troubleshooting.md#list-of-open-ports-required-on-each-ecs-data-node) in place?

Alternatively, what specific error(s) do(es) ecsportalsvc log suggest (`/opt/storageos/logs/ecsportalsvc.log` within the container, or `/var/log/vipr/emcvipr-object/ecsportalsvc.log` on your VM) ?

**Comment by APeter0807** [comment]
Issue resolved off-ticket; was direct result of only installing one node of a four-node installation.

Users should ensure that Community Edition is installed on all host nodes before verifying that the portal service is running.
