### ISSUE TITLE
Unable to start docker after reboot

### ISSUE THREAD

**Issue by mandarmahajan** [EMCECS/ECS-CommunityEdition#150]
I have deployed new community edition of ECS following all the steps given here. it gets deployed fine and works ok. 

However as soon as I stop the docker service and reboot the machine it does not start docker container again.  when checked logs I get permission denied errors.  even if I give 777 to boot.log (which is mentioned in the logs) it still wont start. 

Please advise. 

sudo docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                     PORTS               NAMES
bd9128ffbf01        emccorp/ecs-software-2.2.1:latest   "/opt/vipr/boot/boot."   36 minutes ago      Exited (1) 6 minutes ago                       ecsstandalone

Environment CentOS minimal with docker installed. 
uname -a
Linux bemecdd010.dta.inf 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

sudo docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64

 sudo docker logs bd9128ffbf01
07122016 12:31:02 : ############################### boot operation begin ############################
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:02 : checking 'which' command
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
which is /usr/bin/which
07122016 12:31:02 : exporting environment variable VIPR_DEPLOYMENT_TYPE to fabric
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : Parsing /host/data/network.json
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : VERSION: 2.2.1.0.77331.4f57cc6 private iface: 07122016 12:31:03 : file /host/data/network.json not found public iface: 07122016 12:31:03 : file /host/data/network.json not found START VIPR:
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : expecting data partitions to be mounted under /dae
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : StorageServer - setting partitionroot=/dae in /opt/storageos/conf/storageserver.conf
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : StorageServer JSON configuration file is /data/partitions.json
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
/opt/vipr/boot/boot_datasvcs_lib.sh: line 139: /data/partitions.json: Permission denied
07122016 12:31:03 : validating config.iso and fabric version file
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : config.iso is missing in the /data location
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : fetching network information
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : Data IP address of the machine: 07122016 12:31:03 : file /host/data/network.json not found
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : Management IP address of the machine: 07122016 12:31:03 : file /host/data/network.json not found
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : Geo IP address of the machine: 07122016 12:31:03 : file /host/data/network.json not found
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:: error fetching interface information: Device not found
07122016 12:31:03 : NETMASK found:
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied
07122016 12:31:03 : netmask could not be found from 07122016 12:31:03 : file /host/data/network.json not found
/opt/vipr/boot/boot_datasvcs_lib.sh: line 31: /var/log/boot.log: Permission denied

**Comment by APeter0807** [comment]
#147 seems to display the same symptoms and errors. Have you tried following the steps documented there?

**Comment by mandarmahajan** [comment]
Thank you Aaron. 

Yes that resolved the issue, Can this be included in a default installation script ? I could not find the solution that easy. 

if this is included then users will not face such issues.
