### ISSUE TITLE
How to expand node configuration

### ISSUE THREAD

**Issue by itot555** [EMCECS/ECS-CommunityEdition#153]
Is there procedure to expand node configuration ? 
For example, expand 4 nodes configuration to 8 nodes configuration.

**Comment by APeter0807** [comment]
There is currently no procedure to expand the node configuration for an installation of Community Edition, as that operation would be dependent on a data fabric layer not supported by the docker deployment. Changing to different node configuration would require uninstalling the existing software installation of ECS.

**Comment by itot555** [comment]
I understood that. Thanks.
