### ISSUE TITLE
Documentation refers to wrong license file

### ISSUE THREAD

**Issue by koensayr** [EMCECS/ECS-CommunityEdition#154]
The documentation for ECS says that the license file should be named license.xml, however only license.lic is included with the distribution. Messing around with the binaries it appears that license.lic is actually the proper name, and thus the documentation simply needs updating.

**Comment by APeter0807** [comment]
Fixed in c6e17e93685b12ba13008ac1a66e186838c3fa75 ;  were you seeing this referenced in a different place, as well?
