### ISSUE TITLE
Error getting correct IP address in OpenStack 

### ISSUE THREAD

**Issue by msalem2** [EMCECS/ECS-CommunityEdition#156]
When I tried the code with OS instance. The code break at line
 ip_address = subprocess.check_output(['hostname', '-i']).rstrip('\r\n')

It may better to replace the this line by
ip_address = socket.gethostbyname(socket.gethostname())

**Comment by padthaitofuhot** [comment]
Thank you for reporting.  This issue has been resolved in Installer 2.x.  Please reopen this issue if we can be of further assistance.  Thank you.
