### ISSUE TITLE
Error: Failed to connect to || INFO [root:638] Problem reaching authentication server

### ISSUE THREAD

**Issue by bencrist1988** [EMCECS/ECS-CommunityEdition#157]
**Background:**
We are running a muli-node install and get the same error (which keeps repeating). Using minimal install of CentOS we started with the smaller install (4 hosts 2 disks) and were getting the issue. We then kept trying to re-create the system (the same way and with turning off firewall rules) and eventually the install was successful. We are now are having issues when running it with more hosts and disks installed (5 hosts 22 disks).

**Install Script Step**: python step1_ecs_multinode_install.py --ips 10.170.18.218 10.170.18.219 10.170.18.221 10.170.18.222 --hostnames ecsmultinode0 ecsmultinode1 ecsmultinode3 ecsmultinode4 --disks sdb sdc --ethadapter em1 

**Error: See below image:**
![ecs multinode error](https://cloud.githubusercontent.com/assets/22174296/18725636/1744591a-800f-11e6-84d7-9bf77cb9e0a6.jpg)

Please advise on next troubleshooting steps,
Ben.

**Comment by APeter0807** [comment]
Was additionally contacted over e-mail; sent suggested fixes and prompted for response in weeks following. As there has been no contact from the reporter since, will close this if there is no update from the reporter in three days.
