### ISSUE TITLE
step2 script fails with IdentationError

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ECS-CommunityEdition#160]
Hi all

I wanted to reinstall with Version3. Ran the same script steps as for Version 2.2.

Now step2 fails with the following message:
  File "step2_object_provisioning.py", line 168
    stateCheck = subprocess.check_output(curlCommand, shell=True)
    ^
IndentationError: unexpected indent

Any ideas? Based on the documentation I did not find any differences on launching the step2 script.

Thanks, Holger

**Comment by APeter0807** [comment]
Fixed in 3b913fd, pulled into master.
