### ISSUE TITLE
No nodes included in storage pool (single node deployment on GCE)

### ISSUE THREAD

**Issue by bernhof** [EMCECS/ECS-CommunityEdition#166]
When deploying ECS (single node) on Google Compute Engine, the CreateObjectVArray (create storage pool) step of the object provisioning script (step2) never finishes, because no nodes seem to be added to the storage pool. As a result the `grep -c` command never finds any nodes in "readytouse" state.

What seems to be causing the issue is that we only specify the node name ("ecs1") when creating the storage pool, ie.:

```
python step2_object_provisioning.py --ECSNodes=ecs1 --Namespace=ns1 --ObjectVArray=sp1 --ObjectVPool=rg1 --UserName=user1 --DataStoreName=ds1 --VDCName=vdc1
```

And the payload:
```
{ "nodes":[ { "nodeId":"ecs1","name":"ds1", "virtual_array":"urn:storageos:VirtualArray:a5c45941-df1a-47ea-9453-
0ac449c9bd62","description":"ds1" }]}
```
On another instance I tried executing the step1 and step2 scripts manually, supplying the node internal IP as argument to step2 script:
```
python step2_object_provisioning.py --ECSNodes=10.132.0.2 --Namespace=ns1 --ObjectVArray=sp1 --ObjectVPool=rg1 --UserName=user1 --DataStoreName=ds1 --VDCName=vdc1
```
This worked, ECS was provisioned in no time.

**Solution**: change the startup script in [ecs_node_template.jinja](https://github.com/EMCECS/ECS-CommunityEdition/blob/master/ecs-single-node/gce/ecs_node_template.jinja) to determine internal IP address of node, and supply this instead of hostname as argument to step2 script. I'll see if I can find time to do a PR.

**Comment by APeter0807** [comment]
Fix in #167 looks good.
