### ISSUE TITLE
problems after reboot

### ISSUE THREAD

**Issue by LuisIjano** [EMCECS/ECS-CommunityEdition#169]
Hi, We had a problem at our DC and servers rebooted, after reboot docker do not start, I can run docker images but ther is no docker active:
[root@ecstestnode1 /]# df -k
Filesystem              1K-blocks     Used Available Use% Mounted on
/dev/mapper/centos-root  18307072  6977528  11329544  39% /
devtmpfs                 16381136        0  16381136   0% /dev
tmpfs                    16391328        0  16391328   0% /dev/shm
tmpfs                    16391328     8656  16382672   1% /run
tmpfs                    16391328        0  16391328   0% /sys/fs/cgroup
/dev/sdb1               104805380 94404768  10400612  91% /ecs/uuid-28715b70-c8db-448a-90c4-c0079a558124
/dev/sda1                  508588   170976    337612  34% /boot
tmpfs                     3278268        0   3278268   0% /run/user/0
[root@ecstestnode1 /]# docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
docker.io/emccorp/ecs-software-3.0.0   latest              cb57d5e37f2d        3 weeks ago         1.562 GB
[root@ecstestnode1 /]# docker start cb57d5e37f2d
Error response from daemon: No such container: cb57d5e37f2d
Error: failed to start containers: cb57d5e37f2d
[root@ecstestnode1 /]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@ecstestnode1 /]#

Also I can see that complains about not found a file - Error: network json file not found: /host/data/network.json.  But this file existe and it's ok:
[root@ecstestnode1 /]# cat /host/data/network.json
{"private_interface_name":"eno16777984","public_interface_name":"eno16777984","hostname":"ecstestnode1","data_ip":"10.5.131.40","mgmt_ip":"10.5.131.40","replication_ip":"10.5.131.40"}
[root@ecstestnode1 /]#

Is there anything I'm missing??

TKs in advance.

**Comment by APeter0807** [comment]
You can check that the docker container exists with `docker ps -a`

If the container didn't come back on reboot, you can start it manually using either `docker start ecsstandalone` or `docker start ecsmultinode` depending on your setup.

**Comment by APeter0807** [comment]
Resolved off-ticket; host completed the operation taking longer than expected.
