### ISSUE TITLE
additional_prep.sh fails

### ISSUE THREAD

**Issue by ryandotclair** [EMCECS/ECS-CommunityEdition#17]
There was a recent change to the additional_prep.sh file that gets pulled down with wget. It does not have execution permissions. This either needs to be addressed by the source or the step1 python script needs to include 'chmod a+x additional_prep.sh' in it....

Or even better, include the script in the git hub repo.

**Comment by padthaitofuhot** [comment]
This was resolved in the above commit.  Make sure your repo is synchronized to the upstream repo.

https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/
