### ISSUE TITLE
Document ECS CE Password Reset Procedure

### ISSUE THREAD

**Issue by pwbratach** [EMCECS/ECS-CommunityEdition#171]
Hi, 

I've taken over an EMC ECS Community Edition Multi-Node cluster for someone who left our company.  Can someone please help me figure out how to reset the password and possibly also unlock the account to the ECS portal, since the password I was given is not working, it displays the error "Unauthorized Login. Access is denied due to invalid or expired credentials.".  

Thanks, Paul

**Comment by pwbratach** [comment]
By the way, the user account I am trying to use is the root account.

**Comment by APeter0807** [comment]
There is a procedure for this, but it's a bit involved - you will have to do this from inside the container on any one of the hosts (one method is, on the host, use ``nsenter -i -m -p -u -t `pidof blobsvc` ``)

Enable vnest diagnostic tools:
`curl http://localhost:9101/nest/diagnosticEnabler?enabled=true -X PUT`
 
Delete the flag controlling the creation of predefined accounts:
`curl -X DELETE "http://<NODE IP>:9206/d/?path=/config/ObjectService/PredefinedLocalUsers&scope=paxos"`

Delete the corresponding root account record from vnest:
`curl -X DELETE "http://<NODE IP>:9206/d/?path=/config/ZkConfigTable/DS_urn:LocalUserInfoTable:/CB0SCAgEEgRyb290&scope=paxos"`

Restart provision service:
``kill –9 `pidof provisionsvc` ``

After the services, restart check in `/var/log/vipr/emcvipr-log/authsvc.log` that you see the following messages in the log; they should indicate successful recreation of root account:
```
2016-04-25 00:48:25,994 [SETUP-PREDEFINED-USERS]  INFO  LocalUserAPIServer.java (line 89) About to configure 2 pre-defined users 
2016-04-25 00:48:26,205 [SETUP-PREDEFINED-USERS]  INFO  LocalUserAPIServer.java (line 103) user root does not exist, will create one 
2016-04-25 00:48:26,341 [SETUP-PREDEFINED-USERS]  INFO  LocalUserAPIServer.java (line 110) user root has been created 
2016-04-25 00:48:26,375 [SETUP-PREDEFINED-USERS]  INFO  LocalUserAPIServer.java (line 96) user emcmonitor already exist, skip that one 
2016-04-25 00:48:26,382 [SETUP-PREDEFINED-USERS]  INFO  LocalUserAPIServer.java (line 96) user root already exist, skip that one 
2016-04-25 00:48:26,392 [SETUP-PREDEFINED-USERS]  INFO  LocalUserAPIServer.java (line 96) user emcmonitor already exist, skip that one 
2016-04-25 00:48:26,422 [SETUP-PREDEFINED-USERS]  INFO  LocalUserAPIServer.java (line 140) marking pre-defined users setup as done
```

After that, you should be able to login in UI as root using the default ChangeMe password; upon login you will be forced to change the password again.

Afterwards, disable vnest diagnostic tools by using the following command
`curl http://localhost:9101/nest/diagnosticEnabler?enabled=false -X PUT`

**Comment by pwbratach** [comment]
Aaron,

Thanks for the procedure, unfortunately, I receive an error on the second
step.

[root@ecs001 ~]# nsenter -i -m -p -u -t 17263
ecs001:/ # curl http://localhost:9101/nest/diagnosticEnabler?enabled=true
-X PUT
curl: (7) Failed to connect to localhost port 9101: Connection refused

I'm running a tail on the authsvc.log file and see that the cluster keeps
blacklisting one or more of the nodes and then retrying the cluster
heartbeat check.
I see a lot of these errors on the node that I am logged into (144):
2016-11-29 20:14:58,014 [client-heart-beat-monitor-000] ERROR
 RemoteOperation.java (line 111) Wait for write completion timed out.
RequestID c0a82890:158b1a91c78:1:f5 ServerIP XXX.XXX.XX.144
2016-11-29 20:14:58,015 [client-heart-beat-monitor-000]  WARN
 ClientHeartBeatImpl.java (line 83) server XXX.XXX.XX.144 not ok
2016-11-29 20:15:03,015 [client-heart-beat-monitor-000] ERROR
 RemoteOperation.java (line 111) Wait for write completion timed out.
RequestID c0a82890:158b1a91c78:1:f7 ServerIP XXX.XXX.XX.145
2016-11-29 20:15:03,016 [client-heart-beat-monitor-000]  WARN
 ClientHeartBeatImpl.java (line 83) server XXX.XXX.XX.145 not ok
2016-11-29 20:15:08,017 [client-heart-beat-monitor-000] ERROR
 RemoteOperation.java (line 111) Wait for write completion timed out.
RequestID c0a82890:158b1a91c78:1:f9 ServerIP XXX.XXX.XX.146
2016-11-29 20:15:08,018 [client-heart-beat-monitor-000]  WARN
 ClientHeartBeatImpl.java (line 83) server XXX.XXX.XX.146 not ok


Thanks,
Paul

**Comment by APeter0807** [comment]
Issue was not persistent after reboot, indicating an unhealthy authentication service.

Remaining open to suggestion on a successful reset procedure for the portal root admin password.

**Comment by padthaitofuhot** [comment]
Added @jasoncwik @adrianmo @msalem2 @twincitiesguy for input they may have into reset procedure for portal root admin password.

**Comment by padthaitofuhot** [comment]
Add @captntuttle to document procedure once we have it.

**Comment by padthaitofuhot** [comment]
There is no password reset capability currently available.

**Comment by niladrij** [comment]
![root](https://github.com/EMCECS/ECS-CommunityEdition/assets/156880240/d15cb0be-8620-46e5-a1b2-d03fae40385b)

Now it is simple to reset root passwd on a new deployment from OVA, seems root account do not have any password set by default , so passwd command gets you right at the prompt to define a new password which I pref keeping as ChangeMe
