### ISSUE TITLE
Disk partitioning during install unable to handle disks larger than 2TB properly

### ISSUE THREAD

**Issue by dassic** [EMCECS/ECS-CommunityEdition#173]
Hi!

The install script uses DOS partitioning label which limits the size to max 2 TB per partition. Can you change that to something else & more modern to overcome this limit or is there a good reason to keep as is ?

See error message below (on 6 TB disk) :

[06/Dec/2016 07:53:42] INFO [root:275] Partitioning the disk '/dev/sdn'
Device does not contain a recognized partition table
Building a new DOS disklabel with disk identifier 0x505e5c6c.

WARNING: The size of this disk is 6.0 TB (6000606183424 bytes).
DOS partition table format can not be used on drives for volumes
larger than (2199023255040 bytes) for 512-byte sectors. Use parted(1) and GUID 
partition table format (GPT).

The device presents a logical sector size that is smaller than
the physical sector size. Aligning to a physical sector (or optimal
I/O) size boundary is recommended, or performance may be impacted.
[06/Dec/2016 07:53:42] INFO [root:283] Make File filesystem in '/dev/sdn1'
meta-data=/dev/sdn1              isize=256    agcount=4, agsize=134217664 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=0        finobt=0
data     =                       bsize=4096   blocks=536870655, imaxpct=5
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=0
log      =internal log           bsize=4096   blocks=262143, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
[06/Dec/2016 07:53:44] INFO [root:288] Make /ecs/uuid-f731c5d6-39dd-4d82-a0cc-766cfc837bcf Directory in attached Volume
[06/Dec/2016 07:53:44] INFO [root:292] Mount attached /dev/sdn1 to /ecs/uuid-f731c5d6-39dd-4d82-a0cc-766cfc837bcf volume.

**Comment by dassic** [comment]
The culprint is this line in step1_ecs_multinode_install.py :

ps = subprocess.Popen(["echo", "-e", "\"o\nn\np\n1\n\n\nw\""], stdout=subprocess.PIPE)

This is piped to fdisk but fdisk will not work for disks above 2 TB so it should likely be changed to parted and look something like this (needs to be adjusted to fit ECS) :

parted -s -a optimal **/dev/sdm** mklabel gpt -- mkpart primary ext4 1 -1

**Comment by padthaitofuhot** [comment]
The new installer uses GPT, so this issue will resolve once the new installer is released.
