### ISSUE TITLE
Replication between two Single Node VMs

### ISSUE THREAD

**Issue by docdentz** [EMCECS/ECS-CommunityEdition#175]
Hi All, I am not able to setup replication between two single node ECS VMs. Is that an issue or on purpose like that?
When adding VDC I'll get the following (IP Adresses are correct): Virtual Data Center creation failure. Be sure that you have correctly entered the IP address(s) of online devices and that Data Services has completed initialization. Please correct input or retry after a few minutes. Service Error details: Error 7000 (http: 500): An error occurred in the API Service. An error occurred in the API service. Cause: error insertVdcInfo.

**Comment by Beowulf67** [comment]
Hi All.
Got the same with a multi node ECS. Is this an issue or is it not possible to get replication build?

**Comment by jasoncwik** [comment]
There's a very specific order that must be followed to set up multiple VDCs.  Once you create a local VDC, the cluster becomes "initialized" can cannot be joined to another VDC at that point.  The order needs to be this:

1. Run "step1" on VDC1
2. Run "step1" on VDC2

If you're using the "step2" script, do the following:
3. Run the "step2" script on VDC1
4. Run the "step2" script on VDC2, but pass the argument `--SkipVdcProvision`

If you're using manual provisioning in the GUI, do the following:
3. On VDC1, install license, initialize storage pool, and create VDC.
4. On VDC2, install license, and initialize storage pool.  *Do not create VDC*

For both provisioning flows, now do the following:
5. Login to VDC2.  Go to the Manage->Virtual Data Center screen and click "Get VDC Access Key".  Copy this to your clipboard.
6. Logout and login to VDC1.  Go to Manage->Virtual Data Center and click "New Virtual Data Center".  Configure the endpoints with the IP(s) of VDC2 and paste in VDC2's access key.

**Comment by jasoncwik** [comment]
@captntuttle Assigning to you to document this procedure.

**Comment by captntuttle** [comment]
https://github.com/EMCECS/ECS-CommunityEdition/wiki/Multiple-VDC's

**Comment by Beowulf67** [comment]
Hi all checked it - works as descriped
