### ISSUE TITLE
Pull images with authentication required error

### ISSUE THREAD

**Issue by bai030805** [EMCECS/ECS-CommunityEdition#177]
Hi All

i try to install ecs single node mode, when the script pulling images from internet. it gives below error.

5e222c23f917: Waiting 
d174a3b8f3ad: Waiting 
44cb462f9750: Waiting 
c9658e216906: Waiting 
f8d44c7c1891: Waiting 
unauthorized: authentication required
unauthorized: authentication required

**Comment by jasoncwik** [comment]
Are you behind a proxy server that requires authentication?  You can stop the docker process and run it in debug mode to get more info 
```
sudo systemctl stop docker
sudo docker -d -D
```

**Comment by padthaitofuhot** [comment]
@bai030805 Have you had an opportunity to investigate this solution further?

**Comment by padthaitofuhot** [comment]
Please reopen this issue if we can be of further assistance.  Thank you.
