### ISSUE TITLE
ECS Community Edition is not compatible with IBM Tivoli Monitoring (k10agent)

### ISSUE THREAD

**Issue by jasoncwik** [EMCECS/ECS-CommunityEdition#178]
## Issue
ECS Community edition will fail to completely initialize the storage pool on machines that have the IBM Tivoli Monitoring agent installed.  The storage pool will forever stick in the "Initializing" state and attempts to create a VDC will result in HTTP 400 errors.

## Analysis
Doing a `ps -ef` inside the container will show that dataheadsvc and metering are restarting frequently.  Looking at `/opt/storageos/logs/metering.log` will show a bind exception on port 10110.  This port is already bound by Tivoli's `k10agent` process.

## Workaround
1. Uninstall Tivoli Monitoring
or
2. Change the port on impacted nodes.

### Changing the port on ECS
On _all_ nodes, you will need to edit `/opt/storageos/conf/mt-var.xml` to change the bind port from 10110 to 10109.  Edit the file and change the line:

```
            <property name="serviceUrl" value="service:jmx:rmi://127.0.0.1:10110/jndi/rmi://127.0.0.1:10111/sos" />
```

to:

```
            <property name="serviceUrl" value="service:jmx:rmi://127.0.0.1:10109/jndi/rmi://127.0.0.1:10111/sos" />
```

Then restart the metering service:

```
kill `pidof metering`
```

**Comment by jasoncwik** [comment]
Opened #179 to have the installer to try and check for conditions like this before installation.

**Comment by captntuttle** [comment]
https://github.com/EMCECS/ECS-CommunityEdition/wiki/IBM-Tivoli-Monitoring
