### ISSUE TITLE
problem creating VDC

### ISSUE THREAD

**Issue by LuisIjano** [EMCECS/ECS-CommunityEdition#181]
Hi Guy, 
I created 2 virtual ECS system and create local VDC and buckets without problems on both.
When I try to add VDC from ecs2 into ecs1 system I got the following problem:
"Virtual Data Center creation failure. Be sure that you have correctly entered the IP address(s) of online devices and that Data Services has completed initialization. Please correct input or retry after a few minutes. Service Error details: Error 7000 (http: 500): An error occurred in the API Service. An error occurred in the API service. Cause: error insertVdcInfo."
My ECS1 system has the following config: 1 IP / VDC local with ECS1 IPs
My ECS2 system has the following config: 1 IP / VDC local with ECS2 IPs
The problem was when I try to add on ECS1 VDC2 (with key from vdc2) + IPs of ECS2 into this VDC. I wanna test ECS replication, that is why I'm creating this.

Is there any commando I can run into docker to see logs, status, to understand where is the problem?

regards,

**Comment by jasoncwik** [comment]
Hi Luisljano,

The issue here is the same as #175 .  When you created the VDC on ecs2, the cluster became "initialized" and cannot be joined with another VDC.  You only create the VDC on ecs1 and then add ecs2's VDC on ecs1.  See the steps in #175 for details.

**Comment by LuisIjano** [comment]
sorry Jason,

I just saw later.. I was able to create both VDCs now on my ecsnode1

tks.
