### ISSUE TITLE
Work around transient NIC device names in CentOS

### ISSUE THREAD

**Issue by russfellows** [EMCECS/ECS-CommunityEdition#184]
Help anyone?  I am unable to get past Step1 of the installation.  I have read other issues here on the community, but so far to no avail.   Here are the issues:

1. I have no GUI on any of the 443 ports (that is 443, 4443 or 64443).  
2. After rebooting each of my 4 nodes in my ECS multimode setup, the docker images fail to run.  I have never been able to get past the "Install Step 1" process, which reported it completed on all four nodes. 
3. Docker is running and a ps -a shows that the image starts, but then quickly dies, the output is similar for each of my 4 hosts.  
4. If I try to run the docker image directly, I get an error message about the "/host/data/network.json" not found, but the file exists.  

I have checked my network settings, I have IPV6 disabled, my hostname matches my configuration, the hostname -i returns the correct IP address. etc. etc.  

Se below for example output:

```
[root@ecs-2 ~]# docker run emccorp/ecs-software-3.0.0:latest 
01/10/17 01:24:36: ############################### boot operation begin ############################
01/10/17 01:24:36: checking 'which' command
which is /usr/bin/which
01/10/17 01:24:36: exporting environment variable VIPR_DEPLOYMENT_TYPE to fabric
01/10/17 01:24:36: Error: network json file not found: /host/data/network.json

[root@ecs-2 ~]# cat /host/data/network.json
{"private_interface_name":"ens161","public_interface_name":"ens161","hostname":"ecs-2","data_ip":"172.16.1.132","mgmt_ip":"172.16.1.132","replication_ip":"172.16.1.132"}

[root@ecs-2 ~]# ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtg 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:76:31:f2:5e  txqueuelen 0  (Ethernet)
        RX packets 6  bytes 432 (432.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens161: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtg 1500
        inet 172.16.1.132  netmask 255.255.0.0  broadcast 172.16.255.255
        ether 00:50:56:88:0d:34  txqueuelen 1000  (Ethernet)
        RX packets 8784  bytes 641478 (626.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1149  bytes 112205 (109.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtg 65536
        inet 127.0.0.1  net mask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 34  bytes 2788 (2.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 34  bytes 2788 (2.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@ecs-2 ~]# hostname
ecs-2
[root@ecs-2 ~]# hostname -i
172.16.1.132
```

Running the "docker ps -a" shows that the ECS image dies just after starting

```
[root@ecs-2 ~]# docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                         PORTS               NAMES
b8466ce0fb5d        emccorp/ecs-software-3.0.0:latest   "/opt/vipr/boot/boot."   8 minutes ago       Exited (1) 8 minutes ago                           jovial_mayer
e8ff78186086        emccorp/ecs-software-3.0.0:latest   "/opt/vipr/boot/boot."   16 minutes ago      Exited (1) 16 minutes ago                          pedantic_liskov
50d20ab82b41        emccorp/ecs-software-3.0.0:latest   "/opt/vipr/boot/boot."   24 minutes ago      Exited (1) 24 minutes ago                          gigantic_bhaskara
40179c17c7d8        emccorp/ecs-software-3.0.0:latest   "/opt/vipr/boot/boot."   37 minutes ago      Exited (1) 37 minutes ago                          elated_snyder
ebec70d30d39        emccorp/ecs-software-3.0.0:latest   "/opt/vipr/boot/boot."   38 minutes ago      Exited (1) 38 minutes ago                          modest_bardeen
d707d69a27a0        emccorp/ecs-software-3.0.0:latest   "/opt/vipr/boot/boot."   40 minutes ago      Exited (1) 40 minutes ago                          evil_jang
203c43374acb        hello-world                         "/hello"                 46 minutes ago      Exited (0) 46 minutes ago                          gloomy_sammet
c54372be279c        emccorp/ecs-software-3.0.0          "/opt/vipr/boot/boot."   About an hour ago   Exited (1) About an hour ago                       ecstatic_mayer
b48aceaaa1f5        emccorp/ecs-software-3.0.0:latest   "/opt/vipr/boot/boot."   3 hours ago         Exited (1) 34 seconds ago                          ecsmultinode
```

**Comment by jasoncwik** [comment]
Hi Russ,

I believe you are seeing issue #147.  Did you download from the releases page?  Can you checkout the latest from git?

```git clone https://github.com/EMCECS/ECS-CommunityEdition.git```

**Comment by russfellows** [comment]
Jason,

Thanks for the pointer.  This information did solve the docker problem, but not the bigger issue.

So, in following the fixes here, then rebooting all four nodes, I see that the “ecsmultinode” docker image is in fact running on all 4 nodes.

However, there remains no web browser access to any of the four nodes.  That is bringing up the IP address in a web browser URL with https:// in front, or with “:443” or “:4443” or “:64443” appended for the port shows a “Can’t connect to server” error message.

In checking netstat for open ports, it shows in fact that nothing is running on port 443.  Here is the relevant output:

[root@ecs-1 ~]# docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS               NAMES
e09d3453eca6        emccorp/ecs-software-3.0.0:latest   "/opt/vipr/boot/boot."   20 hours ago        Up 8 minutes                            ecsmultinode
[root@ecs-1 ~]# 
[root@ecs-1 ~]# netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 172.16.1.97:9099        0.0.0.0:*               LISTEN      14006/storageserver 
tcp        0      0 172.16.1.97:9069        0.0.0.0:*               LISTEN      14006/storageserver 
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      11368/rpcbind       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1223/sshd           
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      1205/cupsd          
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1720/master         
tcp        0      0 127.0.0.1:64443         0.0.0.0:*               LISTEN      14086/ecsportalsvc  
tcp6       0      0 :::111                  :::*                    LISTEN      11368/rpcbind       
tcp6       0      0 :::22                   :::*                    LISTEN      1223/sshd           


This output is identical on all four nodes, except of course they all use their own IP’s in the local address as appropriate. 

Thoughts?

Thanks for the assistance.

—Russ

**Comment by russfellows** [comment]
Jason,

Also, I forgot to mention, but there is no need for me to get the newest release, because I just pulled it for the very first time 4 days ago.  In checking the updates, nothing has been updated in the last 4 days.  So, I have the very latest version.   Not sure why fix #147 wasn’t taken care of.  

The whole networking part of the setup is quite tenuous.  Each system really should be configured completely independently from other nodes.  Then they need to be told about each other during step 2 process.  The way of specifying the ethernet interface is also quite poor, because CentOS likes to create random names for the ethernet interface, which is VERY difficult to change.  As a result, the interface name of some of my nodes was different.  It was “ens161” on some and “ens192” on others.  It was also set to “eth0” on one node for a while, but then it changed itself.  

Having to specify the interface “name” only once for each of the nodes during the “Step 1” process is just not a good design.  

Just MHO.  Thanks for taking feedback.

—Russ

**Comment by jasoncwik** [comment]
From your `netstat` output, it appears that the only ECS services running are `storageserver` and `ecsportalsvc`.  The rest of the services are failing to start.  Can you please start the container and attach to get the output during container startup?

```
docker stop ecsmultinode
docker start -a ecsmultinode 2>&1 | tee containerboot.log
```

Also, you might want to try entering the container and checking coordinatorsvc to see if it failed to init:

```
[root@ecs ~]# nsenter -i -m -p -u -t `pidof authsvc`
ecs:/ # less /opt/storageos/logs/coordinatorsvc.log
```

As for the setup procedure, yes, we are working on a new ansible-based installer for multinode and more streamlined single-node procedures.  However, we _can't_ wait until step 2 to tell the services about each other.  At the heart of ECS is a service called `vnest` that implements the distributed-consensus algorithm Paxos to coordinate the state among cluster members.  In order for ECS to initialize, we need to know about all the cluster members so we can establish consensus among the members (by electing leaders) and initialize the core services.

**Comment by russfellows** [comment]
This does show some errors, but not sure exactly how to fix.  

Perhaps I should re-run the "Step 1" process?  I'm open to any suggestions.  Previously, I re-ran the install 2x previously before posting here.  Obviously the "Fix #147" problems were part of the issue, so now that is solved, perhaps a reinstall would work this time?

See below for output of ecsmultinode startup.  

```
[root@ecs-1 ~]# docker stop ecsmultinode
ecsmultinode
[root@ecs-1 ~]# docker start -a ecsmultinode 2>&1 | tee containerboot.log
01/10/17 17:05:46: ############################### boot operation begin ############################
01/10/17 17:05:46: checking 'which' command
which is /usr/bin/which
01/10/17 17:05:46: exporting environment variable VIPR_DEPLOYMENT_TYPE to fabric
01/10/17 17:05:46: Parsing /host/data/network.json
01/10/17 17:05:46: VERSION: 3.0.0.0.85754.f41b34f private iface: ens192 public iface: ens192 START VIPR:
01/10/17 17:05:46: expecting data partitions to be mounted under /dae
01/10/17 17:05:46: StorageServer - setting partitionroot=/dae in /opt/storageos/conf/storageserver.conf
01/10/17 17:05:46: StorageServer JSON configuration file is /data/partitions.json
01/10/17 17:05:46: partitions.json already exists - will not generate it
01/10/17 17:05:46: validating config.iso and fabric version file
01/10/17 17:05:46: config.iso is missing in the /data location
01/10/17 17:05:46: fetching network information
01/10/17 17:05:46: Data IP address of the machine: 172.16.1.97
01/10/17 17:05:46: Management IP address of the machine: 172.16.1.97
01/10/17 17:05:46: Geo IP address of the machine: 172.16.1.97
01/10/17 17:05:46: NETMASK found: 255.255.0.0
01/10/17 17:05:46: Created /opt/storageos/conf/network
01/10/17 17:05:46: IPADDR='172.16.1.97'
01/10/17 17:05:46: All validations are complete. Going ahead with the configuration steps.
01/10/17 17:05:46: populating vipr shared library path
01/10/17 17:05:46: /opt/storageos/lib is already populated
01/10/17 17:05:46: creating scsi device nodes
01/10/17 17:05:54: creating volumes skeleton containers
01/10/17 17:05:54: populating vipr network info in fabric identifier
01/10/17 17:05:54: fixing svcuser account permissions
chown: invalid user: 'svcuser:users'
01/10/17 17:05:54: updating storageos property to datanode
01/10/17 17:05:54: fixing file permissions
01/10/17 17:05:54: fixing storageos and data ownership
01/10/17 17:05:54: creating place holders file
01/10/17 17:05:54: preparing vipr configuration information
cp: cannot stat '/data/config.iso': No such file or directory
01/10/17 17:05:54: Starting the rpcbind service
01/10/17 17:05:54: Initializing configuration properties
01/10/17 17:05:54: Generating configuration files
/etc/systool: Warning: Fabric deployment. Skipping _bootfs_mount_ro()
01/10/17 17:05:58: Generation failed
/etc/init.d/storageos-dataservice: line 100: /proc/sys/kernel/core_pattern: Read-only file system
Warning: Found stale pidfile(s) (unclean shutdown?)
Setting up SSL certificates  ...done
Starting ViPR services..done
service: no such service cron
Starting nginx service 
..done
mkfifo: cannot create fifo '/var/run/.boot_sh_pipe': File exists
```

**Comment by jasoncwik** [comment]
Hmm... from the above it sounds like boot is successful... Yes, why don't you try starting everything again clean.

**Comment by russfellows** [comment]
OK,

The install with “—cleanup” succeeded on all nodes.  But, before I reinstall again, here is the issue.  

On three of four nodes the ethernet interface is “ens192”.  However, on the fourth node it is “ens161”.  

How do I do the install with different interface names?  I have tried reinstalling this host, but it continually gets different ethernet interface names.  Not always the same.  By the way, these are VM’s, and I have cloned VM’s and created them from scratch, but 1 or 2 nodes always have different interface names than others.  I just LOVE (not) CentOS.  

[root@ecs-1 ecs-multi-node]# ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:6b:b4:32:91  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens192: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.1.97  netmask 255.255.0.0  broadcast 172.16.255.255
        ether 00:50:56:88:d2:d1  txqueuelen 1000  (Ethernet)
        RX packets 78303  bytes 17421223 (16.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 60262  bytes 3724292 (3.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 1188  bytes 4668557 (4.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1188  bytes 4668557 (4.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@ecs-2 ecs-multi-node]# ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:84:08:36:a5  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens161: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.1.132  netmask 255.255.0.0  broadcast 172.16.255.255
        ether 00:50:56:88:0d:34  txqueuelen 1000  (Ethernet)
        RX packets 78663  bytes 6621816 (6.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 63076  bytes 4519244 (4.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 6052  bytes 338753 (330.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6052  bytes 338753 (330.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0



Thanks,
—Russ

**Comment by russfellows** [comment]
Solved:

First I had to fix the inconsistent ethernet names across hosts.  

Despite many different methods stated on CentOS and other sites, the only set of instructions that seemed to keep the ethernet interface name across a reboot was the following steps.  [https://www.certdepot.net/rhel7-restore-old-network-interface-name/](url)

After getting changing all interfaces to be "eth0" and re-running the step1, I now have all 4 nodes running all services, and the web page does indeed appear on port 443, ready for step2.  

I believe there were several things that cause this.  First was fix #147, which doesn't seem to be fixed, even with my latest version of ECS 3.0 code.  

Second, in CentOS ipv6 is on by default, which causes problems.  Also, they use a "device" based naming scheme for the ethernet interface, which also must be disabled.  

SO, after fixing all three of these issues, and then running an install it appears to finally work.  Looks like issues with stock CentOS7 being not compatible with the install scripts as they currently exist.

**Comment by jasoncwik** [comment]
Interesting.  While we've noticed the name of the interfaces being different for instances of CentOS, we've never seen them _change_ between reboots.

Re-opening and assigning to @captntuttle.  Ken, can you document the procedure to document IPv6 and the troubleshooting for the interface name?  @adrianmo can you make sure the install scripts check to make sure IPv6 is disabled?

**Comment by padthaitofuhot** [comment]
This has some interesting implications for when we implement the Network Separation features of ECS in ECS CE.  I'm adding myself to this issue and tagging it "requirement" so it will get properly researched.

**Comment by padthaitofuhot** [comment]
Evidence (the issue pile) suggests this is a rare occurrence.  I've been unable to duplicate it and this is the only ticket logged so far where this has been an issue.  

If the MAC address or UUID/GUID of the NIC changes between reboots for some reason, this situation could develop.  However, various clouds, vBox/Vagrant, and VMWare pin those values in the VM metadata.  Hardware nodes shouldn't see this issue unless the NIC is changed between reboots.  

One case that comes to mind where this could be an issue is with multi-port hardware NICs.  There were some pinning issues with the kernel drivers for Intel NICs a while back (2007-ish IIRC) where the ports could swap their /dev/names between reboots.  Pretty sure that isn't the problem here though.

**Comment by padthaitofuhot** [comment]
@captntuttle Please link the associated documentation for this issue in a comment here. Thanks!

**Comment by captntuttle** [comment]
http://ecsce.readthedocs.io/en/latest/troubleshooting/ECS-Troubleshooting.html#get-correct-interface-name
