### ISSUE TITLE
New multinode ECS detects only one node/disks while creating stgpool

### ISSUE THREAD

**Issue by bhavenjp** [EMCECS/ECS-CommunityEdition#185]
I have encountered this strange issue where
1) A new multinode (6 nodes) ECS is installed
2) Logged to GUI
3) root password is changed
4) License is uploaded
however while creating storage pool, it detects only one node (instead of all 6) and its disks as shown below.

Issue:
![stgpool_error](https://cloud.githubusercontent.com/assets/20352933/21810407/9db27602-d786-11e6-93aa-7b7a954a6efc.JPG)

Installation output:
![multinode_install_log](https://cloud.githubusercontent.com/assets/20352933/21810424/b6469fc2-d786-11e6-96a2-457b41d80b6c.JPG)

Has anyone see this before? Any idea what could be wrong?
--> SELinux is set to permissive
--> Tried this with firewalld service stopped as well as active with required ports allowed for multinode (as per doc) - same issue.
--> Tried this on 4x node as well as 6x node cluster - same issue.
And the strange thing is both the times it detects last node (4th and 6th respectively) while other nodes are not detected.

**Comment by jasoncwik** [comment]
Can you check the contents of `/host/files/seeds` and `/etc/hosts` on each node to make sure they're the same?

**Comment by jasoncwik** [comment]
Can you also provide the output `netstat -anp` from the base OS?  It's possible there's a service conflict with something the customer installed.

**Comment by bhavenjp** [comment]
Hi Jason,
Used the latest files from github.
The hosts and seeds files look good ... same entries.
And not other services found.

Is it possible to check this on webex?

**Comment by bhavenjp** [comment]
Hi Jason,

Not sure if this is a bug or what..as GUI can only detect one node.


When I use step2 script it adds all the nodes(6) to the stgpool. However the hostnames are not correctly taken.
![stgpoolmgmt](https://cloud.githubusercontent.com/assets/20352933/21919446/753a4e50-d995-11e6-8c9a-4b75fdc4b93a.JPG)

Hardware health of the stgpool still displays only one node, not 6.
![hwdhealth_pool](https://cloud.githubusercontent.com/assets/20352933/21919459/8d4b61b4-d995-11e6-83a1-800c21d1f426.JPG)

Hardware health screen only displays "online nodes" two (2) and offline zero(0) - which doesn't match.
![hwdhealth](https://cloud.githubusercontent.com/assets/20352933/21919495/d572876a-d995-11e6-892c-fca65958babe.JPG)


For your advise please.

**Comment by jasoncwik** [comment]
I still fell like you have host resolution issues.  Would you be available for a WebEx?

**Comment by bhavenjp** [comment]
Hi Jason,

Noted. As currently the testing is in-progress, I shall let you know when we need your help for this topic via webex? Thanks

**Comment by padthaitofuhot** [comment]
@bhavenjp Yes, please let us know here when you're available for WebEx support with the environment.

**Comment by bhavenjp** [comment]
Hi Jason, Travis,

Thanks for your support.
The evaluation environment had to be torn down due to resource constraints.
You may close the ticket.


Regards
--
Bhaven Parmar
+65 8818 1741

**Comment by padthaitofuhot** [comment]
I understand.  Please let us know if we can help with anything else, perhaps at a later time.
