### ISSUE TITLE
Tunable parameters

### ISSUE THREAD

**Issue by spirilis** [EMCECS/ECS-CommunityEdition#191]
So I'm well aware this Community Edition is not meant for performance and certainly not production use, but for those of us having fun with it who can't help themselves (but must tinker), can we get any insight as to what tunables exist in /opt/storageos/conf (inside the docker)?  I'm assuming that's where most of the service config parameters are, appears to be anyhow...

Specifically, are there any tunables that assist in increasing NFS I/O throughput or can improve performance of posting small files, perhaps by modifying cache parameters (at the expense of RAM usage) and/or threading parameters (for those providing more than 4 vCPUs to our install)?

**Comment by padthaitofuhot** [comment]
Hello and thanks for your patience.  I'm not sure what's publicly available in this regard, but I'll see what i can find.

**Comment by jasoncwik** [comment]
Hi @spirilis,

We don't generally want users tinkering with the configurations, but you could increase the heap sizes of dataheadsvc and blobsvc in /opt/storageos/bin.

No guarantees you won't brick your system by changing things.
