### ISSUE TITLE
Max number of tokens exceeded for this user

### ISSUE THREAD

**Issue by itot555** [EMCECS/ECS-CommunityEdition#193]
root user couldn't access with management API.
does anyone fix that ?

I masked a part of following log.

curl -L --location-trusted -k https://aaa.bbb.ccc.ddd:4443/login -u 'root:xxxxxx' -v
`About to connect() to aaa.bbb.ccc.ddd port 4443 (#0)`
`  Trying aaa.bbb.ccc.ddd...`
`Connected to aaa.bbb.ccc.ddd (aaa.bbb.ccc.ddd) port 4443 (#0)`
`Initializing NSS with certpath: sql:/etc/pki/nssdb`
`skipping SSL peer certificate verification`
`SSL connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA`
`Server certificate:`
`    subject: CN=localhost`
`    start date: 10月 04 19:19:47 2016 GMT`
`    expire date: 10月 02 19:19:47 2026 GMT`
`    common name: localhost`
`    issuer: CN=localhost`
`Server auth using Basic with user 'root'`
`GET /login HTTP/1.1`
`Authorization: Basic xxxxxxxx`
`User-Agent: curl/7.29.0`
`Host: aaa.bbb.ccc.ddd:4443`
`Accept: */*`

`HTTP/1.1 401 Unauthorized`
`Date: Fri, 03 Mar 2017 07:20:09 GMT`
`Content-Type: application/xml`
`Content-Length: 283`
`Connection: keep-alive`

`Connection #0 to host aaa.bbb.ccc.ddd left intact`
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
`<error>`
`<code>4000</code>`
`<description>Invalid credentials or authentication token provided to access to this resource</description>`
`<details>Max number of tokens exceeded for this user</details>`
`<retryable>false</retryable>`
`</error>`

**Comment by meetgrinder** [comment]
Are you continuously creating new tokens?
There is a limit to the number allowed per day.
If you have a script that's doing logins frequently, it should send any existing token in the X-SDS-AUTH-TOKEN header of the login request.

**Comment by itot555** [comment]
Thanks for your advice.
So, I would like to fix this issue.
How can I fix that ??

BR

**Comment by meetgrinder** [comment]
You can use the ecscli which you can install via "pip install ecscli" which will handle tokens for you.
Or you can follow what I was saying in my previous comment...
send any existing token in the X-SDS-AUTH-TOKEN header of the login request.

**Comment by yhidai** [comment]
Thanks for your comment.
If I lost all existing tokens, only I can do is waiting for the next day?
Can I reset the available tokens in the authentication server directly ?

**Comment by meetgrinder** [comment]
to that node... but tokens are per node. So you could just authenticate against a different node in the vdc

**Comment by padthaitofuhot** [comment]
The best way to use the ECS Management API is either through, as @meetgrinder suggests, the cli client, or the python-ecsclient module for Python (https://github.com/EMCECS/python-ecsclient).

**Comment by padthaitofuhot** [comment]
If we can be of further assistance, please reopen this issue.  Thanks!
