### ISSUE TITLE
Date/time format issue

### ISSUE THREAD

**Issue by bipsendk** [EMCECS/ECS-CommunityEdition#194]
A colleague has been doing some testing towards a single-node setup I did (for development purposes), and has notified me, that object/user/info should return ISO 8601 formatted timestamps - but instead returns e.g. "Wed Mar 01 13:32:21 UTC 2017"

Is there a place, where we can verify/change the settings - to ensure the right format of the timestamps ?

**Comment by padthaitofuhot** [comment]
Indeed, this appears to be a bug as reported.  The ECS Management API does clearly state that these timestamps should be presented in ISO 8601 format (https://www.emc.com/techpubs/api/ecs/v3-0-0-0/UserManagementService_getUserInfo_aff8efb3d588bdf7fdaf10d31b0fdd44_b2081f90369a6d96de7811240fd3b244_detail.htm).  Thank you for bringing this to our attention.

**Comment by jasoncwik** [comment]
@meetgrinder can you triage this and open a STORAGE jira for it?

**Comment by padthaitofuhot** [comment]
@meetgrinder bump bump

**Comment by padthaitofuhot** [comment]
@jasoncwik Do you happen to know if this was ever resolved upstream?
