### ISSUE TITLE
Migrate Hadoop HDFS data to ECS

### ISSUE THREAD

**Issue by imYerik** [EMCECS/ECS-CommunityEdition#198]
Hello all,
I have a lot of data stored in Hadoop HDFS, I want to archive the cold data to ECS. Are there some practical way? 

Can distcp or S3Distcp be used in this scenario？

**Comment by padthaitofuhot** [comment]
Hi @imYerik .  This is a good question.  I'll look into possible solutions and get back to you.

**Comment by imYerik** [comment]
Thank you! :) @padthaitofuhot

**Comment by jasoncwik** [comment]
Hi Yerik,

You should be able to use s3distcp or distcp.  If s3distcp uses the s3a driver, note that there was an [issue we fixed](https://issues.apache.org/jira/browse/HADOOP-11687) so you'll need to ensure you have the latest s3a driver.  With distcp, you'll want to set up ECS's HCFS driver "viprfs" as a secondary FS and then distcp from hdfs://... to viprfs://... Instructions on installing our HCFS driver can be found in our [Data Access Guide](http://doc.isilon.com/ECS/3.0/DataAccessGuide/wwhelp/wwhimpl/js/html/wwhelp.htm#href=vipr_c_hdfs_ViPRHDFS_intro.html).

**Comment by padthaitofuhot** [comment]
Please reopen the ticket if we can assist further.  Thank you.
