### ISSUE TITLE
Installer must have public key initial auth capability

### ISSUE THREAD

**Issue by padthaitofuhot** [EMCECS/ECS-CommunityEdition#205]
The installer is currently able to perform initial authentication using usernames and passwords only.  It goes on to generate SSH keys and distribute them to nodes, but it cannot currently perform this initial auth using existing public keys.

Solving this probably looks like:
1. bootstrap argument for accepting a keypair
2. install keypair as installer ssh keys 
3. skip ssh key generation and distribution

**Comment by captntuttle** [comment]
Affects GCE

**Comment by padthaitofuhot** [comment]
This requirement is resolved by #270
