### ISSUE TITLE
A Global testing strategy

### ISSUE THREAD

**Issue by padthaitofuhot** [EMCECS/ECS-CommunityEdition#217]
We need one.  Currently this thing is awkward to test, especially the Ansible stuff.  Let's set up a meeting to talk about this.

**Comment by adrianmo** [comment]
@padthaitofuhot you are right, we absolutely need it. Let me share a workflow proposal for the end-to-end testing of the new installer and hopefully we can work from there.

On every commit, the CI agent would do the following:

* spin up a couple of ephemeral VMs in our lab or AWS with the minimum hardware requirements (one for the installer, and the other as the target node). We can spin up more target VMs to test multi-node deployments;
* populate a `deploy.yml` template with the VMs information;
* run the bootstrap script in the installer VM;
* run step1, this will validate the Ansible playbooks and roles;
* run step2, this will validate that the ECS system is operational;
* tear everything down

We could use caches and local mirrors for Docker images and packages to speed up the process.

We could also configure multiple pipelines to test different configurations (e.g. single node, multi node, CentOS, RHEL, Ubuntu, with/without internet, multiple VDCs, etc.).

Open for discussion.

**Comment by padthaitofuhot** [comment]
https://hub.docker.com/_/jenkins/

**Comment by adrianmo** [comment]
Working on this in #269
