### ISSUE TITLE
Install error in step1_ecs_singlenode_install.py

### ISSUE THREAD

**Issue by amarcionek** [EMCECS/ECS-CommunityEdition#22]
After pulling the latest and re-running the install, I get this:

[27/Aug/2015 17:29:25] INFO [root:484] Clean up local files
Traceback (most recent call last):
  File "step1_ecs_singlenode_install.py", line 659, in <module>
    main()
  File "step1_ecs_singlenode_install.py", line 651, in main
    getAuthToken(ip_address,root,ChangeMe)
NameError: global name 'root' is not defined

Seems its when polling for the auth service.

**Comment by APeter0807** [comment]
Looks like the credentials for token authentication weren't getting properly formatted as strings.

You can either change line 651 to:

`getAuthToken(ip_address,"root","ChangeMe")`

Or update the latest version of `step1_ecs_singlenode_install.py` to fix this issue.

**Comment by amarcionek** [comment]
I can confirm @APeter0807 fix in #23 works.
