### ISSUE TITLE
scripts do not work with linux distributions that don't use YUM.

### ISSUE THREAD

**Issue by lundjEMC** [EMCECS/ECS-CommunityEdition#24]
SuSE related distributions use zypper as the package manager instead of YUM.  The EMC ECS appliance uses SuSE's SLES distribution.  Is there a reason SuSE is not supported for the Community Edition of ECS?

**Comment by padthaitofuhot** [comment]
@lundjEMC, that's an excellent question. Eventually we'd like to support more distributions, but it's tough going when the community is so small.  Feel free to send pull requests!  If you get ECS-CE working on OpenSuSE, we'd love to hear about it and see the code changes you made to get there.

**Comment by pbutlerm** [comment]
@lundjEMC  I have not tested with SLES, but we can put a flag on the script for step 1 with the Linux Distro and call the specific update functions as needed. As @padthaitofuhot  explains, currently we  support RH and derivatives. If you can test and propose a pull request we can check and approve.

**Comment by lundjEMC** [comment]
I'm working with someone who's using CoreOS at the moment, I'll try to propose changes for SLES in Sept. if I can.

**Comment by lundjEMC** [comment]
FYI - got an ECS single node system up with a SLES 12 (G3 Azure vm) using modified scripts from my fork here: https://github.com/lundjEMC/ECS-CommunityEdition.  I'm going to get the same scripts to work for CoreOS (and maybe RHEL based OS) before I try to propose a pull request.  Then maybe I'll attempt multi-node script edits.

**Comment by padthaitofuhot** [comment]
That's awesome.  I was looking at the zypper support you added in your branch the other day.  Looking good.  I'll be looking forward to your PR.  Do keep in mind that we currently only QA on RHEL/CentOS 7, so other distros will be in the "unsupported" category for the foreseeable future.  However, as we add distros to QA, it will be helpful to have install support already included.

**Comment by padthaitofuhot** [comment]
@lundjEMC You'll be interested to know I'm adding support for more Linux distributions to the new installer.  Look at the issues list for the Installer 2.1.0 milestone: https://github.com/EMCECS/ECS-CommunityEdition/milestones/Installer%202.1.0
