### ISSUE TITLE
Document local ports required by ECS, including those on lo0 and the Docker host iface

### ISSUE THREAD

**Issue by padthaitofuhot** [EMCECS/ECS-CommunityEdition#243]
Raised by #180 

A yaml port list can be found here: ui/ansible/vars/ports.yml

**Comment by padthaitofuhot** [comment]
If workarounds are possible, document those as well.  Known conflicts:
* #178 k10agent IBM Tivoli Monitoring (should already be in the yaml)
* #179 NFS Ports (should already be in the yaml)
* #180 ScaleIO ports

**Comment by captntuttle** [comment]
#178 and #179 are documented already, will add the others.
