### ISSUE TITLE
Work around sudo timeouts for long-running commands during bootstrap

### ISSUE THREAD

**Issue by padthaitofuhot** [EMCECS/ECS-CommunityEdition#249]
Some commands run for a long time.  When `sudo` is used to execute these long-running commands and successive commands, then it is possible for the `sudo` auth token to expire and re-prompt for the account password.  If the user does not notice this before the authentication attempt times out, the bootstrap script may continue on without executing an important step.  Problems caused by this can be resolved by re-running the bootstrap script.  However, to smooth things out and prevent what to the user may look like "mystery errors", `sudo` token reauthorizations should be placed into a retry loop.

**Comment by adrianmo** [comment]
@padthaitofuhot what if we force users to run the bootstrap script as root?

Something like this at the beginning of the script: 

```
if [ $EUID != 0 ]; then
    echo "Not running as root"
    exit
fi
...
```
