### ISSUE TITLE
The links to the documentation are broken

### ISSUE THREAD

**Issue by shanetreacy** [EMCECS/ECS-CommunityEdition#254]
This url http://dell-emc-ecs-community-edition.readthedocs.io/ gives a 404 ...

In the README.md obviously....

**Comment by padthaitofuhot** [comment]
@shanetreacy Thanks for reporting that.  That's quite the doc bug.  The real docs are here: http://ecsce.readthedocs.io/en/latest/?badge=latest

@captntuttle Please update RTD urls to point to http://ecsce.readthedocs.io/

**Comment by cblackuk** [comment]
The download links in the documentation are not working at all as well...

Everything on the page comes up with 
![image](https://cloud.githubusercontent.com/assets/28607803/26715416/924fe5f4-476d-11e7-962e-cf1a8eb2eced.png)

**Comment by padthaitofuhot** [comment]
@cblackuk Addressing your primary concerns, I merged a PR (#253) to clean up a bunch of docbugs.  That should clear up most, if not all, of the documentation issues you're seeing.  Thank you for reporting them.

Regarding the OVA links, the URLs are correct, but the objects in ECS Test Drive also needed an ACL update to permit public reads.  

Please let me know if there are any further issues you're running into.  Thanks!

**Comment by padthaitofuhot** [comment]
@shanetreacy and @cblackuk Please reopen this ticket if you are still finding critical documentation issues.  Thank you!
