### ISSUE TITLE
Step1 Error Single Node

### ISSUE THREAD

**Issue by amarcionek** [EMCECS/ECS-CommunityEdition#255]
Get the following error when running step1

`TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute ed25519 ssh key] **********
fatal: [192.168.50.2]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleFileNotFound'>, original message: the file_name '/opt/ssh/id_ed25519.pub' does not exist, or is not readable"}`

There is no /opt/ssh directory on the docker host.

This is a single node install on the same node as the install node. [Here is my deploy.xml](https://gist.github.com/amarcionek/5fc599d4374fccb37103b66c2203ff69) that I ran using ./bootstrap.sh -y -g -c deploy.xml  (SSH password omitted for obvious reasons.)  I cloned master just this morning. Ideas appreciated.

**Comment by padthaitofuhot** [comment]
How odd.  That `/opt/ssh` is relative to the `ecs-install` Docker container, not the host.  However, if the steps that generated the ed25519 key completed without error, then that file should exist.  

It would help if you could provide the output of these commands:
```
find /opt/emc
enter
find /opt
exit
```

Thanks!

**Comment by amarcionek** [comment]
[root@ecs ECS-CommunityEdition]# find /opt/emc

/opt/emc
/opt/emc/ecs-install
/opt/emc/ecs-install/ssl
/opt/emc/ecs-install/ssh
/opt/emc/ecs-install/deploy.yml
/opt/emc/ecs-install/state.yml
/opt/emc/ecs-install/cache
/opt/emc/ecs-install/cache/facts
/opt/emc/ecs-install/cache/facts/192.168.50.2

[root@ecs ECS-CommunityEdition]# find /opt
/opt
/opt/rh
/opt/emc
/opt/emc/ecs-install
/opt/emc/ecs-install/ssl
/opt/emc/ecs-install/ssh
/opt/emc/ecs-install/deploy.yml
/opt/emc/ecs-install/state.yml
/opt/emc/ecs-install/cache
/opt/emc/ecs-install/cache/facts
/opt/emc/ecs-install/cache/facts/192.168.50.2

Thanks for responding, hope this helps!

**Comment by padthaitofuhot** [comment]
It looks like you didn't run `enter` prior to running the second find.  Please run the following commands:

```
enter
find /opt
exit
```

Also, I'd like to see the output of `sudo docker ps -a`

Thanks!

**Comment by amarcionek** [comment]
ecs [/]$ find /opt
/opt
/opt/ssl
/opt/ssh
/opt/deploy.yml
/opt/state.yml
/opt/cache
/opt/cache/facts
/opt/cache/facts/192.168.50.2

[root@ecs ECS-CommunityEdition]# sudo docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                    PORTS               NAMES
14edcb51b352        emccorp/ecs-install:latest   "/bin/echo echo 'D..."   22 hours ago        Exited (0) 22 hours ago                       ecs-install-data

**Comment by amarcionek** [comment]
One thing I noticed when I run step1 is an error about file not found:  


[root@ecs bin]# ./step1
grep: ./step1: No such file or directory
PLAY [Common | Ping data nodes before doing anything else] *********************
TASK [ping] ********************************************************************
ok: [192.168.50.2]
PLAY [Installer | Gather facts and slice into OS groups] ***********************
TASK [group_by] ****************************************************************
ok: [192.168.50.2]
PLAY [CentOS 7 | Configure access] *********************************************
TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute ed25519 ssh key] **********
fatal: [192.168.50.2]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleFileNotFound'>, original message: the file_name '/opt/ssh/id_ed25519.pub' does not exist, or is not readable"}
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
192.168.50.2               : ok=2    changed=0    unreachable=0    failed=1
Playbook run took 0 days, 0 hours, 0 minutes, 1 seconds
Operation failed.

Probably should have mentioned that earlier. Am I running it from the correct directory. The files are put in ~/bin

**Comment by amarcionek** [comment]
if I 'cd' into the cloned source directory and run ~/bin/step1, the No Such file or directory error does not appear, but I still get the same problem:

[root@ecs ECS-CommunityEdition]# ~/bin/step1
PLAY [Common | Ping data nodes before doing anything else] *********************
TASK [ping] ********************************************************************
ok: [192.168.50.2]
PLAY [Installer | Gather facts and slice into OS groups] ***********************
TASK [group_by] ****************************************************************
ok: [192.168.50.2]
PLAY [CentOS 7 | Configure access] *********************************************
TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute ed25519 ssh key] **********
fatal: [192.168.50.2]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleFileNotFound'>, original message: the file_name '/opt/ssh/id_ed25519.pub' does not exist, or is not readable"}
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
192.168.50.2               : ok=2    changed=0    unreachable=0    failed=1
Playbook run took 0 days, 0 hours, 0 minutes, 3 seconds
Operation failed.

**Comment by padthaitofuhot** [comment]
Okay, I think I see what is happening.  

From the cloned source directory, which I will assume is `~/ECS-CommunityEdition`, please the share output of the following:

```
ui/update_image.sh --clean
step1
```

BTW - ~/bin is where the shell path shims are kept.  Those are just aliases to a shell script that handles the various CLI commands made available on the host.  You shouldn't need to be in that directory.

**Comment by amarcionek** [comment]
Hi @padthaitofuhot, 

I managed to get it working by a cloning into ~/ECS-CommunityEdition instead of ~/source/ECS-CommunityEdition. Given that was your assumption, figured I better try it! I guess that fixes my issue, so I'll close it. Still working through some others, but they are obvious why its not working (bad deploy values.)

Thanks for your help, Travis!

**Comment by Yeajimi** [comment]
Not to resurrect a dead thread, but I have a similar issue where Step1 fails, citing that my node is unreachable.  Upon inspection there is no folder present for /opt/ssh.  I attempted the steps above "ui/update_image.sh --clean" to no avail.


---------------------------------------------------------------
login as: root
root@10.0.7.77's password:
Last login: Fri Dec 14 16:41:52 2018
[root@ecs3 ~]# step1

PLAY [Common | Ping data nodes before doing anything else] *********************

TASK [ping] ********************************************************************
fatal: [10.0.7.77]: UNREACHABLE! => {"changed": false, "msg": "Authentication fa                                             ilure.", "unreachable": true}

PLAY RECAP *********************************************************************
10.0.7.77                  : ok=0    changed=0    unreachable=1    failed=0

Playbook run took 0 days, 0 hours, 0 minutes, 2 seconds
Operation failed.

[root@ecs3 ~]# find /opt/emc
/opt/emc
/opt/emc/ecs-install
/opt/emc/ecs-install/ssl
/opt/emc/ecs-install/ssh
/opt/emc/ecs-install/deploy.yml
/opt/emc/ecs-install/state.yml
[root@ecs3 ~]# find /opt
/opt
/opt/emc
/opt/emc/ecs-install
/opt/emc/ecs-install/ssl
/opt/emc/ecs-install/ssh
/opt/emc/ecs-install/deploy.yml
/opt/emc/ecs-install/state.yml
[root@ecs3 ~]#

**Comment by Yeajimi** [comment]
@padthaitofuhot should I create a new issue, or just piggy back on this one?  Wasn't able to re-open this closed issue though.

**Comment by California-CSE** [comment]
@Yeajimi 
Problem with [root@localhost ECS-CommunityEdition]# step1

If you need to make changes to your deploy.yml after bootstrapping, there are two utilities for this.
The **videploy** utility will update the installed deploy.yml file in place and is the preferred method. 

1. Check the license is accepted:true , possible failure is if the license accepted is **false**  it will not attempt a connection but the script continues and therefore returns a unable to ping node which can be misleading.  So use the videploy to recheck your configuration, wq! to save it which pushes the container updates.

2. Verify the username (default is admin so if you did not create an user admin during installation then use  ssh_username: root 

*** Stilling having problems try island mode
3. Run in island mode
[root@localhost ECS-CommunityEdition]# island-step1
...........................
[root@localhost ECS-CommunityEdition]# island-step2
............................
[root@localhost ECS-CommunityEdition]# island-step3

On screen messages with guide and show completion or Error in each of these steps.
Here is my completion of step3
[root@localhost ECS-CommunityEdition]# island-step3
> Pinging Management API Endpoint until ready
> Pinging endpoint 10.x.xx.xxx... (CTRL-C to break)
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: ECS API internal error. If ECS services are still bootstrapping, this is likely temporary.
> WAIT: ECS API internal error. If ECS services are still bootstrapping, this is likely temporary.
> WAIT: ECS API internal error. If ECS services are still bootstrapping, this is likely temporary.
> WAIT: ECS API internal error. If ECS services are still bootstrapping, this is likely temporary.
> WAIT: ECS API internal error. If ECS services are still bootstrapping, this is likely temporary.
> PONG: api_endpoint=10.x.xx.xxx username=root diag_endpoint=10.x.xx.xxx dt_total=0 dt_unready=0 dt_unknown=0

> Installing licensing in ECS VDC(s)
> Using default license
> Adding licensing to VDC: vdc1
>       OK
> Added default license to ECS

> Pinging Management API Endpoint until ready
> Pinging endpoint 10.x.xx.xxx... (CTRL-C to break)
> PONG: api_endpoint=10.x.xx.xxx username=root diag_endpoint=10.x.xx.xxx dt_total=0 dt_unready=0 dt_unknown=0

> Creating Storage Pool: vdc1/sp1
>       OK
> Adding Data Stores to Storage Pool:
>       vdc1/sp1/10.x.xx.xxx

> Pinging Management API Endpoint until ready
> Pinging endpoint 10.x.xx.xxx... (CTRL-C to break)
> PONG: api_endpoint=10.x.xx.xxx username=root diag_endpoint=10.x.xx.xxx dt_total=384 dt_unready=0 dt_unknown=0

> Creating all VDCs...
>       vdc1
> Created all VDCs

> Waiting for all VDCs to online and become active...
> Checking vdc1:
>       WAIT: VDC still onlining...
> Retrying...
> Checking vdc1:
>       OK: VDC online

> Pinging Management API Endpoint until ready
> Pinging endpoint 10.x.xx.xxx... (CTRL-C to break)
> PONG: api_endpoint=10.x.xx.xxx username=root diag_endpoint=10.x.xx.xxx dt_total=384 dt_unready=0 dt_unknown=0

> Creating replication group rg1
>       Generating zone mappings for rg1/vdc1
>       sp1
>       Applying mappings
>       OK
> Created all Replication Groups

> Pinging Management API Endpoint until ready
> Pinging endpoint 10.x.xx.xxx... (CTRL-C to break)
> PONG: api_endpoint=10.x.xx.xxx username=root diag_endpoint=10.x.xx.xxx dt_total=416 dt_unready=0 dt_unknown=-1

> Creating all configured management users:
>       admin1
>       monitor1
> Created all configured management users

> Pinging Management API Endpoint until ready
> Pinging endpoint 10.x.xx.xxx... (CTRL-C to break)
> PONG: api_endpoint=10.x.xx.xxx username=root diag_endpoint=10.x.xx.xxx dt_total=416 dt_unready=0 dt_unknown=0

> Creating all Namespaces
> Adding namespace ns1
>       OK
> Created all configured namespaces

> Pinging Management API Endpoint until ready
> Pinging endpoint 10.x.xx.xxx... (CTRL-C to break)
> PONG: api_endpoint=10.x.xx.xxx username=root diag_endpoint=10.x.xx.xxx dt_total=416 dt_unready=0 dt_unknown=0

> Creating all configured object users:
> Creating all object users
> Creating 'object_admin1' in namespace 'ns1'
>       Waiting for 'object_admin1' to become editable
>       OK
>       Adding object_admin1's S3 credentials
>       Adding object_admin1's S3 credentials
>       Adding object_admin1's S3 credentials
>       Adding object_admin1's S3 credentials
>       Adding object_admin1's S3 credentials
>       Adding object_admin1's S3 credentials
>       Adding object_admin1's S3 credentials
>       Adding object_admin1's S3 credentials
>       Adding object_admin1's Swift credentials
> Creating 'object_user1' in namespace 'ns1'
>       Waiting for 'object_user1' to become editable
>       OK
>       Adding object_user1's S3 credentials
>       Adding object_user1's Swift credentials
> Created all configured object users

> Pinging Management API Endpoint until ready
> Pinging endpoint 10.x.xx.xxx... (CTRL-C to break)
> PONG: api_endpoint=10.x.xx.xxx username=root diag_endpoint=10.x.xx.xxx dt_total=416 dt_unready=0 dt_unknown=0

> Creating all buckets
> Creating bucket: bucket1
>       OK
> Created all configured buckets

4. At this point open your web browser and enter your end point

**Comment by Yeajimi** [comment]
@California-CSE Hey, thanks for the help.  I updated the SSH account to use 'root' which got me through that step, but when I run step1, I encounter the following error.

```
[root@ecs3 ECS-CommunityEdition]# step1

PLAY [Common | Ping data nodes before doing anything else] **********************************************************************************************************************************************************************************

TASK [ping] *********************************************************************************************************************************************************************************************************************************
ok: [10.0.7.77]

PLAY [Installer | Gather facts and slice into OS groups] ************************************************************************************************************************************************************************************

TASK [group_by] *****************************************************************************************************************************************************************************************************************************
ok: [10.0.7.77]

PLAY [CentOS 7 | Configure access] **********************************************************************************************************************************************************************************************************

TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute ed25519 ssh key] ***********************************************************************************************************************************************************************

TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute rsa ssh key] ***************************************************************************************************************************************************************************
ok: [10.0.7.77]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable SSH UseDNS] *******************************************************************************************************************************************************************************
ok: [10.0.7.77]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable requiretty] *******************************************************************************************************************************************************************************
ok: [10.0.7.77]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable sudo password reverification for admin group] *********************************************************************************************************************************************
ok: [10.0.7.77]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable sudo password reverification for wheel group] *********************************************************************************************************************************************
ok: [10.0.7.77]

TASK [firewalld_configure_access : Firewalld | Ensure service is started] *******************************************************************************************************************************************************************
ok: [10.0.7.77]

TASK [firewalld_configure_access : Firewalld | Add install node to firewalld trusted zone] **************************************************************************************************************************************************
changed: [10.0.7.77]

TASK [firewalld_configure_access : Firewalld | Add all data nodes to firewalld trusted zone] ************************************************************************************************************************************************
ok: [10.0.7.77] => (item=10.0.7.77)
changed: [10.0.7.77] => (item=172.17.0.1)

TASK [firewalld_configure_access : Firewalld | Whitelist management prefixes] ***************************************************************************************************************************************************************
changed: [10.0.7.77] => (item=0.0.0.0/0)

TASK [firewalld_configure_access : Firewalld | Add all public service ports to firewalld public zone] ***************************************************************************************************************************************
changed: [10.0.7.77] => (item=3218/tcp)
changed: [10.0.7.77] => (item=9020-9025/tcp)
changed: [10.0.7.77] => (item=9040/tcp)

TASK [firewalld_configure_access : Firewalld | Ensure service is started] *******************************************************************************************************************************************************************
changed: [10.0.7.77]

PLAY [Common | Configure hostnames] *********************************************************************************************************************************************************************************************************

TASK [common_set_hostname : include_vars] ***************************************************************************************************************************************************************************************************
ok: [10.0.7.77]

TASK [common_set_hostname : Common | Find node hostname] ************************************************************************************************************************************************************************************
ok: [10.0.7.77] => (item=(0, u'10.0.7.77'))

TASK [common_set_hostname : Common | Set node hostname] *************************************************************************************************************************************************************************************
changed: [10.0.7.77]

PLAY [Common | Configure /etc/hosts] ********************************************************************************************************************************************************************************************************

TASK [common_etc_hosts : Common | Add install node to /etc/hosts] ***************************************************************************************************************************************************************************
changed: [10.0.7.77] => (item=10.0.7.77)

TASK [common_etc_hosts : Common | Add data nodes to /etc/hosts] *****************************************************************************************************************************************************************************
ok: [10.0.7.77] => (item=10.0.7.77)

PLAY [Common | Test inter-node access] ******************************************************************************************************************************************************************************************************

TASK [common_access_test : Common | Check node connectivity by IP] **************************************************************************************************************************************************************************
ok: [10.0.7.77] => (item=10.0.7.77)
ok: [10.0.7.77] => (item=172.17.0.1)

TASK [common_access_test : Common | Check node connectivity by short name] ******************************************************************************************************************************************************************
ok: [10.0.7.77] => (item=luna)

TASK [common_access_test : Common | Check node connectivity by fqdn] ************************************************************************************************************************************************************************
ok: [10.0.7.77] => (item=luna)

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
10.0.7.77                  : ok=21   changed=7    unreachable=0    failed=0

Playbook run took 0 days, 0 hours, 0 minutes, 19 seconds


PLAY [Common | Ping data nodes before doing anything else] **********************************************************************************************************************************************************************************

TASK [ping] *********************************************************************************************************************************************************************************************************************************
ok: [10.0.7.77]

PLAY [Installer | Slice nodes into OS groups] ***********************************************************************************************************************************************************************************************

TASK [group_by] *****************************************************************************************************************************************************************************************************************************
ok: [10.0.7.77]

PLAY [Installer | Perform preflight check] **************************************************************************************************************************************************************************************************

TASK [common_collect_facts : Common | Create custom facts directory] ************************************************************************************************************************************************************************
changed: [10.0.7.77]

TASK [common_collect_facts : Common | Insert data_node.fact file] ***************************************************************************************************************************************************************************
changed: [10.0.7.77]

TASK [common_collect_facts : Common | Reload facts to pick up new items] ********************************************************************************************************************************************************************
ok: [10.0.7.77]

TASK [common_baseline_check : include_vars] *************************************************************************************************************************************************************************************************
ok: [10.0.7.77]

TASK [common_baseline_check : Common | Check RAM size] **************************************************************************************************************************************************************************************

TASK [common_baseline_check : Common | Check CPU architecture] ******************************************************************************************************************************************************************************

TASK [common_baseline_check : Common | Validate OS distribution] ****************************************************************************************************************************************************************************

TASK [common_baseline_check : Common | (Optional) Check UTC Timezone] ***********************************************************************************************************************************************************************
ok: [10.0.7.77] => {
    "msg": "Timezone is not set to UTC - It is recommended to use the UTC timezone"
}

TASK [common_baseline_check : Common | Make sure /data directory does not exist] ************************************************************************************************************************************************************
ok: [10.0.7.77]

TASK [common_baseline_check : fail] *********************************************************************************************************************************************************************************************************

TASK [common_baseline_check : Common | Make sure /host directory does not exist] ************************************************************************************************************************************************************
ok: [10.0.7.77]

TASK [common_baseline_check : fail] *********************************************************************************************************************************************************************************************************

TASK [common_baseline_check : Common | Make sure block device(s) exist on node] *************************************************************************************************************************************************************
ok: [10.0.7.77] => (item=/dev/vda)

TASK [common_baseline_check : fail] *********************************************************************************************************************************************************************************************************
failed: [10.0.7.77] (item={'_ansible_parsed': True, u'stat': {u'exists': False}, '_ansible_item_result': True, '_ansible_no_log': False, 'failed': False, u'changed': False, 'item': u'/dev/vda', u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'/dev/vda', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}}) => {"changed": false, "failed": true, "item": {"changed": false, "failed": false, "invocation": {"module_args": {"checksum_algorithm": "sha1", "follow": false, "get_attributes": true, "get_checksum": true, "get_md5": true, "get_mime": true, "path": "/dev/vda"}}, "item": "/dev/vda", "stat": {"exists": false}}, "msg": "A block device configured in deploy.yml does not exist on the node."}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
10.0.7.77                  : ok=10   changed=2    unreachable=0    failed=1

Playbook run took 0 days, 0 hours, 0 minutes, 7 seconds
Operation failed.
```

**Comment by California-CSE** [comment]
TASK [common_baseline_check : Common | Make sure block device(s) exist on node] *************************************************************************************************************************************************************
ok: [10.0.7.77] => (item=/dev/vda)  


1. Recommand to #sudo fdisk /dev/vda
2. Recheck the deploy.yml file
3. Is this a VM or physical server? --
 - if this is a VM did you add a second virtual disk to 104 GB Minimum additional block storage device in a raw, unpartitioned state and if so confirm the partition

**   /dev/vda ? ** I believe this may be your boot disk rather than your block storage needed.

**Comment by tadada** [comment]
> TASK [common_baseline_check : Common | Make sure block device(s) exist on node] *************************************************************************************************************************************************************
> ok: [10.0.7.77] => (item=/dev/vda)
> 
> 1. Recommand to #sudo fdisk /dev/vda
> 2. Recheck the deploy.yml file
> 3. Is this a VM or physical server? --
> 
> * if this is a VM did you add a second virtual disk to 104 GB Minimum additional block storage device in a raw, unpartitioned state and if so confirm the partition
> 
> ** /dev/vda ? ** I believe this may be your boot disk rather than your block storage needed.

How to create a unpartitioned dist, thanks
