### ISSUE TITLE
High CPU for hours memory exhaustion problems

### ISSUE THREAD

**Issue by VMMan** [EMCECS/ECS-CommunityEdition#26]
Hi Team,
Struggling to get ECS single node docker deployment stable. I can get it running, but have constant high CPU and very slow / hours to gain connectivity to management gui.

Running Centos 7.1 on vSphere 5.5. 4vcpu and 20GB RAM. Have an older penryn proc, so nothing fast. 512GB data disk (vmdk) from FC SAN- attached VMware Datastore. I've applied the sysctl to help with memory, but no luck. 

After running step1, cpu stays very high, all memory gets gobbled up and then starts to burn the swap as well. Is there something I could be doing wrong here, or does this just need more power/ram? ssm.log shows chunk corruption and DT not initialized errors.

**Comment by jasoncwik** [comment]
Hi there,

We need to update the documentation on the single-node installation page.  The minimum memory footprint for the single-node image on the current version (2.0.1) is about 50GB (64GB recommended).  At the end of September when we update to 2.1.0 we should have a workable 16GB configuration (maybe less).  Sorry for the confusion.

**Comment by VMMan** [comment]
Jason, thanks for the quick response.  I'm really looking forward to a future version that will play nice with limited RAM resources.  This will be fantastic for training and demo purposes. 

Dave

**Comment by jasoncwik** [comment]
Confirmed that the latest version (2.1.0.2) works on single-node with 16GB RAM.
