### ISSUE TITLE
storage capacity always decreasing

### ISSUE THREAD

**Issue by ambitslix** [EMCECS/ECS-CommunityEdition#266]
My setup is single-node stock install process inside CentOS 7.3 VM with 16GB RAM and 200GB disk.

It seems that the Online Available Capacity keeps decreasing as more objects are put into the storage, and it does NOT increase after deleting all buckets and objects?

When I look at the Capacity Utilization I can see the same amount of available storage after deleting all buckets. In addition when I finally run out of space the server returns HTTP 507:

"The server cannot process the request because there is not enough space on disk"

However there isn't a single object there according to an S3 request list all. The only way I was able to fix this is by a complete re-install. 

Am I missing something?

**Comment by padthaitofuhot** [comment]
Hi @ambitslix.  Thank you for your question.  The main issue with ECS Community Edition deployments is that it's such a small form factor when compared to ECS appliance deployments.  ECS is typically deployed in hundreds of TB to 10s of PB.  ECS assumes a relatively very large storage capacity.  The garbage collection system for ECS is meant to be performant and unintrusive, so it is extremely unaggressive.  It may take more than 72 hours for the space taken up by deleted objects to be reclaimed.  You can test this for yourself by exhausting space on an ECS, removing all objects, and monitoring the time required to zero out the object storage.

**Comment by ambitslix** [comment]
Thank you!

That explains it all, I will monitor the activity.

**Comment by padthaitofuhot** [comment]
Excellent.  Happy I could help shed some light on what you were seeing.  Let me know if we can help with anything else.
