### ISSUE TITLE
Current Island Deploy .OVA for Non-Internet Access Site Fails During STEP1

### ISSUE THREAD

**Issue by OohDark30** [EMCECS/ECS-CommunityEdition#283]
Running step1 on current island .OVA Fails with the following error:

TASK [common_sync_caches_by_torrent : Common | Copy cache torrent digest to nodes] ***
changed: [136.251.129.120]
changed: [136.251.129.119]
changed: [136.251.129.121]

TASK [common_sync_caches_by_torrent : Common | Torrent sync caches with nodes] *
fatal: [136.251.129.119]: FAILED! => {"changed": true, "cmd": "aria2c --file-allocation=trunc -T /var/cache/emc/ecs-install/cache.torrent --bt-tracker-connect-timeout=1 --bt-tracker-interval=1 --bt-tracker-timeout=2 --listen-port=6883-6999 --enable-dht=true --dht-entry-point=136.251.129.80:6882 --dht-message-timeout=2 --dht-listen-port=6882 --seed-time=0 --allow-overwrite=true --check-integrity --bt-enable-lpd=false && touch /var/cache/emc/ecs-install/cache_control.sem", "delta": "0:00:00.003883", "end": "2017-06-19 16:40:48.675710", "failed": true, "rc": 127, "start": "2017-06-19 16:40:48.671827", "stderr": "/bin/sh: aria2c: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
fatal: [136.251.129.120]: FAILED! => {"changed": true, "cmd": "aria2c --file-allocation=trunc -T /var/cache/emc/ecs-install/cache.torrent --bt-tracker-connect-timeout=1 --bt-tracker-interval=1 --bt-tracker-timeout=2 --listen-port=6883-6999 --enable-dht=true --dht-entry-point=136.251.129.80:6882 --dht-message-timeout=2 --dht-listen-port=6882 --seed-time=0 --allow-overwrite=true --check-integrity --bt-enable-lpd=false && touch /var/cache/emc/ecs-install/cache_control.sem", "delta": "0:00:00.004169", "end": "2017-06-19 16:40:48.685524", "failed": true, "rc": 127, "start": "2017-06-19 16:40:48.681355", "stderr": "/bin/sh: aria2c: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
fatal: [136.251.129.121]: FAILED! => {"changed": true, "cmd": "aria2c --file-allocation=trunc -T /var/cache/emc/ecs-install/cache.torrent --bt-tracker-connect-timeout=1 --bt-tracker-interval=1 --bt-tracker-timeout=2 --listen-port=6883-6999 --enable-dht=true --dht-entry-point=136.251.129.80:6882 --dht-message-timeout=2 --dht-listen-port=6882 --seed-time=0 --allow-overwrite=true --check-integrity --bt-enable-lpd=false && touch /var/cache/emc/ecs-install/cache_control.sem", "delta": "0:00:00.003810", "end": "2017-06-19 16:40:48.690044", "failed": true, "rc": 127, "start": "2017-06-19 16:40:48.686234", "stderr": "/bin/sh: aria2c: command not found", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
136.251.129.119            : ok=8    changed=5    unreachable=0    failed=1   
136.251.129.120            : ok=8    changed=5    unreachable=0    failed=1   
136.251.129.121            : ok=8    changed=5    unreachable=0    failed=1   

Playbook run took 0 days, 0 hours, 0 minutes, 3 seconds
Operation failed.

Full log below:

[admin@localhost ECS-CommunityEdition]$ step1

PLAY [Common | Ping data nodes before doing anything else] *********************

TASK [ping] ********************************************************************
ok: [136.251.129.121]
ok: [136.251.129.80]
ok: [136.251.129.119]
ok: [136.251.129.120]

PLAY [Installer | Gather facts and slice into OS groups] ***********************

TASK [group_by] ****************************************************************
ok: [136.251.129.119]
ok: [136.251.129.121]
ok: [136.251.129.120]
ok: [136.251.129.80]

PLAY [CentOS 7 | Configure access] *********************************************

TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute ed25519 ssh key] **********
changed: [136.251.129.121]
changed: [136.251.129.119]
ok: [136.251.129.80]
changed: [136.251.129.120]

TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute rsa ssh key] **************
changed: [136.251.129.119]
changed: [136.251.129.121]
ok: [136.251.129.80]
changed: [136.251.129.120]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable SSH UseDNS] ******************
ok: [136.251.129.80]
changed: [136.251.129.121]
changed: [136.251.129.119]
changed: [136.251.129.120]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable requiretty] ******************
ok: [136.251.129.80]
ok: [136.251.129.119]
ok: [136.251.129.121]
ok: [136.251.129.120]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable sudo password reverification for admin group] ***
ok: [136.251.129.80]
changed: [136.251.129.119]
changed: [136.251.129.121]
changed: [136.251.129.120]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable sudo password reverification for wheel group] ***
changed: [136.251.129.121]
ok: [136.251.129.80]
changed: [136.251.129.119]
changed: [136.251.129.120]

TASK [firewalld_configure_access : Firewalld | Ensure service is started] ******
ok: [136.251.129.80]
ok: [136.251.129.121]
ok: [136.251.129.119]
ok: [136.251.129.120]

TASK [firewalld_configure_access : Firewalld | Add install node to firewalld trusted zone] ***
ok: [136.251.129.80]
changed: [136.251.129.121]
changed: [136.251.129.119]
changed: [136.251.129.120]

TASK [firewalld_configure_access : Firewalld | Add all data nodes to firewalld trusted zone] ***
ok: [136.251.129.80] => (item=136.251.129.119)
changed: [136.251.129.121] => (item=136.251.129.119)
changed: [136.251.129.119] => (item=136.251.129.119)
changed: [136.251.129.120] => (item=136.251.129.119)
ok: [136.251.129.80] => (item=136.251.129.120)
changed: [136.251.129.120] => (item=136.251.129.120)
changed: [136.251.129.121] => (item=136.251.129.120)
changed: [136.251.129.119] => (item=136.251.129.120)
ok: [136.251.129.80] => (item=136.251.129.121)
changed: [136.251.129.120] => (item=136.251.129.121)
changed: [136.251.129.119] => (item=136.251.129.121)
changed: [136.251.129.121] => (item=136.251.129.121)

TASK [firewalld_configure_access : Firewalld | Whitelist management prefixes] **
changed: [136.251.129.121] => (item=0.0.0.0/0)
changed: [136.251.129.120] => (item=0.0.0.0/0)
ok: [136.251.129.80] => (item=0.0.0.0/0)
changed: [136.251.129.119] => (item=0.0.0.0/0)

TASK [firewalld_configure_access : Firewalld | Add all public service ports to firewalld public zone] ***
ok: [136.251.129.80] => (item=3218/tcp)
changed: [136.251.129.121] => (item=3218/tcp)
changed: [136.251.129.119] => (item=3218/tcp)
changed: [136.251.129.120] => (item=3218/tcp)
ok: [136.251.129.80] => (item=9020-9025/tcp)
changed: [136.251.129.121] => (item=9020-9025/tcp)
changed: [136.251.129.119] => (item=9020-9025/tcp)
changed: [136.251.129.120] => (item=9020-9025/tcp)
ok: [136.251.129.80] => (item=9040/tcp)
changed: [136.251.129.121] => (item=9040/tcp)
changed: [136.251.129.119] => (item=9040/tcp)
changed: [136.251.129.120] => (item=9040/tcp)

TASK [firewalld_configure_access : Firewalld | Ensure service is started] ******
changed: [136.251.129.121]
changed: [136.251.129.119]
changed: [136.251.129.120]
changed: [136.251.129.80]

RUNNING HANDLER [CentOS_7_configure_ssh : CentOS 7 | Restart sshd] *************
changed: [136.251.129.119]
changed: [136.251.129.120]
changed: [136.251.129.121]

PLAY [Common | Configure hostnames] ********************************************

TASK [common_set_hostname : include_vars] **************************************
ok: [136.251.129.119]
ok: [136.251.129.121]
ok: [136.251.129.120]

TASK [common_set_hostname : Common | Find node hostname] ***********************
ok: [136.251.129.119] => (item=(0, u'136.251.129.119'))
ok: [136.251.129.120] => (item=(1, u'136.251.129.120'))
ok: [136.251.129.121] => (item=(2, u'136.251.129.121'))

TASK [common_set_hostname : Common | Set node hostname] ************************
changed: [136.251.129.120]
changed: [136.251.129.119]
changed: [136.251.129.121]

PLAY [Common | Configure /etc/hosts] *******************************************

TASK [common_etc_hosts : Common | Add install node to /etc/hosts] **************
ok: [136.251.129.80] => (item=136.251.129.80)
changed: [136.251.129.119] => (item=136.251.129.80)
changed: [136.251.129.120] => (item=136.251.129.80)
changed: [136.251.129.121] => (item=136.251.129.80)

TASK [common_etc_hosts : Common | Add data nodes to /etc/hosts] ****************
ok: [136.251.129.80] => (item=136.251.129.119)
changed: [136.251.129.119] => (item=136.251.129.119)
changed: [136.251.129.120] => (item=136.251.129.119)
changed: [136.251.129.121] => (item=136.251.129.119)
ok: [136.251.129.80] => (item=136.251.129.120)
changed: [136.251.129.121] => (item=136.251.129.120)
changed: [136.251.129.119] => (item=136.251.129.120)
changed: [136.251.129.120] => (item=136.251.129.120)
ok: [136.251.129.80] => (item=136.251.129.121)
changed: [136.251.129.121] => (item=136.251.129.121)
changed: [136.251.129.119] => (item=136.251.129.121)
changed: [136.251.129.120] => (item=136.251.129.121)

PLAY [Common | Test inter-node access] *****************************************

TASK [common_access_test : Common | Check node connectivity by IP] *************
ok: [136.251.129.121] => (item=136.251.129.119)
ok: [136.251.129.80] => (item=136.251.129.119)
ok: [136.251.129.119] => (item=136.251.129.119)
ok: [136.251.129.120] => (item=136.251.129.119)
ok: [136.251.129.119] => (item=136.251.129.120)
ok: [136.251.129.121] => (item=136.251.129.120)
ok: [136.251.129.80] => (item=136.251.129.120)
ok: [136.251.129.120] => (item=136.251.129.120)
ok: [136.251.129.119] => (item=136.251.129.121)
ok: [136.251.129.121] => (item=136.251.129.121)
ok: [136.251.129.80] => (item=136.251.129.121)
ok: [136.251.129.120] => (item=136.251.129.121)

TASK [common_access_test : Common | Check node connectivity by short name] *****
ok: [136.251.129.119] => (item=luna)
ok: [136.251.129.120] => (item=luna)
ok: [136.251.129.121] => (item=luna)
ok: [136.251.129.80] => (item=luna)
ok: [136.251.129.80] => (item=phobos)
ok: [136.251.129.120] => (item=phobos)
ok: [136.251.129.121] => (item=phobos)
ok: [136.251.129.119] => (item=phobos)
ok: [136.251.129.80] => (item=deimos)
ok: [136.251.129.119] => (item=deimos)
ok: [136.251.129.121] => (item=deimos)
ok: [136.251.129.120] => (item=deimos)

TASK [common_access_test : Common | Check node connectivity by fqdn] ***********
ok: [136.251.129.121] => (item=luna)
ok: [136.251.129.119] => (item=luna)
ok: [136.251.129.120] => (item=luna)
ok: [136.251.129.80] => (item=luna)
ok: [136.251.129.119] => (item=phobos)
ok: [136.251.129.121] => (item=phobos)
ok: [136.251.129.80] => (item=phobos)
ok: [136.251.129.120] => (item=phobos)
ok: [136.251.129.119] => (item=deimos)
ok: [136.251.129.121] => (item=deimos)
ok: [136.251.129.80] => (item=deimos)
ok: [136.251.129.120] => (item=deimos)

PLAY RECAP *********************************************************************
136.251.129.119            : ok=23   changed=14   unreachable=0    failed=0   
136.251.129.120            : ok=23   changed=14   unreachable=0    failed=0   
136.251.129.121            : ok=23   changed=14   unreachable=0    failed=0   
136.251.129.80             : ok=19   changed=1    unreachable=0    failed=0   

Playbook run took 0 days, 0 hours, 0 minutes, 13 seconds

PLAY [Common | Ping data nodes before doing anything else] *********************

TASK [ping] ********************************************************************
ok: [136.251.129.119]
ok: [136.251.129.121]
ok: [136.251.129.120]

PLAY [Installer | Slice nodes into OS groups] **********************************

TASK [group_by] ****************************************************************
ok: [136.251.129.119]
ok: [136.251.129.120]
ok: [136.251.129.121]

PLAY [Installer | Perform preflight check] *************************************

TASK [common_collect_facts : Common | Create custom facts directory] ***********
ok: [136.251.129.119]
ok: [136.251.129.121]
ok: [136.251.129.120]

TASK [common_collect_facts : Common | Insert data_node.fact file] **************
ok: [136.251.129.119]
ok: [136.251.129.121]
ok: [136.251.129.120]

TASK [common_collect_facts : Common | Reload facts to pick up new items] *******
ok: [136.251.129.121]
ok: [136.251.129.119]
ok: [136.251.129.120]

TASK [common_baseline_check : include_vars] ************************************
ok: [136.251.129.119]
ok: [136.251.129.120]
ok: [136.251.129.121]

TASK [common_baseline_check : Common | Check RAM size] *************************

TASK [common_baseline_check : Common | Check CPU architecture] *****************

TASK [common_baseline_check : Common | Validate OS distribution] ***************

TASK [common_baseline_check : Common | (Optional) Check UTC Timezone] **********
ok: [136.251.129.119] => {
    "msg": "Timezone is not set to UTC - It is recommended to use the UTC timezone"
}
ok: [136.251.129.120] => {
    "msg": "Timezone is not set to UTC - It is recommended to use the UTC timezone"
}
ok: [136.251.129.121] => {
    "msg": "Timezone is not set to UTC - It is recommended to use the UTC timezone"
}

TASK [common_baseline_check : Common | Make sure /data directory does not exist] ***
ok: [136.251.129.119]
ok: [136.251.129.121]
ok: [136.251.129.120]

TASK [common_baseline_check : fail] ********************************************

TASK [common_baseline_check : Common | Make sure /host directory does not exist] ***
ok: [136.251.129.119]
ok: [136.251.129.121]
ok: [136.251.129.120]

TASK [common_baseline_check : fail] ********************************************

TASK [common_baseline_check : Common | Make sure block device(s) exist on node] 
ok: [136.251.129.119] => (item=/dev/sdb)
ok: [136.251.129.121] => (item=/dev/sdb)
ok: [136.251.129.120] => (item=/dev/sdb)

TASK [common_baseline_check : fail] ********************************************

TASK [common_baseline_check : Common | Make sure block device(s) are at least 100GB] ***

TASK [common_baseline_check : Common | Make sure block device(s) are unpartitioned] ***
ok: [136.251.129.119] => (item=/dev/sdb)
ok: [136.251.129.121] => (item=/dev/sdb)
ok: [136.251.129.120] => (item=/dev/sdb)

TASK [common_baseline_check : fail] ********************************************

TASK [common_baseline_check : Common | Check for listening layer 4 ports] ******
changed: [136.251.129.119]
changed: [136.251.129.121]
changed: [136.251.129.120]

TASK [common_baseline_check : Common | Report any conflicts with published ECS ports] ***

TASK [common_baseline_check : Common | Report any conflicts with internal ECS ports] ***

PLAY RECAP *********************************************************************
136.251.129.119            : ok=12   changed=1    unreachable=0    failed=0   
136.251.129.120            : ok=12   changed=1    unreachable=0    failed=0   
136.251.129.121            : ok=12   changed=1    unreachable=0    failed=0   

Playbook run took 0 days, 0 hours, 0 minutes, 11 seconds

PLAY [Installer | Setup access between ecs-install and install node] ***********

TASK [group_by] ****************************************************************
ok: [136.251.129.80]

PLAY [Installer | Create SSH keys] *********************************************

TASK [installer_generate_ssh_keys : include_vars] ******************************
ok: [localhost]

TASK [installer_generate_ssh_keys : Installer | Check RSA Keypair] *************
ok: [localhost]

TASK [installer_generate_ssh_keys : Installer | Generate RSA Keypair] **********

TASK [installer_generate_ssh_keys : Installer | Check ed25519 Keypair] *********
ok: [localhost]

TASK [installer_generate_ssh_keys : Installer | Generate ed25519 Keypair] ******

TASK [installer_generate_ssh_keys : Installer | Ensure directory permissions on ssh keystore] ***
ok: [localhost] => (item={'value': {u'owner': u'root', u'state': u'file', u'group': u'root', u'mode': 600}, 'key': u'/opt/ssh/id_ed25519'})
ok: [localhost] => (item={'value': {u'owner': u'root', u'state': u'file', u'group': u'root', u'mode': 600}, 'key': u'/opt/ssh/id_rsa'})
ok: [localhost] => (item={'value': {u'owner': u'root', u'state': u'directory', u'group': u'root', u'mode': 700}, 'key': u'/opt/ssh'})

PLAY [CentOS 7 | Setup SSH on install node] ************************************

TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute ed25519 ssh key] **********
ok: [136.251.129.80]

TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute rsa ssh key] **************
ok: [136.251.129.80]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable SSH UseDNS] ******************
ok: [136.251.129.80]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable requiretty] ******************
ok: [136.251.129.80]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable sudo password reverification for admin group] ***
ok: [136.251.129.80]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable sudo password reverification for wheel group] ***
ok: [136.251.129.80]

PLAY RECAP *********************************************************************
136.251.129.80             : ok=7    changed=0    unreachable=0    failed=0   
localhost                  : ok=4    changed=0    unreachable=0    failed=0   

Playbook run took 0 days, 0 hours, 0 minutes, 2 seconds

PLAY [Installer | Build the package cache] *************************************

TASK [installer_build_cache : include_vars] ************************************
ok: [localhost]

TASK [installer_build_cache : Installer | Create cache directories] ************
changed: [localhost] => (item=os_CentOS_7)
changed: [localhost] => (item=docker)

TASK [installer_build_cache : Installer | Create compressed cache files] *******
changed: [localhost -> 136.251.129.80] => (item={'value': {u'src': u'/var/cache/yum', u'dest': u'package_cache.tgz', u'pack_cmd': u'tar -c /var/cache/yum | pigz -c5 > package_cache.tgz', u'unpack_sem': u'cache_control.sem', u'applies_to': u'os_CentOS_7', u'unpack_cmd': u'tar -xzf package_cache.tgz'}, 'key': u'os_CentOS_7'})
changed: [localhost -> 136.251.129.80] => (item={'value': {u'src': u'emccorp/ecs-software:latest', u'dest': u'ecs-software.tgz', u'pack_cmd': u'docker save emccorp/ecs-software:latest | pigz -c5 > ecs-software.tgz', u'unpack_sem': u'cache_control.sem', u'applies_to': u'data_node', u'unpack_cmd': u'pigz -dc ecs-software.tgz | docker load'}, 'key': u'docker'})

TASK [installer_build_cache : Installer | Create cache distribution torrent file] ***
changed: [localhost]

PLAY [Installer | Enable torrent ffx] ******************************************

TASK [file] ********************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=4    unreachable=0    failed=0   

Playbook run took 0 days, 0 hours, 0 minutes, 54 seconds
ecs-install> Init bittorrent ffx .. OK

PLAY [Common | Ping data nodes before doing anything else] *********************

TASK [ping] ********************************************************************
ok: [136.251.129.121]
ok: [136.251.129.119]
ok: [136.251.129.120]

PLAY [Installer | Slice nodes into OS groups for package install] **************

TASK [group_by] ****************************************************************
ok: [136.251.129.119]
ok: [136.251.129.120]
ok: [136.251.129.121]

PLAY [CentOS 7 | Synchronize cache] ********************************************

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Fetch torrent package names] ******
changed: [136.251.129.121 -> 136.251.129.80]
changed: [136.251.129.119 -> 136.251.129.80]
changed: [136.251.129.120 -> 136.251.129.80]

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Make yum cache paths for torrent packages] ***

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Copy torrent packages to nodes] ***

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Install torrent packages on nodes] 

TASK [common_sync_caches_by_torrent : include_vars] ****************************
ok: [136.251.129.119]
ok: [136.251.129.120]
ok: [136.251.129.121]

TASK [common_sync_caches_by_torrent : Selinux | Set selinux permissive] ********
changed: [136.251.129.119]
changed: [136.251.129.121]
changed: [136.251.129.120]

TASK [common_sync_caches_by_torrent : Common | Create ecs-install host directory on nodes] ***
changed: [136.251.129.121]
changed: [136.251.129.119]
changed: [136.251.129.120]

TASK [common_sync_caches_by_torrent : Common | Create ecs-install cache directory on nodes] ***
changed: [136.251.129.119]
changed: [136.251.129.120]
changed: [136.251.129.121]

TASK [common_sync_caches_by_torrent : Common | Copy cache torrent digest to nodes] ***
changed: [136.251.129.120]
changed: [136.251.129.119]
changed: [136.251.129.121]

TASK [common_sync_caches_by_torrent : Common | Torrent sync caches with nodes] *
fatal: [136.251.129.119]: FAILED! => {"changed": true, "cmd": "aria2c --file-allocation=trunc -T /var/cache/emc/ecs-install/cache.torrent --bt-tracker-connect-timeout=1 --bt-tracker-interval=1 --bt-tracker-timeout=2 --listen-port=6883-6999 --enable-dht=true --dht-entry-point=136.251.129.80:6882 --dht-message-timeout=2 --dht-listen-port=6882 --seed-time=0 --allow-overwrite=true --check-integrity --bt-enable-lpd=false && touch /var/cache/emc/ecs-install/cache_control.sem", "delta": "0:00:00.003883", "end": "2017-06-19 16:40:48.675710", "failed": true, "rc": 127, "start": "2017-06-19 16:40:48.671827", "stderr": "/bin/sh: aria2c: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
fatal: [136.251.129.120]: FAILED! => {"changed": true, "cmd": "aria2c --file-allocation=trunc -T /var/cache/emc/ecs-install/cache.torrent --bt-tracker-connect-timeout=1 --bt-tracker-interval=1 --bt-tracker-timeout=2 --listen-port=6883-6999 --enable-dht=true --dht-entry-point=136.251.129.80:6882 --dht-message-timeout=2 --dht-listen-port=6882 --seed-time=0 --allow-overwrite=true --check-integrity --bt-enable-lpd=false && touch /var/cache/emc/ecs-install/cache_control.sem", "delta": "0:00:00.004169", "end": "2017-06-19 16:40:48.685524", "failed": true, "rc": 127, "start": "2017-06-19 16:40:48.681355", "stderr": "/bin/sh: aria2c: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
fatal: [136.251.129.121]: FAILED! => {"changed": true, "cmd": "aria2c --file-allocation=trunc -T /var/cache/emc/ecs-install/cache.torrent --bt-tracker-connect-timeout=1 --bt-tracker-interval=1 --bt-tracker-timeout=2 --listen-port=6883-6999 --enable-dht=true --dht-entry-point=136.251.129.80:6882 --dht-message-timeout=2 --dht-listen-port=6882 --seed-time=0 --allow-overwrite=true --check-integrity --bt-enable-lpd=false && touch /var/cache/emc/ecs-install/cache_control.sem", "delta": "0:00:00.003810", "end": "2017-06-19 16:40:48.690044", "failed": true, "rc": 127, "start": "2017-06-19 16:40:48.686234", "stderr": "/bin/sh: aria2c: command not found", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
136.251.129.119            : ok=8    changed=5    unreachable=0    failed=1   
136.251.129.120            : ok=8    changed=5    unreachable=0    failed=1   
136.251.129.121            : ok=8    changed=5    unreachable=0    failed=1   

Playbook run took 0 days, 0 hours, 0 minutes, 3 seconds
Operation failed.
[admin@localhost ECS-CommunityEdition]$

**Comment by padthaitofuhot** [comment]
This will pushed to master on Monday with release 2.2.1.  In the meantime, please switch to the documentation in the `develop` branch for the correct documentation.

##### OVA Download Links

* [dellemc-ecsce-3.0.0.1-install-node-2.2.0-vm1.ova](http://130852476153187606.public.ecstestdrive.com/public/dellemc-ecsce-3.0.0.1-install-node-2.2.0-vm1.ova)
* [dellemc-ecsce-3.0.0.1-install-node-2.2.0-vm1.ova.xz](http://130852476153187606.public.ecstestdrive.com/public/dellemc-ecsce-3.0.0.1-install-node-2.2.0-vm1.ova.xz)
