### ISSUE TITLE
Step 1 fails when there is no tty

### ISSUE THREAD

**Issue by adrianmo** [EMCECS/ECS-CommunityEdition#287]
Step 1 script fails when there is no TTY in the device running the script.

```
the input device is not a tty
```

Removing the `-t` from the `docker run` command in the `run.sh` file may fix the issue. I will give it a try and submit a PR.

**Comment by padthaitofuhot** [comment]
@adrianmo What I want is to detect whether we have a TTY or not and then change the flag accordingly.  When running under a TTY I absolutely want to have the `-t` flag present on the `docker run` command line.

**Comment by adrianmo** [comment]
@padthaitofuhot OK, I can confirm that the issue was fixed by removing the `-t` flag. We can leave this open until we implement that TTY detection.
