### ISSUE TITLE
Documentation not updated on EMC community page for installation

### ISSUE THREAD

**Issue by bipsendk** [EMCECS/ECS-CommunityEdition#29]
On https://community.emc.com/docs/DOC-45387#centos-installation it is stated in step 5:

Execute the following command as SUDO. For our example the command would look like this: sudo python step1_ecs_singlenode_install.py --disks sdc
The execution of this script is will take about 1-5 minutes depending of how many packages need to be updated. This script executed should be executed on each ECS Node.

But when runninng "python step1_ecs_singlenode_install.py --disks sdc", the script returns:

usage: step1_ecs_singlenode_install.py [-h] --disks DISKS [DISKS ...]
                                       --hostname HOSTNAME [HOSTNAME ...]
                                       --ethadapter ETHADAPTER
                                       [ETHADAPTER ...]
                                       [--onlyContainerConfig] [--cleanup]
step1_ecs_singlenode_install.py: error: argument --hostname is required

Is the hostname parameter the name of the local host - and ethadapter the device name of the ethernet adapter (eth0) ?

If this is the case, I just end up with (after a lot of waiting):

[08/Sep/2015 11:30:22] INFO [root:511] Problem reaching authentication server. Retrying shortly.
Executing getAuthToken: curl -i -k https://10.11.12.152:4443/login -u root:ChangeMe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to 10.11.12.152:4443; Connection refused
[08/Sep/2015 11:30:52] INFO [root:511] Problem reaching authentication server. Retrying shortly.
[08/Sep/2015 11:30:52] CRITICAL [root:514] Authentication service not yet started.
[08/Sep/2015 11:30:52] INFO [root:655] Step 1 Completed.  Navigate to the administrator website that is available from any of the ECS data nodes.         The ECS administrative portal can be accessed from port 443. For example: https://ecs-node-external-ip-address.         The website may take a few minutes to become available.

**Comment by APeter0807** [comment]
The `hostname` parameter should be the desired hostname or IP of the ECS node you are constructing - in the case of a single-node install, it will be the name/address of the local host.

`ethadapter` will be the name of your network interface (eth0 on most systems, ens32 for some - you can check yours via either `ip link show` or `ifconfig -a`, depending on your system).

Assuming that you input the correct information, your authentication service may just be taking longer than normal to start. If at this point the IP you set is still unavailable, however, you may have some other problem with your network setup or with the authentication service itself.

**Comment by bipsendk** [comment]
Seems like it was the ethernet adapter name, that caused the issue.
Step 1 completed successfully, now trying step 2 - which fails with:

Executing REST API command: curl -s -k -X GET -H 'Content-Type:application/json'     -H 'X-SDS-AUTH-TOKEN: BAAcUzByR2ZXSTFDcjFnWEExNGZaM3ZPcUdDc3BnPQMAQQIADTE0NDE3MjQ0MjE1OTQDAC51cm46VG9rZW46YmFkYWI1NTMtOWZkZi00OWM4LWJlZWYtOWZlNmNkN2IyYzAyAgAC0A8='     -H 'ACCEPT:application/json'      https://10.11.12.152:9011/object/namespaces
{"code":7000,"retryable":false,"description":"An error occurred in the API Service","details":"An error occurred in the API service. Cause: error getting the list of namespaces."}Traceback (most recent call last):
  File "step2_object_provisioning.py", line 312, in <module>
    main(sys.argv[1:])
  File "step2_object_provisioning.py", line 304, in main
    print("Namespace: %s" %getNamespaces(ECSNode))
  File "step2_object_provisioning.py", line 68, in getNamespaces
    return executeRestAPI('/object/namespaces', 'GET','.id', "", ECSNode, checkOutput=1)['namespace'][0]["id"]
KeyError: 'namespace'


(started by: python step2_object_provisioning.py --ECSNodes=10.11.12.152 --Namespace=ns1 --ObjectVArray=ova1 --ObjectVPool=ov1 --UserName=user1 --DataStoreName=ds1 --VDCName=vdc1 --MethodName=      )

**Comment by bipsendk** [comment]
Tried to do a fresh re-install. Now it seems like the admin portal shows up at port 64443:

# netstat -lptn | grep 443
tcp        0      0 0.0.0.0:64443           0.0.0.0:*               LISTEN      650/ecsportalsvc

(at least, there is a web page there, looking exactly like the one in the install instructions).

**Comment by sadotimothy** [comment]
@bipsendk you are on the right path, I am guessing by the time you ran the netstat the system was still initializing the new install, you can check again let's see, but as the directions indicated, if you can see the web page then you can proceed with the next step, any previous initialization should be done now.

**Comment by bipsendk** [comment]
Executing REST API command: curl -s -k -X POST -H 'Content-Type:application/json'     -H 'X-SDS-AUTH-TOKEN: BAAcZllMTm1QQ2pRbXhzdTh1bmJhVEZEQS9EZXp3PQMAQQIADTE0NDE4ODgzOTA1NTgDAC51cm46VG9rZW46MWQ3YWRhNTEtZjdkMS00ZjNmLTk2OTktOTM2NTEyZTdhM2JhAgAC0A8='     -H 'ACCEPT:application/json'     -d @request_body.tmp https://10.11.12.152:9011/object/namespaces/namespace
{"code":7000,"retryable":false,"description":"An error occurred in the API Service","details":"An error occurred in the API service. Cause: error creating namespace."}Namespace ns1 is created
Executing REST API command: curl -s -k -X GET -H 'Content-Type:application/json'     -H 'X-SDS-AUTH-TOKEN: BAAcZllMTm1QQ2pRbXhzdTh1bmJhVEZEQS9EZXp3PQMAQQIADTE0NDE4ODgzOTA1NTgDAC51cm46VG9rZW46MWQ3YWRhNTEtZjdkMS00ZjNmLTk2OTktOTM2NTEyZTdhM2JhAgAC0A8='     -H 'ACCEPT:application/json'      https://10.11.12.152:9011/object/namespaces
{"code":7000,"retryable":false,"description":"An error occurred in the API Service","details":"An error occurred in the API service. Cause: error getting the list of namespaces."}Traceback (most recent call last):
  File "step2_object_provisioning.py", line 312, in <module>
    main(sys.argv[1:])
  File "step2_object_provisioning.py", line 304, in main
    print("Namespace: %s" %getNamespaces(ECSNode))
  File "step2_object_provisioning.py", line 68, in getNamespaces
    return executeRestAPI('/object/namespaces', 'GET','.id', "", ECSNode, checkOutput=1)['namespace'][0]["id"]
  File "step2_object_provisioning.py", line 38, in executeRestAPI
    RestOutputDict = json.loads(jsonResult)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I'll try to re-deploy once more and add more CPU ressources...

**Comment by bipsendk** [comment]
Adding more CPU ressources seemed to do the trick. When deploying in vCloud, it helps with 8 vCpu cores..
