### ISSUE TITLE
Add Community Documentation

### ISSUE THREAD

**Issue by padthaitofuhot** [EMCECS/ECS-CommunityEdition#299]
# Code of Conduct

- https://opensource.guide/code-of-conduct/
- https://github.com/codedellemc/community/blob/master/docs/code-of-conduct.md

- [x] CODE_OF_CONDUCT.md <-- We'll use a version of Dell EMC {code}'s (^above^)

# Contributing

- https://github.com/blog/2111-issue-and-pull-request-templates
- https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines
- https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md

- [x] .github/
- [x] .github/CONTRIBUTING.md <-- We're waiting for Legal to get back to us on the CLA/CCLA rules here
- [x] .github/ISSUE_TEMPLATE.md
- [x] .github/PULL_REQUEST_TEMPLATE.md

# README integration
- [x] Code of Conduct
- [x] Contributing

**Comment by captntuttle** [comment]
Waiting on legal...
