### ISSUE TITLE
installer hangs at step1 finished

### ISSUE THREAD

**Issue by bottkars** [EMCECS/ECS-CommunityEdition#307]
hi guys, just getting an issue right now that step1 in single deployment hangs when finished:
https://gist.github.com/bottkars/9f986e96903a4f0dbe275e651f0dfad5#file-step1-issue
even it states successfull, comes not back.

**Comment by captntuttle** [comment]
Yes, I ran into this issue yesterday. If you `sudo docker ps -all` you'll see that there is a dead container in there. I was able to continue by deleting the container before it timed out. The installation will create a new container and continue.

**Comment by adrianmo** [comment]
Can you try it again? This might be related to #305

**Comment by bottkars** [comment]
ok, killing the container seems to work.

**Comment by bottkars** [comment]
well, at least starts step1 again and stops at the same point. it never starts . after rmi and rm, it finally worked

**Comment by adrianmo** [comment]
@bottkars great - the problem was the Docker image. You did well by removing the image and pulling it again.

**Comment by bottkars** [comment]
LOL, still had my headaches on the next run, as mine is the old one :-)

emccorp/ecs-install          latest              8dd6810f4905        8 days ago 

When will a new image made available ?
btw, lloks like the repo for 3.0.0 is messed. Manifest for latest is not available ( guess it point to 3.0.0.2 which has been removed today ?! )

**Comment by bottkars** [comment]
looks fine now , but we need to fix the installer image
![image](https://user-images.githubusercontent.com/8255007/27871937-84fed21c-61a7-11e7-9e2a-5f8f1873df0a.png)

**Comment by adrianmo** [comment]
@bottkars What problem are you experiencing with the installer image?

Also, adding @padthaitofuhot as the owner of that.

**Comment by bottkars** [comment]
@adrianmo @padthaitofuhot, the installer image still dies ( sais remove and then dead) in step 1 without finishing. it still takes multiple kills to finally get it to work.reproducable

**Comment by padthaitofuhot** [comment]
Don't close this until we're confident the issue has been dealt with.

**Comment by padthaitofuhot** [comment]
@bottkars Which branch (master or develop) are you seeing this issue in?

**Comment by bottkars** [comment]
i am using master currently

**Comment by padthaitofuhot** [comment]
Okay, I think I've dramatically replicated this issue:

```
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                     PORTS               NAMES
836bb0aa2657        emccorp/ecs-install:latest   "/usr/local/bin/en..."   7 minutes ago       Dead                                           confident_banach
6431d815db81        emccorp/ecs-install:latest   "/bin/echo echo 'D..."   7 minutes ago       Exited (0) 7 minutes ago                       ecs-install-data
416dd787e510        emccorp/ecs-install:latest   "/usr/local/bin/en..."   16 minutes ago      Dead                                           festive_wing
87942ee17b64        9c11e187a9e9                 "/usr/local/bin/en..."   22 minutes ago      Dead                                           pensive_goldwasser
```

It appears the container namespace is dying _after_ the container ENTRYPOINT script, `entrypoint.sh`, exits, but before control is passed back to the Docker daemon for clean-up.

```
TASK [common_baseline_check : Common | Make sure block device(s) are at least 100GB] ***

TASK [common_baseline_check : Common | Make sure block device(s) are unpartitioned] ***
ok: [192.168.2.221] => (item=/dev/vda)

TASK [common_baseline_check : fail] ********************************************

TASK [common_baseline_check : Common | Check for listening layer 4 ports] ******
changed: [192.168.2.221]

TASK [common_baseline_check : Common | Report any conflicts with published ECS ports] ***

TASK [common_baseline_check : Common | Report any conflicts with internal ECS ports] ***

PLAY RECAP *********************************************************************
192.168.2.221              : ok=11   changed=1    unreachable=0    failed=0

Playbook run took 0 days, 0 hours, 0 minutes, 15 seconds
+ cond_incr_rc 0
+ [ 0 -lt 0 ]
+ simple_shutdown aria2c opentracker
+ processlist=aria2c opentracker
+ wait
+ retry condkill aria2c -INT+
retry condkill opentracker -INT+
local tries=0
+ local+  tries=0condkill
 aria2c -INT
+ condkill opentracker+  -INT
process=aria2c
+ signal=-INT+
process=opentracker
+ signal=-INT
+ + pgreppgrep opentracker aria2c

+ [ -z  ]
+ return 0
+ [ -z  ]
+ return 0
+ cond_incr_rc 0
+ [ 0 -lt 0 ]
+ wait
+ retry condkill aria2c -TERM
+ local tries=0
+ condkill aria2c -TERM
+ process=aria2c
+ signal=-TERM
+ retry condkill opentracker -TERM
+ local tries=0
+ condkill opentracker -TERM
+ process=opentracker
+ signal=-TERM
+ pgrep aria2c
+ pgrep opentracker
+ [ -z  ]
+ [ -z  ]+
return 0
+ return 0
+ cond_incr_rc 0
+ [ 0 -lt 0 ]
+ wait
+ retry condkill aria2c -KILL
+ local tries=0
+ condkill aria2c -KILL
+ process=aria2c
+ + retrysignal=-KILL
 condkill opentracker -KILL
+ local tries=0
+ condkill opentracker -KILL
+ process=opentracker
+ signal=-KILL
+ pgrep aria2c
+ pgrep opentracker
+ [ -z  ]
+ [ -z +  ]return
 0
+ return 0
+ cond_incr_rc 0
+ [ 0 -lt 0 ]
+ exit 0
```

So now I'm going to look at what's going on with Docker that's leading to this outcome.

**Comment by padthaitofuhot** [comment]
Until we have a long-term solution, the work-around to unstick Docker is to run the following command in another shell session when Docker gets stuck:

```
sudo docker rm -f  $(sudo docker ps -a -f 'status=dead' --format '{{.ID}}')
```

If that doesn't unstick the process, please let me know.
