### ISSUE TITLE
hostname check fails on some chars and leads to invalid value in /etc/hostname

### ISSUE THREAD

**Issue by padthaitofuhot** [EMCECS/ECS-CommunityEdition#31]
## Synopsis
The script hostname checking fails on hostnames that contain non alpha-numeric characters and results in invalid contents of `/etc/hostname`.  This behavior leads to a failed deploy and requires user intervention to fix the `/etc/hotname` file.

## Work-Around
Make sure the hostname only contains valid alpha-numeric characters from the set [0-9a-zA-Z].

## Manual Fix in case of Error
If the /etc/hostname file is updated with a bad value, it must be replaced by a valid value. Run the following commands:
1. `hostname <valid hostname>`
2. `hostname >/etc/hostname`

**Comment by jasoncwik** [comment]
@APeter0807 please ensure hostname parameter passes the regex "^[a-z0-9]+" in the step1 script.  Note that I'm *not* accepting uppercase letters since DNS is case-insensitive.

**Comment by APeter0807** [comment]
Hostname is checked against regex for validity as of 35160ca .
