### ISSUE TITLE
ECS CE 3.0.0 Admin Portal Login Issue - Error 10001 (http:401): An error occurred while encoding/decoding of tokens. Unable to decode token.

### ISSUE THREAD

**Issue by sureshdarsru** [EMCECS/ECS-CommunityEdition#320]
I have installed ECS 3.0.0 (Community Edition) (Dockerized from github) in Centos box over AWS cloud. After that when I tried to login to ECS ADMIN PORTAL as 'root' , I am getting below error message.

"Error 10001 (http:401): An error occurred while encoding/decoding of tokens. Unable to decode token."

Also , I am getting below error message popped up.

"This session is expired because it has timed out, the user's login password has been changed, or the logged in user is logged out from another session. To resume your session , please log in again."

Appreciate your help on how to resolve this login issue and pls let me know if you need any other info.

**Comment by padthaitofuhot** [comment]
Usually the session expiration message will show up when you change the password or login for the first time.  What happens if you login a second time using the new password?

**Comment by padthaitofuhot** [comment]
I am closing this issue.  If you want further assistance, please reopen the issue.  Thank you.

**Comment by munishase** [comment]
I am facing same issue. I am able to login to portal successfully, but when calling same api with postman then facing below resultset. even I am sending same request as it is with portal, I observer network calls as well.
{
    "status": "error",
    "messageKey": "ns.msg.query.list.failed",
    "msgDetails": "Error 10001 (http: 401): An error occurred while encoding/decoding of tokens. Unable to decode token.",
    "isSuccess": false,
    "isError": true
}

**Comment by KarimM0hamed** [comment]
The same issue happens to me, does anyone find a way to resolve the error?
