### ISSUE TITLE
bootstrap.sh infinite loop

### ISSUE THREAD

**Issue by bottkars** [EMCECS/ECS-CommunityEdition#321]
Hi,
using centos 7.3, latest docker already installed, causes bootstrap.sh to ininite loop into package installation:

> Error: docker-ce conflicts with 2:docker-1.12.6-32.git88a4867.el7.centos.x86_64
> You could try using --skip-broken to work around the problem

**Comment by padthaitofuhot** [comment]
Why is Docker already installed?  The requirement is vanilla CentOS minimal.

**Comment by padthaitofuhot** [comment]
See #322 for clarification.

**Comment by padthaitofuhot** [comment]
This issue is resolved by #332
