### ISSUE TITLE
OVA Deployment Failure

### ISSUE THREAD

**Issue by ktizzle75** [EMCECS/ECS-CommunityEdition#329]
Receive an error when deploying the OVA in vSphere 6.5:

OVF package with compressed disks is currently not supported for OVF import

**Comment by padthaitofuhot** [comment]
Thank you for bringing this to our attention.  I'll look into it and see what the status of "compressed disks" is in current VMWare products.

**Comment by padthaitofuhot** [comment]
For 2.4.0, stop compressing disks.  Compress the whole OVA.
