### ISSUE TITLE
ACL issue - can't set the lifecycle policy

### ISSUE THREAD

**Issue by yogendramummaneni** [EMCECS/ECS-CommunityEdition#333]
Even though the access_key(user) has full control on the bucket, the user can't update the life cycle policy, getting Access Denied error.
If we make user as bucket owner it works fine. But we can't really do that as every time our app is rebound to the ECS, it is getting new accessKey and secretKey credentials.

**Comment by padthaitofuhot** [comment]
@jasoncwik any ideas?

**Comment by ben-schumacher** [comment]
A quick read of the documentation indicates only bucket owner can modify subresource rules (lifecycle policy).  Unless, a bucket policy is configured to allow `s3:PutLifecycleConfiguration` by other users on the bucket.  Bucket policies are supported in ECS 3.1.

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTlifecycle.html

Thanks,
Ben

**Comment by yogendramummaneni** [comment]
Thanks Ben for clarifying!
