### ISSUE TITLE
Issues with Proxy

### ISSUE THREAD

**Issue by marciakubo** [EMCECS/ECS-CommunityEdition#334]
I am trying to install ECS Virtual on a machine in Dell Solution Center under a proxy.

The proxy is already configured, it was possible to install some package.s

But when the installation reaches 66% it’s hangs on the following error:

Trying to pull repository docker.io/emccorp/ecs-install ...
Pulling repository docker.io/emccorp/ecs-install
Network timed out while trying to connect to https://index.docker.io/v1/repositories/emccorp/ecs-install/images. You may want to check your internet connection or if you are behind a proxy.
> ERROR: Failed to pull the installer image. Check the log for details.
> [ui/pull_image.sh] ERROR: Failed to pull the installer image. Check the log for details.
> [./bootstrap.sh] ERROR: We couldn't pull the ecs-install image for some reason. Please check the logs.
> [./bootstrap.sh] ERROR: If it's something simple, such as the ecs-install:latest image missing from
> [./bootstrap.sh] ERROR: your custom Docker registry, or if your Internet access isn't working, then
> [./bootstrap.sh] ERROR: you may be able to solve the problem by first solving one of the above issues.
> [./bootstrap.sh] ERROR: If you still need more help after trying the above, you can reach us on GitHub.

See the configurations below:

[root@SAOPOCECS01 ECS-CommunityEdition]# env | grep -i proxy
http_proxy=http://10.204.57.5:8080
ftp_proxy=http://10.204.57.5:8080
https_proxy=http://10.204.57.5:8080

**Comment by marciakubo** [comment]
wget works, 

[root@SAOPOCECS01 ECS-CommunityEdition]# wget https://index.docker.io/v1/repositories/emccorp/ecs-install/images
--2017-08-11 00:29:21--  https://index.docker.io/v1/repositories/emccorp/ecs-install/images
Connecting to 10.204.57.5:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘images.2’

    [ <=>                                                                  ] 2           --.-K/s   in 0s

2017-08-11 00:29:22 (257 KB/s) - ‘images.2’ saved [2]

**Comment by padthaitofuhot** [comment]
What does your `bootstrap.sh` command line look like?  Did you use the arguments for dealing with proxies?

**Comment by marciakubo** [comment]
I've tried to use this command:
 ./bootstrap.sh -y -g -c deploy.yml  -p 10.204.57.5:8080
but I've gotten this error:


> important being the speed of your Internet connection.
> The ECS software docker image is around 1.5GiB.
> Bootstrapping requires about 10 minutes under KVM on a
> Xeon E5 with a 250Mbps Internet connection.
>
> 13% [##------------------] Checking proxy connectioncurl: (22) The requested URL returned error: 400 Bad Request
> ERROR: Could not form CONNECT to 'http://10.204.57.5:8080' with provided proxy string

Do you have any idea?

**Comment by padthaitofuhot** [comment]
I'm not sure.  Clearly `curl` is having a hard time tunneling HTTPS through your proxy using the CONNECT verb.  The actual command executed is:

`curl -sSLfI -w '%{http_code}' -x ${proxy_val} --proxytunnel ${proxy_test_val} -o /dev/null -m 10`

Where `proxy_val="10.204.57.5:8080"` and `proxy_test_val="google.com:80"`.  What this is trying to do is form a CONNECT through $proxy_val to $proxy_test_val, and report success or failure via `curl`'s exit code (0=OK).  

I haven't come across a proxy setup yet where `curl` had troubles but `wget` did not.  This is interesting.  Could you perhaps fiddle with `curl` and see if you can figure out what it's getting stuck on?

**Comment by marciakubo** [comment]
Team, thanks for all replies. 

I solved the issue. It was necessary to inform form a file under docker configuration. See the configuration below.

•	[root@SAOPOCECS01 system]# find / -name http-proxy.conf
/etc/systemd/system/docker.service.d/http-proxy.conf

•	[root@SAOPOCECS01 system]# cd docker.service.d/
•	[root@SAOPOCECS01 docker.service.d]# ls
•	http-proxy.conf
•	[root@SAOPOCECS01 docker.service.d]# vi http-proxy.conf
•	[root@SAOPOCECS01 docker.service.d]# systemctl deamon-reload
•	Unknown operation 'deamon-reload'.
•	[root@SAOPOCECS01 docker.service.d]# systemctl daemon-reload
•	[root@SAOPOCECS01 docker.service.d]# systemctl show --property Environment docker
•	Environment=GOTRACEBACK=crash DOCKER_HTTP_HOST_COMPAT=1 PATH=/usr/libexec/docker:/usr/bin:/usr/sbin HTTP_PROXY=
•	
•	[root@SAOPOCECS01 docker.service.d]# systemctl restartdocker
•	Unknown operation 'restartdocker'.
•	[root@SAOPOCECS01 docker.service.d]# systemctl restart docker
•	[root@SAOPOCECS01 docker.service.d]# cd /etc/systemd/system docker pull docker.io/emccorp/ecs-install
•	[root@SAOPOCECS01 system]# docker pull docker.io/emccorp/ecs-install
•	Using default tag: latest
•	Trying to pull repository docker.io/emccorp/ecs-install ...
•	latest: Pulling from docker.io/emccorp/ecs-install

**Comment by padthaitofuhot** [comment]
Reopening to track proxy changes to Docker config.
