### ISSUE TITLE
The ECS disk is full after a few reboots.

### ISSUE THREAD

**Issue by korvinca** [EMCECS/ECS-CommunityEdition#341]
I observed an issue with overloading data after reboot ECS-CommunityEdition VM. It is fresh deployed one node VM, with 10MB data in bucket. After each reboot of VM the free space on disk is reduced. Finally /etc/uuid-XX... value is overloaded with some data and system doesn't response.

**Comment by padthaitofuhot** [comment]
Hello.  How much disk space have you allocated to ECS for object storage?

**Comment by korvinca** [comment]
I experimented with 104GB (default) and 300GB as sdb disk. VM with 300GB works longer till disk still full.

**Comment by padthaitofuhot** [comment]
Okay.  Standard ECS has hundreds of TB to work with, so these issues don't usually show up there.  My guess is this is related to garbage collection.  ECS is not meant to be rebooted except in edge and failure scenarios.  Does the consumed free space after a reboot return to the expected free space if the ECS is left online for 72 hours?

**Comment by korvinca** [comment]
Unfortunately I didn't test it during 72 hours. I reboot system with cli "sudo reboot" each 30 min. for my test.

**Comment by padthaitofuhot** [comment]
What kind of testing are you wanting to do?

**Comment by korvinca** [comment]
We are testing communication between our application and private BlobStore with moving time ahead and sync time from NTP server. To apply new time on ECS I have to restart docker container or reboot VM. I prefer to reboot VM each 30 min after change time on NTP server for clear test. All works fine except overloading ECS disk after reboot. After disk has been full the test failed on our app. I understand what it is not a common case for ECS but it would be nice if you offer any solution to clear garbage collection on start or any workaround for keep free space on ECS during reboot. Thanks!

**Comment by padthaitofuhot** [comment]
My recommendation is to increase the available object storage for the ECS.

**Comment by korvinca** [comment]
We decided to use another S3-emulator for our monstrous experiments. Hence issue can be closed. Thanks.
