### ISSUE TITLE
OVA invocation of /bin/needs-restarting sometimes fails with yum errors

### ISSUE THREAD

**Issue by padthaitofuhot** [EMCECS/ECS-CommunityEdition#342]
Need to use `needs-restarting`'s `-r` flag to detect rather than doing regexy stuff.  Otherwise yum errors on OVA in islands will cause breakage.

**Comment by ruizgonzalo** [comment]
Hi,. im having this error with the ova (install node 2.4.0). island-step1 works OK but step2 fail in the "Check needs-restarting" phase. Any ideas? Thanks

**Comment by ruizgonzalo** [comment]
Hi, i just replaced the /usr/bin/needs-restarting binary by my own script calling /usr/sbin/originalneeds-restarting -r

Thanks

**Comment by padthaitofuhot** [comment]
That won't work to detect whether nodes need restarting or not, but it will allow the install to complete.  Since the OVA build shouldn't ever need rebooting (since nothing is updated) there should be no need to even invoke `needs-restarting`.  I've bumped the priority on this issue.

**Comment by padthaitofuhot** [comment]
Closed by #349
