### ISSUE TITLE
island_step2 fails @ Add install node to /etc/hosts]

### ISSUE THREAD

**Issue by juergenschubert** [EMCECS/ECS-CommunityEdition#354]
### Expected Behavior
island_step1 works without errors
island_step2 fails with
TASK [common_etc_hosts : Common | Add install node to /etc/hosts] **************
fatal: [192.168.202.129]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/local/src/ui/ansible/roles/common_etc_hosts/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Common | Add install node to /etc/hosts\n  ^ here\n"}

### Actual Behavior
island_step2 fails with
TASK [common_etc_hosts : Common | Add install node to /etc/hosts] **************
fatal: [192.168.202.129]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/local/src/ui/ansible/roles/common_etc_hosts/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Common | Add install node to /etc/hosts\n  ^ here\n"}

### Steps to Reproduce Behavior
run island_step2 on my ova

### Output
[admin@luna ~]$ island-step2

PLAY [Common | Ping data nodes before doing anything else] *********************

TASK [ping] ********************************************************************
ok: [192.168.202.129]

PLAY [Installer | Gather facts and slice into OS groups] ***********************

TASK [group_by] ****************************************************************
ok: [192.168.202.129]

PLAY [CentOS 7 | Configure access] *********************************************

TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute ed25519 ssh key] **********
ok: [192.168.202.129]

TASK [CentOS_7_configure_ssh : CentOS 7 | Distribute rsa ssh key] **************
ok: [192.168.202.129]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable SSH UseDNS] ******************
ok: [192.168.202.129]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable requiretty] ******************
ok: [192.168.202.129]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable sudo password reverification for admin group] ***
ok: [192.168.202.129]

TASK [CentOS_7_configure_ssh : CentOS 7 | Disable sudo password reverification for wheel group] ***
ok: [192.168.202.129]

TASK [firewalld_configure_access : Firewalld | Ensure service is started] ******
ok: [192.168.202.129]

TASK [firewalld_configure_access : Firewalld | Add install node to firewalld trusted zone] ***
ok: [192.168.202.129]

TASK [firewalld_configure_access : Firewalld | Add all data nodes to firewalld trusted zone] ***
ok: [192.168.202.129] => (item=172.17.0.1)
ok: [192.168.202.129] => (item=192.168.202.129)

TASK [firewalld_configure_access : Firewalld | Whitelist management prefixes] **
ok: [192.168.202.129] => (item=0.0.0.0/0)

TASK [firewalld_configure_access : Firewalld | Add all public service ports to firewalld public zone] ***
ok: [192.168.202.129] => (item=3218/tcp)
ok: [192.168.202.129] => (item=9020-9025/tcp)
ok: [192.168.202.129] => (item=9040/tcp)

TASK [firewalld_configure_access : Firewalld | Ensure service is started] ******
changed: [192.168.202.129]

PLAY [Common | Configure hostnames] ********************************************

TASK [common_set_hostname : include_vars] **************************************
ok: [192.168.202.129]

TASK [common_set_hostname : Common | Find node hostname] ***********************
ok: [192.168.202.129] => (item=(0, u'192.168.202.129'))

TASK [common_set_hostname : Common | Set node hostname] ************************
ok: [192.168.202.129]

PLAY [Common | Configure /etc/hosts] *******************************************

TASK [common_etc_hosts : Common | Add install node to /etc/hosts] **************
fatal: [192.168.202.129]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/local/src/ui/ansible/roles/common_etc_hosts/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Common | Add install node to /etc/hosts\n  ^ here\n"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
192.168.202.129            : ok=17   changed=1    unreachable=0    failed=1

Playbook run took 0 days, 0 hours, 0 minutes, 9 seconds
Operation failed.
>
[admin@luna ~]$

**Comment by padthaitofuhot** [comment]
Hi.  Please run `catfacts 192.168.202.129` and provide the complete `ansible_default_ipv4` stanza.  It should look something like the example below.

```
"ansible_default_ipv4": {
    "address": "192.168.2.220",
    "alias": "eth0",
    "broadcast": "192.168.2.255",
    "gateway": "192.168.2.1",
    "interface": "eth0",
    "macaddress": "4A:II:E2:15:23:01",
    "mtu": 1500,
    "netmask": "255.255.255.0",
    "network": "192.168.2.0",
    "type": "ether"
},
```

Thanks!

**Comment by padthaitofuhot** [comment]
The task the error is thrown by in `ui/ansible/roles/common_etc_hosts/tasks/main.yml` is below.

```
- name: Common | Add install node to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ hostvars[item].ansible_hostname }}$'
    line: "{{hostvars[item].ansible_default_ipv4.address}} {{hostvars[item].ansible_fqdn}} {{hostvars[item].ansible_hostname}}"
    state: present
  with_items: "{{ groups.install_node }}"
```

The issue here is that `hostvars[item].ansible_default_ipv4.address` should be present if the node has an IP address and a default route.  Network environments without a default route are not supported, even if that default route is unused (eg. islands).

**Comment by padthaitofuhot** [comment]
@juergenschubert were you able to collect that information?

**Comment by juergenschubert** [comment]
Thank you very much for asking. I was not able to collect it as I destroyed/removed the ova and deployed a new one and all steps are working as expected.

**Comment by padthaitofuhot** [comment]
Thank you for getting back to me.  I'm going to close this issue.  Please let us know if we may be of further assistance.

**Comment by wangguoshuai** [comment]
ova_step1 fails because of the same reason.  catfacts the IP , but the ansible_default_ipv4 is empty. How can I edit it ?

**Comment by salauddinaliahmed** [comment]
Same issue ova_step1. Do you have a workaround against this?

**Comment by salauddinaliahmed** [comment]
> Same issue ova_step1. Do you have a workaround against this?
This was solved by building the VM again with the OVF and going through the installation again.
- The last attempt was sorta all over the place after failures.
