### ISSUE TITLE
ECS Check for Centos Version fails when being updated to 7.4

### ISSUE THREAD

**Issue by sillifantah** [EMCECS/ECS-CommunityEdition#355]
### Expected Behavior
ECS should install when being used on Centos 7.4

### Actual Behavior
Installed fails if update to 7.4 has been run - anything post build 1611 will fail 

### Steps to Reproduce Behavior
run ./Bootstrap.sh process
rerun bootstrap process

**Comment by padthaitofuhot** [comment]
This will be resolved in 2.5.0.  CentOS 7.3 is required for 2.4.0.

**Comment by amarcionek** [comment]
The current OVA is build using 7.4 and I'm pretty sure I just experienced this on island_step2: > ERROR: OS unknown and not supported: centos linux release 7.4.1708 (core)

This must mean that deploying from OVA is currently broken because I don't see any links to the 2.3.0 OVA.

**Comment by amarcionek** [comment]
This is even worse than I thought. I deployed a 7.3 from an ISO. But after running bootstrap in step 3, the script says it needs to reboot, and upon reboot the kernel was updated automatically to 7.4!  There is literally no way to install ECS right now?

**Comment by padthaitofuhot** [comment]
As long as it's the bootstrap script that upgrades CentOS, you're fine.

**Comment by padthaitofuhot** [comment]
Closed by #360
