### ISSUE TITLE
Make Jenkins output human readable 

### ISSUE THREAD

**Issue by adrianmo** [EMCECS/ECS-CommunityEdition#357]
The current Jenkins output when executing some of the scripts via Ansible is very hard to read. Changing the output format from JSON to something more human friendly would be very helpful to troubleshoot failed builds. 

Related blog post: http://blog.cliffano.com/2014/04/06/human-readable-ansible-playbook-log-output-using-callback-plugin/

**Comment by padthaitofuhot** [comment]
@adrianmo That PR I merged uses ssh instead of Ansible for great effect.

**Comment by adrianmo** [comment]
Great, log output looks much cleaner now :+1:
