### ISSUE TITLE
Node does not start automatically after reboot.

### ISSUE THREAD

**Issue by bipsendk** [EMCECS/ECS-CommunityEdition#36]
For other reasons, I had to reboot my test server with the single node installation.
After reboot, the single-node ECS installation does not start the services.

What should be done in order to start everything up again - in order to avoid having to start an installation from scratch?

**Comment by padthaitofuhot** [comment]
Thanks for filing an issue on this.

## Disposition 
Enabling the system to boot back up after a reboot should be included in the install script. This enhancement is marked for inclusion in the 2.1 release due out sometime next quarter.

## Work-Around
1. Enable the docker service to run on boot. 
`systemctl enable docker.service`

2. Start the docker container:
`docker start <Your container ID here>`

3. Add a line to `/etc/rc.local` to start the docker container on reboot:
`echo "docker start <Your container ID here>" >>/etc/rc.local`

4. Update `/etc/fstab`*** to make sure the data disk gets mounted on reboot. For example, assuming one data disk as sdb, add:
`/dev/sdb1 /ecs/uuid-1                           xfs     defaults        0 0`

5. Then run `mount -a` to mount all the block devices.

6. Increase the memory limit for pids by running:
`sysctl -w kernel.pid_max=655360`

7. Add that same line (without `sysctl -w`) to `/etc/sysctl.conf` so it's enabled on reboot:
`echo "kernel.pid_max=655360" >>/etc/sysctl.conf`

*** *For reference, here's an excerpt of `mount` output on one of my single-node deployments with five block devices in the datastore:*
```
/dev/sdc1 on /ecs/uuid-1 type xfs (rw,noatime,seclabel,attr2,inode64,noquota)
/dev/sdd1 on /ecs/uuid-2 type xfs (rw,noatime,seclabel,attr2,inode64,noquota)
/dev/sde1 on /ecs/uuid-3 type xfs (rw,noatime,seclabel,attr2,inode64,noquota)
/dev/sdf1 on /ecs/uuid-4 type xfs (rw,noatime,seclabel,attr2,inode64,noquota)
/dev/sdg1 on /ecs/uuid-5 type xfs (rw,noatime,seclabel,attr2,inode64,noquota)
```

**Comment by bipsendk** [comment]
What is the container ID (where do I find it)? It does not seem to be a parameter specified during installation/configuration.

**Comment by Callero** [comment]
Please issue `sudo docker ps` and you should be able to see a container ID

**Comment by bipsendk** [comment]
# docker ps
FATA[0000] Get http:///var/run/docker.sock/v1.16/containers/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

**Comment by bipsendk** [comment]
After 
`systemctl enable docker.service`
there should be a 
`systemctl start  docker.service`
and then (for standalone):
`docker start ecsstandalone`

**Comment by Callero** [comment]
Please remember to use `sudo`

**Comment by bipsendk** [comment]
I am logged in as root :-)

Status so far 5 minutes after reboot and startup:

`tcp        0      0 0.0.0.0:9099            0.0.0.0:*               LISTEN      22724/storageserver`
`tcp        0      0 0.0.0.0:9069            0.0.0.0:*               LISTEN      22724/storageserver`
`tcp        0      0 10.11.12.152:9204       0.0.0.0:*               LISTEN      22704/vnest`
`tcp        0      0 0.0.0.0:9205            0.0.0.0:*               LISTEN      22704/vnest`
`tcp        0      0 0.0.0.0:9206            0.0.0.0:*               LISTEN      22704/vnest`
`tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1045/sshd`
`tcp        0      0 0.0.0.0:64443           0.0.0.0:*               LISTEN      22796/ecsportalsvc`
`tcp6       0      0 :::22                   :::*                    LISTEN      1045/sshd`

**Comment by jasoncwik** [comment]
Depends on issue #66.  Also need to install systemd scripts to ensure docker is auto-started and the docker image is auto-started after docker.

**Comment by keithxanderson** [comment]
Hello, I've followed the single node software only install process for ECS 2.2 plus the workarounds listed above but I can't log into the webUI after a reboot.  Any tips in how to get this working?  I log in as root with the correct password and the page hangs with a spinning "login" animation.  Have CentOS 7 running in a VM.

**Comment by APeter0807** [comment]
Resolved the above issue in discussion elsewhere.

When editing /etc/fstab, use the following settings rather than the default:

`/dev/sdb1 /ecs/uuid-1 xfs rw,noatime,seclabel,attr2,inode64,noquota 0 0`

**Comment by victorock** [comment]
Please see pull request #108

**Comment by bottkars** [comment]
/etc/rc.local is a symlink to /etc/rc.d/rc.local
even if you put stuff into /etc/rc.local, you mast chmod the symlink in /etc/rc.d/rc.local

so chmod +x /etc/rc.d/rc.local should work !

**Comment by padthaitofuhot** [comment]
This is working in installer 2.0.0; unfortunately release has been delayed.
