### ISSUE TITLE
3.0.0.2 installation failed with error "Total block storage available for ECS is less then 100GB (0GB reported by node)"

### ISSUE THREAD

**Issue by ausjackliu** [EMCECS/ECS-CommunityEdition#361]
### Expected Behavior
TASK [common_baseline_check : Common | Make sure block device(s) are at least 100GB] ***

TASK [common_baseline_check : Common | Make sure block device(s) are unpartitioned] ***

### Actual Behavior / Output
TASK [common_baseline_check : Common | Make sure block device(s) are at least 100GB] ***
fatal: [10.251.59.197]: FAILED! => {"changed": false, "failed": true, "msg": "Total block storage available for ECS is less then 100GB (0GB reported by node)"}

### Steps to Reproduce Behavior
I downloaded dellemc-ecsce-3.0.0.2-install-node-2.4.0-vm0.ova and got it deployed on an ESX6.5. I finished the pre-configuration by referring to http://ecsce.readthedocs.io/en/latest/installation/ECS-Installation.html and ran $ step1... Then it kept complaining that there was no available block storage even though the size of hard disk 2 was 104 GB.

This CE is just killing me as I got too many errors while running the command  step1.

**Comment by ausjackliu** [comment]
I've attached my deploy.yml and the install.log as TEST.zip as above.

**Comment by ben-schumacher** [comment]
I have a feeling your:

`
ecs_block_devices:
      - /dev/vda
`

is wrong.

Before running **step1** can do run **lsblk** and paste the output here?  Here's what mine look like.  You can see my data volume is /dev/sdb which is what I then used for ecs_block_devices.

[root@ecs-1 ~]# lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0           2:0    1    4K  0 disk
sda           8:0    0   16G  0 disk
├─sda1        8:1    0    1G  0 part /boot
└─sda2        8:2    0   15G  0 part
  ├─cl-root 253:0    0 13.4G  0 lvm  /
  └─cl-swap 253:1    0  1.6G  0 lvm  [SWAP]
sdb           8:16   0  128G  0 disk
sr0          11:0    1  680M  0 rom

**Comment by ausjackliu** [comment]
Thanks Ben.  Here is how it returns with the command **lsblk**. TA
![lsblk](https://user-images.githubusercontent.com/32562338/31300129-c17f004c-ab3d-11e7-81c4-513709ddc9a0.PNG)

**Comment by ausjackliu** [comment]
In addition, it did says the following while running "ecsremove purge-nodes":

TASK [common_purge_cleanup : Common | Zero first 10MiB of ECS block devices] ***
changed: [10.251.59.197] => (item=/dev/vda)

The output of this command is here:
[ecsremove-purge-nodes.log](https://github.com/EMCECS/ECS-CommunityEdition/files/1367197/ecsremove-purge-nodes.log)

The output of step1 is as below:
[step1.log](https://github.com/EMCECS/ECS-CommunityEdition/files/1367198/step1.log)

I can't understand why it always complains with common_baseline_check even though the previous purge command has completed successfully.

TASK [common_baseline_check : Common | Make sure /data directory does not exist] ***
ok: [10.251.59.197]

TASK [common_baseline_check : fail] ********************************************

TASK [common_baseline_check : Common | Make sure /host directory does not exist] ***
ok: [10.251.59.197]

TASK [common_baseline_check : fail] ********************************************

TASK [common_baseline_check : Common | Make sure block device(s) exist on node] 
ok: [10.251.59.197] => (item=/dev/vda)

TASK [common_baseline_check : fail] ********************************************

TASK [common_baseline_check : Common | Make sure block device(s) are at least 100GB] ***
fatal: [10.251.59.197]: FAILED! => {"changed": false, "failed": true, "msg": "Total block storage available for ECS is less than 100GB (0GB reported by node)"}

Thanks a lot again for your time.

**Comment by ben-schumacher** [comment]
Okay, so your output indicates to me you should be specifying your block storage like this:

`ecs_block_devices: - /dev/sdb`

Can you try that?  Make sure you change all occurrences of /dev/vda to /dev/sdb.

**Comment by padthaitofuhot** [comment]
@ben-schumacher is likely correct.  I also responded here: https://community.emc.com/message/987905#987905

**Comment by ausjackliu** [comment]
@ben-schumacher @padthaitofuhot 
Thanks a lot, guys. 
That fixed it by changing the block device to /dev/sdb. I'm a Windows guy and this is still new to me regarding the device management in Linux. TA!!

**Comment by padthaitofuhot** [comment]
Glad we could help.  In an effort to keep issues to one topic, please open a new issue if we can help with anything else.  Cheers.
