### ISSUE TITLE
GCE node type outdated

### ISSUE THREAD

**Issue by Callero** [EMCECS/ECS-CommunityEdition#38]
The .jinja file point to the wrong source image.

Should be replaced with 
`sourceImage: https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20150915`

Have submitted PR to fix:
https://github.com/EMCECS/ECS-CommunityEdition/pull/37

**Comment by padthaitofuhot** [comment]
Commented on #37
