### ISSUE TITLE
Island Environment deployment failure

### ISSUE THREAD

**Issue by sillifantah** [EMCECS/ECS-CommunityEdition#387]
### Expected Behavior
Expect running island-step2 post bootstrap and island-step1 to suceed

### Actual Behavior

ansible returns failure for TASK [common_etc_hosts : Common | Add data nodes to /etc/hosts] *

### Steps to Reproduce Behavior

post bootstrap , migrate install node to environment (10.154.2.x/17)  then run island-step1 and then island-step2

### Output

TASK [common_etc_hosts : Common | Add data nodes to /etc/hosts] *****************************************************************************************************************************************************************************
fatal: [10.154.2.222]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/local/src/ui/ansible/roles/common_etc_hosts/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Common | Add data nodes to /etc/hosts\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'address'"}
fatal: [10.154.2.221]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/local/src/ui/ansible/roles/common_etc_hosts/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Common | Add data nodes to /etc/hosts\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'address'"}
fatal: [10.154.2.223]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/local/src/ui/ansible/roles/common_etc_hosts/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Common | Add data nodes to /etc/hosts\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'address'"}
fatal: [10.154.2.224]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/local/src/ui/ansible/roles/common_etc_hosts/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Common | Add data nodes to /etc/hosts\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'address'"}
fatal: [10.154.2.225]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/local/src/ui/ansible/roles/common_etc_hosts/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Common | Add data nodes to /etc/hosts\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'address'"}
fatal: [10.154.2.226]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/local/src/ui/ansible/roles/common_etc_hosts/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Common | Add data nodes to /etc/hosts\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'address'"}
fatal: [10.154.2.220]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/local/src/ui/ansible/roles/common_etc_hosts/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Common | Add data nodes to /etc/hosts\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'address'"}

**Comment by padthaitofuhot** [comment]
You must run `island-step1` before migrating the VM.

**Comment by sillifantah** [comment]
That was done  - with some issues
the process was 

- run bootstrap
- post install node reboot , run island-step1
- this fails if the subnet for the island is not present  : FATAL: [10.154.2.220] : UNRECHABLE
- so then the second subnet is added , while preserving the first subnet on a different nic (on the install node) and post that - the first subnet is removed completely 

this gives the same outcome if the old subnet is present or not

**Comment by padthaitofuhot** [comment]
If the Install node's subnet changes, then `deploy.yml` will need to be updated with the new `install_node:` IP address using `videploy`.

**Comment by sillifantah** [comment]
![image](https://user-images.githubusercontent.com/11227650/32800119-6bc5b7f2-c971-11e7-8965-54531a2393ad.png)

its already on the correct IP as per the island environment - is it meant to not be set to that when running island-step1 ?

this still fails

**Comment by padthaitofuhot** [comment]
the `install_node:` field must always be set to the current IP address for the install node.  If the install node has a different IP outside of the island than inside of it, then this field must be changed accordingly.

**Comment by sillifantah** [comment]
Ok 

let me make sure I have it correct 

set it to the valid IP - outside the island 
Then migrate to the island , change IP
use videploy to update 

try again ?

**Comment by sillifantah** [comment]
HI trying the above gives the same error : 

![image](https://user-images.githubusercontent.com/11227650/32850105-27a9d0a4-ca29-11e7-8fd3-31f7c34b4139.png)

**Comment by padthaitofuhot** [comment]
For island deployments, please use the OVA deployment method: https://github.com/EMCECS/ECS-CommunityEdition/blob/master/docs/source/installation/OVA_Installation.md
