### ISSUE TITLE
Build fails: mktorrent-borg: unrecognized option: i

### ISSUE THREAD

**Issue by adrianmo** [EMCECS/ECS-CommunityEdition#390]
Build fails in the "Deploy ECS" stage with the following error:

```
TASK [installer_build_cache : Installer | Create cache distribution torrent file] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "mktorrent-borg -ig 'facts*' -a udp://192.168.1.118:6881 -a http://192.168.1.118:6881/announce -o /var/cache/emc/ecs-install/cache.torrent -pub /var/cache/emc/ecs-install", "delta": "0:00:00.116930", "end": "2017-11-16 10:50:23.148179", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-11-16 10:50:23.031249", "stderr": "mktorrent-borg: unrecognized option: i\nUse -h for help.", "stderr_lines": ["mktorrent-borg: unrecognized option: i", "Use -h for help."], "stdout": "mktorrent 1.1 (c) 2007, 2009 Emil Renner Berthing", "stdout_lines": ["mktorrent 1.1 (c) 2007, 2009 Emil Renner Berthing"]}
```

Looks like the version 1.1 of `mktorrent` does not accept the `-ig` option to ignore files.

I believe we have two options: 

1) Update the shell command here with the way to ignore files: https://github.com/EMCECS/ECS-CommunityEdition/blob/09e1186f8a3a71cc59d1946fcb8a59bcd3aa7c18/ui/ansible/roles/installer_build_cache/tasks/main.yml#L27

2) Install a working version instead of `edge_community` here: https://github.com/EMCECS/ECS-CommunityEdition/blob/09e1186f8a3a71cc59d1946fcb8a59bcd3aa7c18/ui/resources/docker/Rockerfile#L37

@padthaitofuhot since you are the mastermind behind the installer, I leave it up to you :)

Entire log here: http://10.1.83.120/job/ecs-ce/job/develop/9/

**Comment by padthaitofuhot** [comment]
Resolved by #391
