### ISSUE TITLE
Allow custom ECS node names

### ISSUE THREAD

**Issue by firestarter247** [EMCECS/ECS-CommunityEdition#399]
### Expected Behavior
In the deploy.yml file, there is a naming convention setting that says it's optional:

    # [Optional]
    # Picklist for node names.
    # Available options:
    #  - "moons" (ECS CE default)
    #  - "cities" (ECS SKU-flavored)
    #autonaming: moons

If I comment this out, I would expect ECS to name its instance to whatever the computer name is of the system running the docker container.

### Actual Behavior
Even when commenting out the autonaming line in deploy.yml, once step1 is ran, the system is named "luna" instead of the original name given. 

### Steps to Reproduce Behavior

1. Create Deploy.yml
2. Bootstrap the system and reboot
3. Run step1

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by padthaitofuhot** [comment]
I'm not sure I understand the benefit of this feature request.  Please provide some additional context for clarity?

**Comment by firestarter247** [comment]
When not in an island environment, moon or city names may conflict with existing test/dev hosts since ansible appears to change the physical host name as well as naming the docker container. Is there an issue with renaming the physical host (CentOS) after running step1 and step2?

**Comment by padthaitofuhot** [comment]
So I'm clear what the issue is, could you expand a bit on "may conflict with existing test/dev hosts"?

**Comment by firestarter247** [comment]
My apologies. I don't mean to be vague. The vm running CentOS actually gets its hostname changed to luna (assuming moons was selected or even if autonaming is commented out in deploy.yml). So, both the host and the dockers names are luna after the completion of step1.

Pre-bootstrap hostname:
[root@mbg-ecs-test-001 ~]# hostnamectl
   Static hostname: mbg-ecs-test-001
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 9e8f3e3a87df4f259a82375d8ae1433e
           Boot ID: 54674622e2ae41669c9d806666b1ebfa
    Virtualization: xen
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.11.1.el7.x86_64
      Architecture: x86-64



Post-bootstrap hostname (post reboot):
[root@mbg-ecs-test-001 ~]# hostnamectl
   Static hostname: mbg-ecs-test-001
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 9e8f3e3a87df4f259a82375d8ae1433e
           Boot ID: 9f789c90e8f44e2fbd5c88a38cab8fc9
    Virtualization: xen
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.11.1.el7.x86_64
      Architecture: x86-64


Post step1 (no reboot - you can see the root screen still says the hostname I gave to the VM, but hostnamectl now displays luna):

[root@mbg-ecs-test-001 ~]# hostnamectl
   Static hostname: luna.local
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 9e8f3e3a87df4f259a82375d8ae1433e
           Boot ID: 02e65d2c86514bf8847e91a720b42e39
    Virtualization: xen
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.11.1.el7.x86_64
      Architecture: x86-64


Not only would I like the VM to be named mbg-ecs-test-001, but I would also like the docker container to assume that name as well. This is not only because of existing test server name conflicts but also because I want to install ECS CE in multiple sites to emulate our production ECS environment and having each node in each site being named 'luna' can be a bit difficult to keep track of what is what.

**Comment by padthaitofuhot** [comment]
Renaming is an expected part of the deployment process.  It is recommended to use subdomains to add uniqueness, such as luna.dev-ecs01.atl.domain.tld versus luna.ecs-lab-04.sea.domain.tld.

Allowing arbitrary hostnames or using hostnames collected from each node would require substantial effort, as would allowing arbitrary docker container names or container names based on the hostname.  This is not something we have the resources to implement at this time.  If you're willing to generate a patch and submit a PR, we will review it as time permits.

**Comment by firestarter247** [comment]
Thank you. I must be a bit confused on how to rename then? Could you elaborate?

**Comment by padthaitofuhot** [comment]
The are renamed by the installer, as you previously described.  This is the expected behavior.

**Comment by firestarter247** [comment]
Ok. Sorry to take up your time. I will look into subdomains as you mentioned. Thank you for the quick responses.

**Comment by padthaitofuhot** [comment]
This feature has been requested quite a few times and therefore I am implementing it, albeit in a somewhat non-intuitive way.

**Comment by padthaitofuhot** [comment]
Okay, this is implemented in develop and will be pushed out with the 2.6.0 release (today)
