### ISSUE TITLE
Documentation Mismatch / Possible Mistake

### ISSUE THREAD

**Issue by rodfmarin** [EMCECS/ECS-CommunityEdition#4]
Hello,

There appears to be incorrect information regarding the web ui instructions.

This starts here:
![image](https://cloud.githubusercontent.com/assets/9387266/8858022/eaa2f978-3129-11e5-9fbc-13dcfda95cfa.png)

Has text that is not rendered correctly, and the raw text shows:
![image](https://cloud.githubusercontent.com/assets/9387266/8858056/1a40e8ca-312a-11e5-8553-a98f5420702c.png)
(root with any password)

However, in the setup scripts, the login used is not 'root' with a blank password but 'root/ChangeMe'.
![image](https://cloud.githubusercontent.com/assets/9387266/8858133/978e3ab2-312a-11e5-990b-118f3d57ad13.png)
(Taken from step2 setup script)

And shown here in the main setup guide:
![image](https://cloud.githubusercontent.com/assets/9387266/8858142/a962f21e-312a-11e5-8b3c-7a948bd7e3a0.png)

**However, none of these methods work!**

(Evidence Below):

![image](https://cloud.githubusercontent.com/assets/9387266/8858225/1fda4762-312b-11e5-8365-eeb6689ec6b5.png)

Updated:
Tried this again in a standalone configuration.  If the container doesn't fully start or consumes most of the system resources, you can run into this issue (failed login).  My 4 node lab was in a similar state.  When all 4 nodes were online with containers running, System resources appeared to be heavily consumed on one or two nodes.  It seems this prevents the cluster from achieving some sort of quorum, thus preventing login from working.  However, the documentation still has a mismatch.

**Comment by padthaitofuhot** [comment]
Thank you for reporting the docbug.  The correct login is root/ChangeMe.  There is another issue (see #8) that explains the login problem when the the cluster isn't up yet.
