### ISSUE TITLE
add node to existing storage pool

### ISSUE THREAD

**Issue by mohammad16** [EMCECS/ECS-CommunityEdition#408]
hi friends
i  have implemented ECS infrastructure recently by one installation node that boot strapped 4 Data node in my storage pool (SP1).
now i want add 1 Data node in Existing Storage pool(SP1) , can i do it? 
how can i do it?
bets resgards

**Comment by padthaitofuhot** [comment]
Hi Mohammad.  Thank you for contacting us.  Unfortunately resizing storage pools is not supported under ECS Community Edition.  It requires lifecycle components which are only available in ECS appliances.

**Comment by mohammad16** [comment]
thank you dear friend.
