### ISSUE TITLE
OVA download does not work (ECS Community 2.6.1)

### ISSUE THREAD

**Issue by shezzski** [EMCECS/ECS-CommunityEdition#412]
The URL for the OVA of ECS Community Edition Install Node 2.6.1 (ECS 3.1.0.3) which is "http://130852476153187606.public.ecstestdrive.com/public/dellemc-ecsce-3.1.0.3-install-node-2.6.1-vm0.ova" results in an XML error

`<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>public/dellemc-ecsce-3.1.0.3-install-node-2.6.1-vm0.ova</Resource><RequestId>0c07c835:16174cb5b94:1f96d:130</RequestId></Error>`

**Comment by padthaitofuhot** [comment]
Hi @shezzski.  The issue has been resolved.  Please let us know if you encounter additional issues accessing the OVA.
