### ISSUE TITLE
step2 stuck with WAIT: api_endpoint=192.168.0.23 username=root dt_query fail: 'unknown_dt_num'

### ISSUE THREAD

**Issue by yanfaubert** [EMCECS/ECS-CommunityEdition#413]
### Expected Behavior
step2 completes successfully using the All-in-One Single-Node Deployments instructions

### Actual Behavior
Step2 is stuck with this repeating error:

[ecs@luna ECS-CommunityEdition]$ step2
> Pinging Management API Endpoint until ready
> Pinging endpoint 192.168.0.23... (CTRL-C to break)
> WAIT: api_endpoint=192.168.0.23 username=root dt_query fail: 'unknown_dt_num'
> WAIT: api_endpoint=192.168.0.23 username=root dt_query fail: 'unknown_dt_num'
> WAIT: api_endpoint=192.168.0.23 username=root dt_query fail: 'unknown_dt_num'
> WAIT: api_endpoint=192.168.0.23 username=root dt_query fail: 'unknown_dt_num'
> WAIT: api_endpoint=192.168.0.23 username=root dt_query fail: 'unknown_dt_num'
> WAIT: api_endpoint=192.168.0.23 username=root dt_query fail: 'unknown_dt_num'
....

[root@luna ~]# docker image ls
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
docker.io/emccorp/ecs-install          latest              f92fcd99258b        7 days ago          145 MB
emccorp/ecs-install                    latest              f92fcd99258b        7 days ago          145 MB
docker.io/emccorp/ecs-software-3.1.0   3.1.0.3             47a90ee6b81d        2 weeks ago         1.61 GB
docker.io/hello-world                  latest              f2a91732366c        3 months ago        1.85 kB
docker.io/emccorp/ecs-software         latest              8cab09d46cb1        2 years ago         1.66 GB

[root@luna ~]# docker ps --no-trunc
CONTAINER ID                                                       IMAGE                         COMMAND                                               CREATED             STATUS              PORTS               NAMES
65a9ba08bbd2b368fd64783514ebf27b08cc426683e8fe564130ea318f4c8139   emccorp/ecs-install:latest    "/usr/local/bin/entrypoint.sh ecsconfig ping -c -x"   22 minutes ago      Up 22 minutes                           xenodochial_aryabhata
14dafae4fa87464f6420f74a87a82556e66bf68be8ba2744dbd134139ba51832   emccorp/ecs-software:latest   "/opt/vipr/boot/boot.sh"                              33 minutes ago      Up 33 minutes                           ecs-storageos

### Steps to Reproduce Behavior

1. I followed the instructions from this site: https://github.com/EMCECS/ECS-CommunityEdition/blob/master/docs/source/installation/Standard_Installation.md#all-in-one-single-node-deployments
2. No issues, I can even login to the Web portal using my Web browser with the root account and default password.  But there are no VDC / Storage Pool / etc. created.
3. Run step2 and it doesn't seem to be working, stuck in a loop.

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by padthaitofuhot** [comment]
It looks like one of the ways a deployment will fail if `ecs_block_devices:` is not correct in `deploy.yml`.  Please check that the block device names accurately represent the VM hardware.

**Comment by yanfaubert** [comment]
Yes the correct block device was specified (/dev/sdb in my case).

I can see something was done to /dev/sdb:

[ecs@luna ECS-CommunityEdition]$ sudo fdisk -l /dev/sdb
WARNING: fdisk GPT support is currently new, and therefore in an experimental phase. Use at your own discretion.

Disk /dev/sdb: 111.7 GB, 111669149696 bytes, 218103808 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: gpt
Disk identifier: 5282A3DF-1C22-4B71-802B-A0366739463A


#         Start          End    Size  Type            Name
 1         2048    218101759    104G  Microsoft basic xfs

[ecs@luna ECS-CommunityEdition]$ mount | grep sdb
/dev/sdb1 on /ecs/uuid-dedf6163-5433-4f1b-8f2e-ca5af1768198 type xfs (rw,noatime,seclabel,attr2,inode64,noquota)

**Comment by yanfaubert** [comment]
Another interesting data point, if I ctrl-c it continues and is able to create the VDC and add the license.

If I ctrl-c it continues and is able to create the VDC and add the license:
> WAIT: api_endpoint=192.168.0.23 username=root dt_query fail: 'unknown_dt_num'
^C
Aborted!
>
> Installing licensing in ECS VDC(s)
> Using default license
> Adding licensing to VDC: vdc1
>       OK
> Added default license to ECS
>
> Pinging Management API Endpoint until ready
> Pinging endpoint 192.168.0.23... (CTRL-C to break)
> WAIT: api_endpoint=192.168.0.23 username=root dt_query fail: 'unknown_dt_num'
> WAIT: api_endpoint=192.168.0.23 username=root dt_query fail: 'unknown_dt_num'

**Comment by yanfaubert** [comment]
But creating the storage pool fails with this stack:

> Creating Storage Pool: vdc1/sp1
Traceback (most recent call last):
  File "/usr/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.6.1', 'console_scripts', 'ecsconfig')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/ecsconfig.py", line 646, in sp
    tasks = add_all()
  File "/usr/bin/ecsconfig.py", line 622, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/bin/ecsconfig.py", line 602, in add_one
    sp_id = sp_create(name, conf.ecs.sp_ecs_options(name))
  File "/usr/bin/ecsconfig.py", line 560, in sp_create
    resp = conf.api_client.storage_pool.create(**kwargs)
  File "/usr/lib/python2.7/site-packages/ecsclient/common/provisioning/storage_pool.py", line 109, in create
    return self.conn.post('vdc/data-services/varrays', json_payload=payload)
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Unrecognized field "isColdStorageEnabled" (Class com.emc.storageos.data.datasvcmodels.VirtualArrayCreateParam), not marked as ignorable
 at [Source: org.eclipse.jetty.server.HttpInput@3aecab3e; line: 1, column: 31] (through reference chain: com.emc.storageos.data.datasvcmodels.VirtualArrayCreateParam["isColdStorageEnabled"]) - Bad request body: https://192.168.0.23:4443/vdc/data-services/varrays 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo
>

**Comment by yanfaubert** [comment]
This is strange, I was expecting a version of 3.something:

[ecs@luna ECS-CommunityEdition]$ sudo docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS               NAMES
14dafae4fa87        emccorp/ecs-software:latest   "/opt/vipr/boot/bo..."   About an hour ago   Up About an hour                        ecs-storageos

[ecs@luna ECS-CommunityEdition]$ sudo docker exec -it 14dafae4fa87 cat /etc/ecs_release
2.0.1.0.62273.ca0b6cd

**Comment by padthaitofuhot** [comment]
Yeah, that looks like a very old docker image was either already present on the install node or else was pulled in by the bootstrap script and a custom release.conf.  I'm releasing ECS CE 2.7.0 shortly, which installs ECS 3.2.0.0 by default.  You may want to install via the OVA image.
