### ISSUE TITLE
Can't access object by Firefox 

### ISSUE THREAD

**Issue by chcoboo17kimo** [EMCECS/ECS-CommunityEdition#423]
### Expected Behavior
I have a object(Picture) and upload to ECS. Change the permission and check the object by Firefox, IE and Chrome.

### Actual Behavior
(Please put additional output and logs in the section for that below)

### Steps to Reproduce Behavior

1.upload the object(Picture) to ECS bucket and change permission to public 
2.Open the browser and check  the object 
3.http can show the picture in any browser. But https only can work at IE , Chrome. 

 But our environment only can use Firefox. Will get error message "SSL_ERROR_NO_CYPHER_OVERLAP
https://ns1.ecs95.solcenter.local:9021/francesbucket/O1.jpg

![firefox](https://user-images.githubusercontent.com/38967344/39610665-9fa3c516-4f84-11e8-926a-8d7655cfb6f4.png)

It's the same, but IE can work accordingly.
https://ns1.ecs95.solcenter.local:9021/francesbucket/O1.jpg

"

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by jasoncwik** [comment]
Looks like FF and ECS can't agree on a ciphersuite.  I ran wireshark and it appears that FF only wants ECDHE whereas ECS is only advertising ECDH.  You can fix by doing the following:

1. Enter the container: 
```
nsenter -i -m -p -u -t `pidof dataheadsvc`
```
2. Edit the cipher suites:
```
vi /opt/storageos/conf/security-ciphers.xml
```
3. On line 17, add the following two lines:

```
                 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
                 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
```

4. Save and exit
5. Restart dataheadsvc:
```
kill `pidof dataheadsvc`
```

I opened an internal ticket to update our cipher list in the next release of ECS.

**Comment by chcoboo17** [comment]
Thanks for your quickly update. The issue has been resolved. Appreciate
