### ISSUE TITLE
issue after ./bootstrap.sh ERROR: OS unknown and not supported: centos linux release 7.5.1804 

### ISSUE THREAD

**Issue by odcw** [EMCECS/ECS-CommunityEdition#425]
### Expected Behavior
I'm truying to install on physical server with CentOS 7.4.1708 (64bits)

### Steps to Reproduce Behavior

1.[root@ecs ECS-CommunityEdition]#
[root@ecs ECS-CommunityEdition]# ./bootstrap.sh -c deploy.yml
>
>  ECS Community Edition Install Node Bootstrap 2.7.0r
>  ECS Software Image emccorp/ecs-software-3.2.0:3.2.0.0
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
> Escalating privileges
>     You may be presented with the system sudo banner and asked
>     for your password depending on the Linux flavor and default
>     sudo configuration for your system.
>
>
****# > ERROR: OS unknown and not supported: centos linux release 7.5.1804 (core)****
[root@ecs ECS-CommunityEdition]#

2.
3.

**Comment by padthaitofuhot** [comment]
Resolved by PR #426 , which adds support for CentOS 7.5.  Please do a `git pull` on master branch to get the update.

**Comment by odcw** [comment]
it's ok now Thank for you reactivity
