### ISSUE TITLE
http://130852476153187606.public.ecstestdrive.com/public/dellemc-ecsce-3.2.0.0-install-node-2.7.0-vm0.ova is unreachable.

### ISSUE THREAD

**Issue by robinbohm** [EMCECS/ECS-CommunityEdition#428]
### Expected Behavior
Tried to download the last working release from the addres as mentioned

### Actual Behavior
(Please put additional output and logs in the section for that below)
Now progress box or anything happening with the download

### Steps to Reproduce Behavior

1. Download the second release from https://github.com/EMCECS/ECS-CommunityEdition/releases2.
3.

### Relevant Output and Logs
*.ova is unreachable
# Output and Logs go here
*.ova is unreachable
---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by padthaitofuhot** [comment]
Maintenance has ended and the OVA is once again available.  However, please use the latest release OVA: http://130852476153187606.public.ecstestdrive.com/public/dellemc-ecsce-3.2.0.1-install-node-2.7.2-vm0.ova
