### ISSUE TITLE
ssl certificates

### ISSUE THREAD

**Issue by odcw** [EMCECS/ECS-CommunityEdition#435]
### Expected Behavior
it's possible to install ssl certificates with Community Edition?

If yes, How we can do it ? directly in docker container or from Host ?

### Actual Behavior
(Please put additional output and logs in the section for that below)
without valide ssl certificat we can not use CIFS-ECS tools
### Steps to Reproduce Behavior

1.
2.
3.

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by jasoncwik** [comment]
Yes you can install ecscli (`pip install ecscli`) on any client machine and use the keystore commands to update the certificates. There is one certificate for management (`ecscli vdc_keystore`) and one certificate for the object protocols (`ecscli keystore`).

https://community.emc.com/people/coneryj/blog/2016/06/23/ssl-certificates
