### ISSUE TITLE
there are some merge fragment issues in /step1_ecs_singlenode_install.py_

### ISSUE THREAD

**Issue by bottkars** [EMCECS/ECS-CommunityEdition#44]
bebinning from 464 delet 
<<<<<<< HEAD
=======
        os.system(
            "docker exec -t  ecsstandalone cp /opt/storageos/conf/common.object.properties /opt/storageos/conf/common.object.properties.old")
>>>>>>> bugfix-singlenodeDTs

**Comment by padthaitofuhot** [comment]
Resolved in #45
