### ISSUE TITLE
Can't log in to ECS portal on a fresh install (single all in one) using known good credentials. 

### ISSUE THREAD

**Issue by fdesantis888** [EMCECS/ECS-CommunityEdition#442]
### Expected Behavior
Unable to log into ECS portal, for a single node ( all in one instalaltion ).

### Actual Behavior
I used root, admin, administrative users and admin1 and monitor1 management users.
Could not log in with these know good credentials.
Thanks in advance for your help.

### Steps to Reproduce Behavior

1. http://my_ecs_installation_node_ip_address
2. Used root, admin, administrative users and admin1 and monitor1 management users with proper passwords and could not log in. 

### Relevant Output and Logs
```
# Output and Logs go here
```
![image](https://user-images.githubusercontent.com/40803533/42235277-29a62a5a-7eac-11e8-8f0f-613401791069.png)

[install.log](https://github.com/EMCECS/ECS-CommunityEdition/files/2160453/install.log)

[deploy.yml.txt](https://github.com/EMCECS/ECS-CommunityEdition/files/2160463/deploy.yml.txt)

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by padthaitofuhot** [comment]
The correct login for the portal is:

Username: root
Password: ChangeMe

If that isn't working, it's possible one or more services was unable to activate.  What are your resource levels for the ECS CE VM?

**Comment by fdesantis888** [comment]
Cluster issues on the hyper visor I was using turned out to be the issue.   It probably caused a bad install due to resource issues, just as you mentioned.  After its resolution and re-running ova-step2, I was able to log into the portal.   Thank You for your help.

**Comment by padthaitofuhot** [comment]
Also, the ECS password you specify in deploy.yml should match the edition of ECS you are installing.  It should not change unless you have received an ECS image with a different default password than "ChangeMe".
