### ISSUE TITLE
Object Metadata using Amazon S3 Java API against ECS instance

### ISSUE THREAD

**Issue by Azimuts** [EMCECS/ECS-CommunityEdition#451]
### Expected Behavior

Get the content length of a Object using the aws api (1.11.442)
Using Amazon S3 api againt a ECS instance (coomunity edition ) always returns 0 at content-length... The content length if object is just created is returned at a no standard header called: ( x-emc-previous-object-size)

### Relevant Output and Logs

             Content-Length : 0
             ETag : 78821a05d282822e4abec190c061ba78
             Last-Modified : Mon Nov 05 13:17:14 CET 2018
             Proxy-Connection : Keep-Alive
             x-emc-mtime : 1541420234867
             x-emc-previous-object-size : 14

Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by padthaitofuhot** [comment]
Please try with a newer version of Community Edition.  Thanks!
