### ISSUE TITLE
Standard Install - error in 'jsonfile' cache plugin 

### ISSUE THREAD

**Issue by Lupi619** [EMCECS/ECS-CommunityEdition#452]
### Expected Behavior
Step1 should finish successfully with no errors.  

### Actual Behavior
PLAY [Common | Ping data nodes before doing anything else] *********************
 [WARNING]: error in 'jsonfile' cache plugin while trying to read
/var/cache/emc/ecs-install/facts/192.168.73.54 : Expecting ',' delimiter or
'}': line 684 column 8 (char 23594). Most likely a corrupt file, so erasing and
failing.

ERROR! Error while decoding the cache file /var/cache/emc/ecs-install/facts/192.168.73.54: The cache file /var/cache/emc/ecs-install/facts/192.168.73.54 was corrupt, or did not otherwise contain valid data. It has been removed, so you can re-run your command now.
Operation failed.

### Steps to Reproduce Behavior

1.  Minimal CentOS 7 install with yum updates (CentOS Linux release 7.5.1804 (Core)), of 5 hosts (1 as installer, 4 nodes)
2.  Manual yum install docker, docker-python, ntp, pigz on all nodes  (maybe there is more needed to install?)
3.  run step1 (usually fails at first with ntp error, seems that the ntp service doesn't always stay on, but when started it gets pass this part and then the above error)

### Relevant Output and Logs
This happens to everyone, here at work (I'm a DellEMC employee) who has tried to deploy on a CentOS7,5 manual minimal install,  It's the smae version as the ECS-ova, but not sure what's missing.  While using WinSCP I notice that the file in question is spread out through all nodes.  But the script seems to edits the file (/var/cache/emc/ecs-install/facts/192.168.73.54) on the install node and removes some lines on the bottom of the file (which I've noticed while coping and analyzing files through WinSCP).  Which the script then sees as corrupt and deletes the file.  I can't even run a 'ecsremove purge-nodes' is because the file is now missing.  If I copy it over from one of the nodes, it accepst it and then does the samething to the next IP file. If I replace alll of them, then it goes back to the beginning.  I have not goone through the script code yet to see exactly what is going on but, I have very few options other than the ova.  The ova works with ova_step1 (other than the ntp serivce thing) and is the same exact CentOS version, although ova_step2 fails for whatever reason, but that's for another post.   Any help would be appreciated.  

# Output and Logs go here
```

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by LucasGhost** [comment]
Hi, looks like i have same issue on CentOS Linux release 7.6.1810 (Core)
