### ISSUE TITLE
There is no license.xml 

### ISSUE THREAD

**Issue by alaralar** [EMCECS/ECS-CommunityEdition#454]
There is no license.xml or license.lic in OVA version ECS-CommunityEdition. No way to configure this software.

Need to add more information about free trial license.lic file. How and where it can be obtained for OVA version.

**Comment by captntuttle** [comment]
I have temporarily uploaded the license here so that you can unblock: http://131118670375936839.public.ecstestdrive.com/public/license.lic

I will update the repo accordingly.

**Comment by alaralar** [comment]
It's working. Thank you!

**Comment by amjadalvi** [comment]
I can't see licence file either in other installation as well.
