### ISSUE TITLE
Root Password for Console

### ISSUE THREAD

**Issue by amarcionek** [EMCECS/ECS-CommunityEdition#464]
### Expected Behavior

Root password is ChangeMe according to the [readme](https://github.com/EMCECS/ECS-CommunityEdition).

### Actual Behavior

Login incorrect when logging in via console or SSH

### Steps to Reproduce Behavior

1. Deploy OVA, configure it, start it.
2. Login to console or SSH using root account and password ChangeMe.

Now, I know those could be the passwords for the management console and not the OS. Is root login disabled for the console?  I think if that is the case, the bootstrapping instructions should indicate what account to login to the console with.

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by captntuttle** [comment]
I will have to correct the readme - the root password is now unknowable. In order to log into the ECS VM you will have to use the admin credentials and sudo for anything that requires superuser.

**Comment by amarcionek** [comment]
Thanks!
