### ISSUE TITLE
ECS issue to deploy OVA version

### ISSUE THREAD

**Issue by lcoudures** [EMCECS/ECS-CommunityEdition#470]
Hello
I am getting this error trying to deploy ECS OVA

TASK [common_baseline_check : fail] *******************************************************************************************************
failed: [192.168.183.11] (item={'_ansible_parsed': True, u'stat': {u'exists': False}, '_ansible_item_result': True, '_ansible_no_log': False, u'changed': False, 'item': u'/dev/vda', u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'/dev/vda', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}}) => {"failed": true, "item": {"changed": false, "invocation": {"module_args": {"checksum_algorithm": "sha1", "follow": false, "get_attributes": true, "get_checksum": true, "get_md5": true, "get_mime": true, "path": "/dev/vda"}}, "item": "/dev/vda", "stat": {"exists": false}}, "msg": "A block device configured in deploy.yml does not exist on the node."}

any idea how to solve it?

I ran videploy, configured and static IP, localhost for DNS and the rest is default.

**Comment by captntuttle** [comment]
Yeah it looks like the block device in deploy.yml is misconfigured, or you don't have one.

CE requires a separate block device, most likely called `sdb`. You can see this easily with the `lsblk` command.

**Comment by lcoudures** [comment]
thanks @captntuttle that was exactly the problem, in my computer the disk was sdb.

problem solved!
