### ISSUE TITLE
ECS 3.3 fresh install no more space

### ISSUE THREAD

**Issue by bentoisoucy** [EMCECS/ECS-CommunityEdition#471]
I've just installed a fresh ECS 3.3 with the OVF. Use the default hard disk size of 100 Gig.  I dont need more for my test.  I only have 6 little pdf file uploaded to my name space and I already have 56 Gig used from the total 90 Gig.  Is it normal ?, Can I expand the disk size after the install ?

**Comment by captntuttle** [comment]
How long ago since you installed this OVA?

**Comment by bentoisoucy** [comment]
1 day

Envoyé de mon iPhone

**Comment by captntuttle** [comment]
It is normal for ECS CE to fill up on it's own. the standard 104GB storage is the bare minimum for CE and we highly recommend much more, at least 500GB if you have it. 

Your case is a little faster than what I was seeing with 3.3.0 so I will look into it (some VM variables can cause rapid consumption) - however, it is not totally outside the bounds of what we've seen in previous releases.

You cannot add storage on the fly in CE, however you can run `ecsremove purge-nodes` to destroy the storage, remove the old disk, add a new, larger disk, and then redeploy with `step1` and `step2`

**Comment by bentoisoucy** [comment]
Ok thanks so even with only 6 pdfs of 500k the ECS can fill the 100 gig ?  I will check next week, if it does, I you're deploy a new VM with a bigger disk
thanks

**Comment by captntuttle** [comment]
Unfortunately, yes. Production ECS is designed to have access to basically unlimited storage; 100GB is really nothing to it. 

However, the 3.3.0 release is brand new so I will investigate to be sure this is not misconfigured.
