### ISSUE TITLE
Centos OS support

### ISSUE THREAD

**Issue by doppiak** [EMCECS/ECS-CommunityEdition#472]
### Actual Behavior
(Please put additional output and logs in the section for that below)

When I execute ./bootstrap.sh -y -g -c deploy.yml on a Centos 7.3.1611 distro, I get an error message: OS not supported.

Which Centos version is supported by ECS?

### Steps to Reproduce Behavior

1. use a Centos OS 7.3.1611

### Relevant Output and Logs
```
# Output and Logs go here
```

> 
>  ECS Community Edition Install Node Bootstrap 2.9.1r
>  ECS Software Image emccorp/ecs-software-3.3.0:3.3.0.0
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> Escalating privileges
>     You may be presented with the system sudo banner and asked
>     for your password depending on the Linux flavor and default
>     sudo configuration for your system.
> 
[sudo] password for flytogether: 
> 
> ERROR: OS unknown and not supported: centos linux release 7.3.1611 (core) 

---
Notifies: @captntuttle

**Comment by laszlolaszlo** [comment]
Hello,
As I saw in bootstrap_plugins/os-router.plugin.sh file. CentOS 7.3 is not supported but from CentOS 7.4 to 7.8.
CentOS 7.3 is a little bit old so try to use minimum 7.4 or the latest if possible.

**Comment by padthaitofuhot** [comment]
As soon as we release 3.5.1.2 it will support CentOS 7.9.
