### ISSUE TITLE
ECS CE 3.3.0 ova-step1 fails on cache.torrent

### ISSUE THREAD

**Issue by daitam** [EMCECS/ECS-CommunityEdition#473]
### Expected Behavior
ECS CE 3.3.0 is deployed.

### Actual Behavior
ova-step1 fails with Ansible error.

### Steps to Reproduce Behavior

1. run `ova-step1` from command line
2.
3.

### Relevant Output and Logs
```
TASK [common_sync_caches_by_torrent : Common | Copy cache torrent digest to nodes] *******************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/var/cache/emc/ecs-install/cache.torrent'
fatal: [1.2.3.4]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find or access '/var/cache/emc/ecs-install/cache.torrent'"}
```

Using OVA: [dellemc-ecsce-3.3.0.0-install-node-2.9.1-vm0.ova](http://131118670375936839.public.ecstestdrive.com/public/dellemc-ecsce-3.3.0-install-node-rc2.ova)

---
Notifies: @captntuttle

**Comment by jrosenth** [comment]
Same here.  Any workaround ???

**Comment by captntuttle** [comment]
Looks like i screwed up the OVA and didn't get the caches right. I'll have to redo it. If you have internet access you can get around it. If you're deploying in island you're probably suck until I can fix it.

**Comment by daitam** [comment]
@captntuttle Yes, it's an island. Thanks for the quick reply, waiting for the fix.

**Comment by jrosenth** [comment]
What's the workaround ?  I have inet access.
Thnx

**Comment by captntuttle** [comment]
In that case you ought to be able to just run step1 instead of ova-step1. If you are following the instructions in the docs just follow the ones for normal deploy instead of ova deploy and it should work no problem

**Comment by daitam** [comment]
@captntuttle I've found a way to solve this. OVA image is missing `ova.fact` file from `/etc/ansible/facts.d`. After adding it to OVA image the `ova-step1` went smoothly.

I took `ova.fact` contents from ECS CE 3.2.2:
```
#!/usr/bin/env bash
echo "{
    \"ova\": true
}"
```

**Comment by captntuttle** [comment]
Wonderful! Thanks a million @daitam! I apologize I wasn't able to get to this sooner, I have been slammed this week. I will add this to the currant OVA.

**Comment by LucasGhost** [comment]
Hi guys, i had same issue, i created ova.fact file as @daitam proposed and indeed moved on from "Copy cache torrent digest to nodes" section.

But then i received this error: 

```
> fatal: [10.1.95.16]: FAILED! => {"changed": true, "cmd": "aria2c --file-allocation=trunc -T /var/cache/emc/ecs-install/cache.torrent --bt-tracker-connect-timeout=1 --bt-tracker-interval=1 --bt-tracker-timeout=2 --listen-port=6883-6999 --enable-dht=true --dht-entry-point=10.1.95.51:6882 --dht-message-timeout=2 --dht-listen-port=6882 --seed-time=0 --allow-overwrite=true --check-integrity --bt-enable-lpd=false && touch /var/cache/emc/ecs-install/cache_control.sem", "delta": "0:00:00.007445", "end": "2019-05-13 16:50:10.089452", "failed": true, "msg": "non-zero return code", "rc": 127, "start": "2019-05-13 16:50:10.082007", "stderr": "/bin/sh: aria2c: command not found", "stderr_lines": ["/bin/sh: aria2c: command not found"], "stdout": "", "stdout_lines": []}
> fatal: [10.1.95.18]: FAILED! => {"changed": true, "cmd": "aria2c --file-allocation=trunc -T /var/cache/emc/ecs-install/cache.torrent --bt-tracker-connect-timeout=1 --bt-tracker-interval=1 --bt-tracker-timeout=2 --listen-port=6883-6999 --enable-dht=true --dht-entry-point=10.1.95.51:6882 --dht-message-timeout=2 --dht-listen-port=6882 --seed-time=0 --allow-overwrite=true --check-integrity --bt-enable-lpd=false && touch /var/cache/emc/ecs-install/cache_control.sem", "delta": "0:00:00.004916", "end": "2019-05-13 16:50:10.150914", "failed": true, "msg": "non-zero return code", "rc": 127, "start": "2019-05-13 16:50:10.145998", "stderr": "/bin/sh: aria2c: command not found", "stderr_lines": ["/bin/sh: aria2c: command not found"], "stdout": "", "stdout_lines": []}
> fatal: [10.1.95.17]: FAILED! => {"changed": true, "cmd": "aria2c --file-allocation=trunc -T /var/cache/emc/ecs-install/cache.torrent --bt-tracker-connect-timeout=1 --bt-tracker-interval=1 --bt-tracker-timeout=2 --listen-port=6883-6999 --enable-dht=true --dht-entry-point=10.1.95.51:6882 --dht-message-timeout=2 --dht-listen-port=6882 --seed-time=0 --allow-overwrite=true --check-integrity --bt-enable-lpd=false && touch /var/cache/emc/ecs-install/cache_control.sem", "delta": "0:00:00.005290", "end": "2019-05-13 16:50:10.154636", "failed": true, "msg": "non-zero return code", "rc": 127, "start": "2019-05-13 16:50:10.149346", "stderr": "/bin/sh: aria2c: command not found", "stderr_lines": ["/bin/sh: aria2c: command not found"], "stdout": "", "stdout_lines": []}
> fatal: [10.1.95.19]: FAILED! => {"changed": true, "cmd": "aria2c --file-allocation=trunc -T /var/cache/emc/ecs-install/cache.torrent --bt-tracker-connect-timeout=1 --bt-tracker-interval=1 --bt-tracker-timeout=2 --listen-port=6883-6999 --enable-dht=true --dht-entry-point=10.1.95.51:6882 --dht-message-timeout=2 --dht-listen-port=6882 --seed-time=0 --allow-overwrite=true --check-integrity --bt-enable-lpd=false && touch /var/cache/emc/ecs-install/cache_control.sem", "delta": "0:00:00.005257", "end": "2019-05-13 16:50:10.213838", "failed": true, "msg": "non-zero return code", "rc": 127, "start": "2019-05-13 16:50:10.208581", "stderr": "/bin/sh: aria2c: command not found", "stderr_lines": ["/bin/sh: aria2c: command not found"], "stdout": "", "stdout_lines": []}
```

any ideas appreciated. 

@daitam -- i also try to connect my ova to internet, and just try to run step1 instead of ova-step1, but i got same error. 

Thank you

**Comment by captntuttle** [comment]
@LucasGhost if you have already run step1 you cannot run it again. You will have to redeploy.

**Comment by daitam** [comment]
@LucasGhost looks like it cannot find `aria2c` command. Check the nodes if such executable is available. 

What is OVA image name that you use?

I've successfully deployed OVA in an isolated environment using RC3 [dellemc-ecsce-3.3.0-install-node-rc3.ova](http://131118670375936839.public.ecstestdrive.com/public/dellemc-ecsce-3.3.0-install-node-rc3.ova)

Link on the release page points to RC2 and I wasn't been able to deploy that one in my environment. I didn't try to use RC2 image after solving the `ova.fact` issue since everything works well with RC3 as far as I'm concerned. 

Maybe @captntuttle can comment on using the kinda unpublished RC3.

**Comment by captntuttle** [comment]
I'm working on a fixed ova release now. It will be up today or tomorrow. Apologies to all for this oversight.

I am removing the ova link from the release page. I will replace it with the new image when it is ready.

**Comment by LucasGhost** [comment]
@daitam - it was indeed RC2 version, i will try to deploy RC3 until new version release
@captntuttle - no worries, thanks for prompt replies.

**Comment by captntuttle** [comment]
New OVA is up. Will keep this issue open for a bit in case there are any more issues.

Sorry everyone and thank you for your patience.

**Comment by LucasGhost** [comment]
Thanks @captntuttle . I deployed new version, and i can see ova.fact file now is in ova, but i got still same error :(

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/var/cache/emc/ecs-install/cache.torrent'
fatal: [10.1.95.16]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find or access '/var/cache/emc/ecs-install/cache.torrent'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/var/cache/emc/ecs-install/cache.torrent'
fatal: [10.1.95.17]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find or access '/var/cache/emc/ecs-install/cache.torrent'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/var/cache/emc/ecs-install/cache.torrent'
fatal: [10.1.95.18]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find or access '/var/cache/emc/ecs-install/cache.torrent'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/var/cache/emc/ecs-install/cache.torrent'
fatal: [10.1.95.19]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find or access '/var/cache/emc/ecs-install/cache.torrent'"}
```

everything up to that point went smoothly.

thanks

**Comment by captntuttle** [comment]
@LucasGhost 

I can't seem to reproduce the error that you're seeing. Can you give me some details about your deployment?

**Comment by LucasGhost** [comment]
@captntuttle 

sure.

- OVA - your newest version: dellemc-ecsce-3.3.0-install-node.ova
- 4x Dell PowerEdge FC430; 2x Xeon E5-2620 2.1 GHz
- CentOS Linux release 7.6.1810 (Core)
- same subnet 
- no internet access.

thank you very much for your help.

**Comment by LucasGhost** [comment]
Hello guys,

just to give you some update, i decided to try standard installation (i managed to get inet access to my nodes). Everything went smoothly, until in step1 i get same error as mentioned in #452 

PLAY [Common | Ping data nodes before doing anything else] ***********************************************************************************************************```
************************************************************************************************************
 [WARNING]: error in 'jsonfile' cache plugin while trying to read /var/cache/emc/ecs-install/facts/10.1.95.16 : Expecting value: line 1 column 1 (char 0). Most likely a corrupt file, so erasing and failing.

ERROR! Error while decoding the cache file /var/cache/emc/ecs-install/facts/10.1.95.16: The cache file /var/cache/emc/ecs-install/facts/10.1.95.16 was corrupt, or did not otherwise contain valid data. It has been removed, so you can re-run your command now.
Operation failed.
```

**Comment by daitam** [comment]
@captntuttle Just to confirm - I've successfully deployed ECS 3.3 CE in isolated environment using the updated OVA image without any issues. Thanks.

**Comment by daydrim** [comment]
Hello I've found this issue again in 1 install node + 4 data nodes island installation environment Release 3.6.0.1
Temporary resolved replacing `ova-step1` to `step1` instead

**Comment by russfellows** [comment]
Yup, excact same problem and resolution for me.  Looks like this code hasn't been touched in 2+ years?  
My Environment:
- 4 data nodes + 1 install node
- Using OVA image (since it seems more controlled)
- Have internet connectivity

Problem:
- Error with cache.torrent running "ova-step1"

Resolution:
- Run "step1" instead
