### ISSUE TITLE
OVAs don't contain default requirments

### ISSUE THREAD

**Issue by willnx** [EMCECS/ECS-CommunityEdition#474]
### Expected Behavior
An OVA should work _out of the box._ User's should not be expected to deploy an OVA, then configure it with more RAM/disk. 

### Actual Behavior
After deploying the 3.2.2.0 OVA, the install fails at step 4 with the following:
```
TASK [common_baseline_check : Common | Check RAM size] **********************************************************************************************************************************************
fatal: [192.168.1.170]: FAILED! => {"changed": false, "failed": true, "msg": "Total RAM available for ECS is less than 15500MB (1830MB reported by node)"}

PLAY RECAP ******************************************************************************************************************************************************************************************
192.168.1.170              : ok=6    changed=0    unreachable=0    failed=1

Playbook run took 0 days, 0 hours, 0 minutes, 2 seconds
Operation failed.
```
After that, I checked for the other "hardware" requirement of a 100GB disk, and ~saw there's only a boot disk in the OVA~ *edit* - I'm a derp on this one; I used `df` instead of looking at `/dev`.

### Steps to Reproduce Behavior

1. Deploy OVA
2. Make no "hardware" changes
3. Start following the _setup ECS_ directions

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @captntuttle

**Comment by LucasGhost** [comment]
I didn't get this error in version 3.3.0 [rc2//rc3//final]] so i think this is fixed already.

**Comment by willnx** [comment]
@LucasGhost Good call! I just downloaded the [new OVA](http://131118670375936839.public.ecstestdrive.com/public/dellemc-ecsce-3.3.0-install-node.ova) and checked the config of the `.ovf`; looks good! Sorry for wasting some of your time. I'll close this issue.
