### ISSUE TITLE
Java install required to run JASScript on Community Edition? Is this supported?

### ISSUE THREAD

**Issue by lylemiller** [EMCECS/ECS-CommunityEdition#477]
### Actual Behavior
(Please put additional output and logs in the section for that below)

### Steps to Reproduce Behavior

1.
2.
3.

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @captntuttle

**Comment by captntuttle** [comment]
There should be no reason that you can't install Java.
