### ISSUE TITLE
Does AWS STS work with ECS?

### ISSUE THREAD

**Issue by thomaslange24** [EMCECS/ECS-CommunityEdition#478]
Hi, does ECS also support creating temporary security credentials with AWS STS and Assume Role? 
What i want to do is address the storage from a web app running in the browser on the client side. But i don't want to share the longterm credentials for that. Instead i want to use AWS STS to create temporary credentials on server side and pass those to the client. And since it is not so easy to do a multipart upload using presigned urls i think using STS is the best way. Or do you reccomend another way to do so without sharing longterm credentials?

**Comment by captntuttle** [comment]
https://github.com/EMCECS/ecs-samples/issues/26
