### ISSUE TITLE
Error 1008 Duplicate Namespace on rebuilt ECS using deploy.yml

### ISSUE THREAD

**Issue by zeffery** [EMCECS/ECS-CommunityEdition#479]
### Expected Behavior
Trying to re-create a bucket on an ECS that was rebuilt using deploy.yml file. The deploy.yml did not contain any info on the prior namespaces or buckets. 

### Actual Behavior
ECS has no existing buckets. Try to recreate bucket using UI and receive 'Error 1008 (http: 400): Invalid parameter. Duplicate found: mynamepsacename.mybucketname'
Attempt to delete the namespace and receive message that namespace can not be deletes as buckets exist. However no buckets are displayed in the UI.

So either 1. The buckets exist and are not displayed in the UI or 
               2. The buckets do not exist and something is preventing them from being created.

### Steps to Reproduce Behavior

1.Rebuild an ECS using deploy.yml
2.check no namespaces on the rebuilt ECS
3.Attempt to add the namespace and receive error

### Relevant Output and Logs
```
please tell me what logs to add

# Output and Logs go here
```
please tell me what logs to add

---
Notifies: @captntuttle

**Comment by captntuttle** [comment]
@zeffery 

What do you mean by "rebuilt?" Step1 and step2 should never be run more than one time. However, it is easy to repave the CE deployment if the data can be thrown away. This can be done by running `ecsremove purge-nodes` *NOTE* this will permanently destroy _all_ data on the ECS CE instance. 

After running `ecsremove` step1 and step2 can be re-run without changing the deploy.yml and should not yield any errors.

**Comment by zeffery** [comment]
By ‘rebuilt’ I mean the ECS was destroyed and a new one created using the existing deploy.yml file.
The creation of the new ECS worked fine except I cannot create buckets with the same names that previously existed.
I believe there is a issue with the UI not displaying the old buckets after a re-deploy of the ECS.
Since the error said the buckets already existed I tried copying data into the buckets using ECS-Sync which was successful.
I then went back into the UI and the buckets now display in the UI list of buckets as well as the UI Metering page.

**Comment by captntuttle** [comment]
Apologies, I thought for sure that I responded to this earlier... Perhaps I forgot to submit my comment.

If the ECS CE deployment has been truly destroyed and the disks wiped I don't know how the namespace/bucket etc can persist. How was the ECS destroyed? Can you describe the method used?

If you believe the UI is erroring by not showing you buckets and namespaces that actually do exist you can try using something like S3Browser, Cyberduck, or curl.

**Comment by zeffery** [comment]
I used ecs-sync to populate the empty buckets and they now appear in the UI buckets list page and metering pages.
This appears to be something related to the UI.

**Comment by padthaitofuhot** [comment]
When `ecsremove` is run, nothing of the previous ECS deployment should remain, including the UI.  Does this issue continue with the latest release?

**Comment by nikhil-vr** [comment]
closing as older
