### ISSUE TITLE
EMC-ECS Step2 fails

### ISSUE THREAD

**Issue by SivaKaviyappa** [EMCECS/ECS-CommunityEdition#481]
### Expected Behavior
Step2 should complete during installation and all services should be up.

### Actual Behavior
(Please put additional output and logs in the section for that below)

### Steps to Reproduce Behavior

1.bootstrap
2.step1
3.step2

### Relevant Output and Logs
```
# Output and Logs go here
```
UG:root:'members'
DEBUG:root:====================str====================
DEBUG:root:====================str====================
DEBUG:root:'sp1'
DEBUG:root:====================str====================
DEBUG:root:ECSConf: get_sp_options
DEBUG:root:ECSConf: get_defaults
DEBUG:root:ECSConf: get_attr
DEBUG:root:====================str====================
DEBUG:root:'storage_pools'
DEBUG:root:====================str====================
DEBUG:root:====================str====================
DEBUG:root:'options'
DEBUG:root:====================str====================
DEBUG:root:====================str====================
DEBUG:root:'sp1'
DEBUG:root:====================str====================
INFO:ecsclient.common.provisioning.node:Getting all nodes for cluster
DEBUG:ecsclient.baseclient:Constructed URL as: https://172.31.35.11:4443/vdc/nodes
DEBUG:ecsclient.common.token_request:Validating token
DEBUG:urllib3.connectionpool:https://172.31.35.11:4443 "GET /user/whoami HTTP/1.1" 200 None
DEBUG:ecsclient.common.token_request:Token validated successfully
DEBUG:urllib3.connectionpool:https://172.31.35.11:4443 "GET /vdc/nodes HTTP/1.1" 200 None
INFO:ecsclient.common.provisioning.data_store:Creating data store '172.31.35.11': {'nodes': [{'nodeId': u'1ff1bb3e-c346-11e9-b85d-0eb6a78a1768', 'name': '172.31.35.11', 'virtual_array': u'urn:storageos:VirtualArray:964a733c-5837-4de2-aa62-fc79bf16df41', 'description': 'My First SP'}]}
DEBUG:ecsclient.baseclient:Constructed URL as: https://172.31.35.11:4443/vdc/data-stores/commodity
DEBUG:ecsclient.common.token_request:Validating token
DEBUG:urllib3.connectionpool:https://172.31.35.11:4443 "GET /user/whoami HTTP/1.1" 200 None
DEBUG:ecsclient.common.token_request:Token validated successfully
DEBUG:urllib3.connectionpool:https://172.31.35.11:4443 "POST /vdc/data-stores/commodity HTTP/1.1" 400 None
ERROR:ecsclient.baseclient:Status code NOT OK

> Pinging Management API Endpoint until ready
> Pinging endpoint 172.31.35.11... (CTRL-C to break)
> PONG: api_endpoint=172.31.35.11 username=root diag_endpoint=172.31.35.11 dt_total=0 dt_unready=0 dt_unknown=0

> Creating Storage Pool: vdc1/sp1
>       OK
> Adding Data Stores to Storage Pool:
>       vdc1/sp1/172.31.35.11
Traceback (most recent call last):
  File "/usr/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.9.1.post0', 'console_scripts', 'ecsconfig')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/ecsconfig.py", line 661, in sp
    tasks = add_all()
  File "/usr/bin/ecsconfig.py", line 637, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/bin/ecsconfig.py", line 629, in add_one
    sp_tasks.append(sp_add_node(sp_id, node))
  File "/usr/bin/ecsconfig.py", line 606, in sp_add_node
    return conf.api_client.data_store.create(**kwargs)
  File "/usr/lib/python2.7/site-packages/ecsclient/common/provisioning/data_store.py", line 217, in create
    return self.conn.post('vdc/data-stores/commodity', json_payload=payload)
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Error while registering 1 commodity node(s) - Bad request body: https://172.31.35.11:4443/vdc/data-stores/commodity 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo

---
Notifies: @captntuttle

**Comment by captntuttle** [comment]
This has been an elusive issue that I have been trying to track down for some time, but is becoming more regular. I'm looking into it.

**Comment by SivaKaviyappa** [comment]
Thanks for looking into it. We were able to work around by using older version of ecs and ec2 ami  version.

**Comment by kedmon** [comment]
@SivaKaviyappa, which version worked for you?  We are having similar difficulty.

**Comment by SivaKaviyappa** [comment]
@kedmon emccorp/ecs-software-3.2.2
