### ISSUE TITLE
Update to 3.4.0

### ISSUE THREAD

**Issue by twincitiesguy** [EMCECS/ECS-CommunityEdition#484]
We now have a GA candidate build for ECS 3.4.  We should start the process of creating a Community Edition release built on top of this version.

**Comment by twincitiesguy** [comment]
Let's shoot for 9/30 release.

**Comment by holgerjakob** [comment]
Hi all
Any update on this?

It would be great to be able to test our ECS monitoring and managed service that is based on the rest api. In order to be able to validate the api calls and their output as we've already customers that upgraded to 3.4.

Thanks a lot, Holger

**Comment by captntuttle** [comment]
Released.
