### ISSUE TITLE
ECS OVA installation failure

### ISSUE THREAD

**Issue by Vikneshkumar-Thirumoorthy** [EMCECS/ECS-CommunityEdition#488]
I'm facing issues while trying to install ECS through OVA. The installation fails while trying to deploy the ECS nodes(ova-step1)

Whenever it tries to do an SSH from the base machine to the node servers it not able to communicate.

But while trying to do SSH manually to the node machines, everything seems to work fine without any issues.

Environment Details:

ECS Version - Community Edition 2.9.1 (ECS - 3.3.0.0)

Base Machine : OS - Centos 7.6

Node 1: Windows Server 2012 R2

Node 2: Windows Server 2012 R2

Also, while running ova-step1 does the user information is obtained from deploy.yml file or is it stored somewhere else?

Error Message:

fatal: [10.88.13.15]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo $HOME/.ansible/tmp/ansible-tmp-1571354921.18-107380414822406 `\" && echo ansible-tmp-1571354921.18-107380414822406=\"` echo $HOME/.ansible/tmp/ansible-tmp-1571354921.18-107380414822406 `\" ), exited with result 1", "unreachable": true}
fatal: [10.88.13.14]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo $HOME/.ansible/tmp/ansible-tmp-1571354921.18-202715120194950 `\" && echo ansible-tmp-1571354921.18-202715120194950=\"` echo $HOME/.ansible/tmp/ansible-tmp-1571354921.18-202715120194950 `\" ), exited with result 1", "unreachable": true}

Thanks

Viknesh

**Comment by captntuttle** [comment]
@Vikneshkumar-Thirumoorthy 

It looks like you are trying to deploy to 2 windows server nodes? All nodes must be CentOS minimal installs

**Comment by Vikneshkumar-Thirumoorthy** [comment]
Thanks Ken.

I was able to figure that out. Is there any way to delete individual file content from storage bucket. I’m able to clear the entire bucket. But I don’t know how to delete individual content in a bucket.

Thanks
Vik

Sent from my iPhone

On Nov 4, 2019, at 4:44 PM, Ken Steinfeldt <notifications@github.com<mailto:notifications@github.com>> wrote:


@Vikneshkumar-Thirumoorthy<https://github.com/Vikneshkumar-Thirumoorthy>

It looks like you are trying to deploy to 2 windows server nodes? All nodes must be CentOS minimal installs

**Comment by captntuttle** [comment]
Yes, you just need to do a DELETE call on the object. See https://www.emc.com/techpubs/api/ecs/v3-0-0-0/UserManagementService_b2081f90369a6d96de7811240fd3b244_overview.htm for API references. If you are using an SDK there should be a delete function all for objects.
