### ISSUE TITLE
OS unknown and not supported: centos 8.0.1905 (core) - is the OS supported? 

### ISSUE THREAD

**Issue by grahamck** [EMCECS/ECS-CommunityEdition#491]
### Expected Behavior
Trying to install on a VM running Centos 8.0.1905. 

This error is displayed by bootstrap.sh:

ERROR: OS unknown and not supported: centos linux release 8.0.1905 (core)

### Actual Behavior

bootstrap seems to indicate the latest version of centos is not supported. 

### Steps to Reproduce Behavior
# ./bootstrap.sh -y -g -c deploy.yml

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @captntuttle

**Comment by captntuttle** [comment]
CentOS 8 is not yet supported. But the latest version of 7 is.
