### ISSUE TITLE
Ansible Task sync_caches_by_torrent hangs indefinitely

### ISSUE THREAD

**Issue by AB442** [EMCECS/ECS-CommunityEdition#494]
### Expected Behavior

The expected behavior is that ECS install step 1 executes in full, allowing the subsequent install procedures to follow.

### Actual Behavior
(Please put additional output and logs in the section for that below)

The sync_caches_by_torrent task within step1 does not execute, instead it hangs without any output.

I have followed the install steps in the documentation for a Multi-node install. I am currently manually debugging the aria2c component of the task, and receiving a "connection refused" error, leading me to believe that this could be due to blocked ports, however I have already opened ports 6881-6999 on UDP for all ECS node VMs as well as the install node.

I also noticed the task 'sync_caches_by_copy', and attempted to have the playbook use this one as an alternative, to no avail. Unsure if this is a viable solution.

The issue persists on both the OVA and Island install versions.

Assistance/workarounds would be appreciated.

### Steps to Reproduce Behavior

1. Follow documentation steps at: https://github.com/EMCECS/ECS-CommunityEdition/blob/master/docs/source/installation/ECS-Installation.md
2. Run the first step with ./step1
3. Run the bootstrapper with ./bootstrap.sh -y -g -c deploy.yml

### Relevant Output and Logs
```
terminal output of the Ansible play

# Output and Logs go here
```
PLAY [Installer | Slice nodes into OS groups for package install] *********************************************************

TASK [group_by] ***********************************************************************************************************
ok: [10.x.x.63]
ok: [10.x.x.62]
ok: [10.x.x.64]

PLAY [CentOS 7 | Synchronize cache] ***************************************************************************************

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Fetch torrent package names] *************************************************
changed: [10.x.x.63 -> 10.x.x.61]
changed: [10.x.x.64 -> 10.x.x.61]
changed: [10.x.x.62 -> 10.x.x.61]

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Make yum cache paths for torrent packages] ***********************************
changed: [10.x.x.63] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
changed: [10.x.x.64] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
changed: [10.x.x.62] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
changed: [10.x.x.63] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
changed: [10.x.x.64] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
changed: [10.x.x.62] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Copy torrent packages to nodes] **********************************************
ok: [10.x.x.64] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
ok: [10.x.x.63] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
ok: [10.x.x.62] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
ok: [10.x.x.64] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
ok: [10.x.x.63] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
ok: [10.x.x.62] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Install torrent packages on nodes] *******************************************
ok: [10.x.x.64] => (item=[u'/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm', u'/var/cache/yum/x86_64/7/epel/packages/aria2-1.34.0-5.el7.x86_64.rpm'])
ok: [10.x.x.63] => (item=[u'/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm', u'/var/cache/yum/x86_64/7/epel/packages/aria2-1.34.0-5.el7.x86_64.rpm'])
ok: [10.x.x.62] => (item=[u'/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm', u'/var/cache/yum/x86_64/7/epel/packages/aria2-1.34.0-5.el7.x86_64.rpm'])

TASK [common_sync_caches_by_torrent : include_vars] ***********************************************************************
ok: [10.x.x.63]
ok: [10.x.x.62]
ok: [10.x.x.64]

TASK [common_sync_caches_by_torrent : Selinux | Set selinux permissive] ***************************************************
ok: [10.x.x.64]
ok: [10.x.x.63]
ok: [10.x.x.62]

TASK [common_sync_caches_by_torrent : Common | Create ecs-install host directory on nodes] ********************************
ok: [10.x.x.63]
ok: [10.x.x.64]
ok: [10.x.x.62]

TASK [common_sync_caches_by_torrent : Common | Create ecs-install cache directory on nodes] *******************************
ok: [10.x.x.64]
ok: [10.x.x.63]
ok: [10.x.x.62]

TASK [common_sync_caches_by_torrent : Common | Copy cache torrent digest to nodes] ****************************************
ok: [10.x.x.63]
ok: [10.x.x.64]
ok: [10.x.x.62]

TASK [common_sync_caches_by_torrent : Common | Torrent sync caches with nodes] ********************************************

---
Notifies: @captntuttle

**Comment by AB442** [comment]
I was unable to solve the above issue, however I located a workaround using the "sync_caches_by_copy" task. The reason that I was having trouble switching to 'sync_caches_by_copy' was due to my not using the 'update_images' script to push the changes I was making in the ansible scripts to the docker images.

**Comment by captntuttle** [comment]
Thanks for the notes @AB442 I will investigate.
