### ISSUE TITLE
3.4.0 OVA Advanced Monitoring - Error opening Grafana page 

### ISSUE THREAD

**Issue by psergiu** [EMCECS/ECS-CommunityEdition#496]
### Expected Behavior
3.4.0.0 OVA 4 node install.
Click on Advanced Monitoring
Expected: See Advanced Monitoring in all it's glory

### Actual Behavior
Actual result - red band with error:

 Error opening Grafana page 

### Steps to Reproduce Behavior

1. Login to ECS as admin1
2. Click on Advanced Monitoring
3. admire error

### Relevant Output and Logs

No idea from where to collect logs - will provide if told.
:9101/greplog/ page fails with:

Error while executing script: 
 Cleaning up older output files
Grepping logs @ /opt/storageos/logs
/opt/storageos/logs /
Grep output @ /greplogs_output.grep
mkdir: cannot create directory '/greplogs_output.grep': Permission denied

Thank you !
---
Notifies: @captntuttle

**Comment by captntuttle** [comment]
> admire error 
😂 
sorry for the late notice @psergiu - advanced monitoring is not supported on CE
