### ISSUE TITLE
ntpd fails everytime on ova-step1, no matter the version

### ISSUE THREAD

**Issue by Lupi619** [EMCECS/ECS-CommunityEdition#497]
### Expected Behavior
ova-step1 to complete successfully

### Actual Behavior
RUNNING HANDLER [CentOS_7_baseline_install : CentOS 7 | Set the clock] *********
fatal: [192.168.73.52]: FAILED! => {"changed": true, "cmd": ["ntpd", "-gq"], "de                                                                                                                     lta": "0:00:11.007236", "end": "2019-11-19 20:14:12.196404", "failed": true, "ms                                                                                                                     g": "non-zero return code", "rc": 1, "start": "2019-11-19 20:14:01.189168", "std                                                                                                                     err": "", "stderr_lines": [], "stdout": "ntpd: no servers found", "stdout_lines"                                                                                                                     : ["ntpd: no servers found"]}

### Steps to Reproduce Behavior

1. videploy
2. ova-step1
3.

### Relevant Output and Logs
```
# Output and Logs go here
```
This happens the first time I run the step1 everytime no matter the ECS version.  When the ova is first deployed the chrony service is started so that needs to be disbaled and then ntp needs to be enabled.  However even if the ntp service is up and running and updating the time correctly it still gets this error.  Has anyone else seen this or experienced this?  

---
Notifies: @captntuttle

**Comment by captntuttle** [comment]
@Lupi619 have you confirmed that there is a valid ntp server at the endpoint you define in the bootstrap.yml file?
