### ISSUE TITLE
Postman - Error 10001 (http: 401): An error occurred while encoding/decoding of tokens. Unable to decode token

### ISSUE THREAD

**Issue by munishase** [EMCECS/ECS-CommunityEdition#500]
I am facing same issue. I am able to login to portal successfully, but when calling same api with postman then facing below resultset. even I am sending same request as it is with portal, I observer network calls as well.
{
"status": "error",
"messageKey": "ns.msg.query.list.failed",
"msgDetails": "Error 10001 (http: 401): An error occurred while encoding/decoding of tokens. Unable to decode token.",
"isSuccess": false,
"isError": true
}

**Comment by captntuttle** [comment]
Can you fill me in on the request you were making? What was the workflow? etc.

**Comment by munishase** [comment]
I am calling the APIs with postman. The login api works returns a token successfully. but no other api is working. below is one sample request of postman curl code.

**Request:**
curl -X POST \
  https://xx.xxx.xxx.xx/namespaces \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Basic YXNlYXBpPLMhc3Q3PLOkXCIz' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Cookie: X-SDS-PORTAL-AUTH-TOKEN=; XSRF-TOKEN=; X-SDS-AUTH-TOKEN=' \
  -H 'Host: 10.192.233.18' \
  -H 'Postman-Token: 91c78592-7fef-45b1-ae42-b8b8b787a70b,19990e9a-4cfe-4727-82c5-f965975e30be' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'X-SDS-AUTH-TOKEN: BAAcdUYwPPPiZnNYNUQ0dnVSd2w1RFNSbVBjcWRvPQMAjAQASHVybjpzdG9yYWdlb3M6VmlydHVhbERhdGGGGG50ZXJEYXRhOjdjOGUzNjVhLTlmY2UtNDU1Mi1iMTNiLWY4NjYzY2M4M2Q0NQIADTE1NzU4MTY1IIIxMjQDAC51cm46VG9rZW46AAA0ZjRkNzQtZDk2Zi00ZmE1LThmMGYtMjdiNmM5ZDI0OWM1WgAC0A8=' \
  -H 'X-XSRF-TOKEN: 1b4cd6a9545246841f30071e02702724' \
  -H 'cache-control: no-cache'


**Response**

{
    "status": "error",
    "messageKey": "ns.msg.query.list.failed",
    "msgDetails": "Error 10001 (http: 401): An error occurred while encoding/decoding of tokens. Unable to decode token.",
    "isSuccess": false,
    "isError": true
}

**Comment by captntuttle** [comment]
the X-XSRF-TOKEN is only necessary for the Portal calls so i'm a little confused. If these are management calls they need to be directed at the :4443 port and only require the X-SDS-AUTH token

**Comment by munishase** [comment]
I changed it with below request. but response is same.

curl -X POST \
  https://10.192.233.18/namespaces \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Cookie: X-SDS-PORTAL-AUTH-TOKEN=; XSRF-TOKEN=; X-SDS-AUTH-TOKEN=; ECSUI_ERRORS=; ECSUI_SESSION=; ECSUI_FLASH=' \
  -H 'Host: 10.192.233.18' \
  -H 'Postman-Token: 4d12b6c1-93f1-4cb8-b534-296f32d2d20b,438b4ee6-e173-475d-bf48-f272f367c858' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'X-XSRF-TOKEN: 1b4cd6a9545246841f30071e02702724' \
  -H 'cache-control: no-cache'

**Comment by munishase** [comment]
I observe network traffic from portal browser and observe the api it is trying to call internally. Then I am calling same APIs from postman but it is giving the said error. Don't know the reason?

**Comment by captntuttle** [comment]
yes, you do not need the cookie or other token. send a basic auth request to `/login` at the port `:4443` with just the X-SDS-AUTH-TOKEN in the header

**Comment by munishase** [comment]
As I explained earlier, I am able to generate auth token with below request

curl -X GET \
  https://xx.xxx.xxx.xx/login \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Basic YPLMlYXBpOlBhc3E3MHJkMTIz' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: XSRF-TOKEN=9827e76e05086dc24f7d8b4149281202; ECSUI_ERRORS=' \
  -H 'Host: 10.192.233.11' \
  -H 'Postman-Token: 49a99ba9-8aa4-4b87-b1b7-227eb67eb0c9,7a088c26-d7ec-425a-8df4-028667772c94' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache'


But other request like 
/namespace
/user/list
nothing is working?

**Comment by captntuttle** [comment]
Are you adding `:4443` to the url?

**Comment by munishase** [comment]
if I add :4443 then it says

<?xml version="1.0" encoding="UTF-8"?>
<error>
    <code>6404</code>
    <description>Not Found.</description>
    <details>The resource you requested was not found.</details>
    <retryable>false</retryable>
</error>

**Comment by captntuttle** [comment]
to list namespaces the route is /object/namespaces.

here is the api manual with all the endpoints https://www.emc.com/techpubs/api/ecs/v3-0-0-0/NamespaceService_2ba4e9e849ddf069c429466d38709f38_overview.htm 

please let me know if you continue to have issues.

**Comment by munishase** [comment]
I updated as below
**Request**

curl -X POST \
  https://xx.xxx.xxx.xx:4443/object/namespaces \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Basic YXNlYXBpOlBhc3N3MHJkMTIz' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Cookie: X-SDS-PORTAL-AUTH-TOKEN=; XSRF-TOKEN=; X-SDS-AUTH-TOKEN=' \
  -H 'Host: 10.192.233.18:4443' \
  -H 'Postman-Token: ba69dd81-4e43-42d6-a5a3-f0ddb0c76724,999b7c19-9456-4dd0-b02b-8de93d0fd430' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'X-XSRF-TOKEN: 1b4cd6a9545246841f30071e02702724' \
  -H 'cache-control: no-cache'

**Response**
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /object/namespaces. Reason:
<pre>    Non-GET unauthenticated request: authenticate using https://10.192.233.18:4443/login?service=https%3A%2F%2F10.192.233.18%3A4443%2Fobject%2Fnamespaces</pre></p>
</body>

**Comment by captntuttle** [comment]
login
```
GET /login HTTP/1.1
Host: root:ChangeMe@10.1.83.98:4443
X-Auth-User: object_admin1
X-Auth-key: ChangeMe
Authorization: Basic cm9vdDpDaGFuZ2VNZQ==
User-Agent: PostmanRuntime/7.20.1
Accept: */*
Cache-Control: no-cache
Postman-Token: 72494000-80a7-4de9-8cce-e41c6cb25b8e,ca3bd1ab-3ae5-4b97-a405-4f0487f8f1e4
Host: 10.1.83.98:4443
Accept-Encoding: gzip, deflate
Connection: keep-alive
cache-control: no-cache
```
list namespaces
```
GET /object/namespaces HTTP/1.1
Host: 10.1.83.98:4443
X-SDS-AUTH-TOKEN: BAAcdDBSeUlzUlRpUGlVbkNTaDRGTGpXU3ZGd0U4PQMAjAQASHVybjpzdG9yYWdlb3M6VmlydHVhbERhdGFDZW50ZXJEYXRhOmIyMmFmYjJiLThjMDctNDEwNC1hZmJhLWFmODZhOTRkZjZkNgIADTE1NzYwMTU4NzAzMjkDAC51cm46VG9rZW46OGZiZmFmNWMtMmEyOS00NTZlLWIyZmQtMWZhNTZlMzExMzA5AgAC0A8=
User-Agent: PostmanRuntime/7.20.1
Accept: */*
Cache-Control: no-cache
Postman-Token: cca7bdb1-278f-4bd3-959b-e4826c453cd9,90ca96db-6a1c-4f6e-8608-6e03582f7806
Host: 10.1.83.98:4443
Accept-Encoding: gzip, deflate
Connection: keep-alive
cache-control: no-cache
```
response
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<namespaces>
    <Filter>name=*</Filter>
    <namespace>
        <creation_time>1572647258073</creation_time>
        <id>ns1</id>
        <inactive>false</inactive>
        <link rel="self" href="/object/namespaces/namespace/ns1"/>
        <name>ns1</name>
        <default_bucket_block_size>-1</default_bucket_block_size>
        <blockSize>-1</blockSize>
        <is_compliance_enabled>false</is_compliance_enabled>
        <is_encryption_enabled>false</is_encryption_enabled>
        <is_stale_allowed>false</is_stale_allowed>
        <namespace_admins>root</namespace_admins>
        <retention_classes/>
        <notificationSize>-1</notificationSize>
        <default_data_services_vpool>urn:storageos:ReplicationGroupInfo:5ef61630-c721-4c17-b9d8-3b9f3b0835e9:global</default_data_services_vpool>
    </namespace>
</namespaces>
```

**Comment by munishase** [comment]
I really dont have any idea what is going on. when I call 
**Request**
curl -X GET \
  https://10.192.233.18:4443/login \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Basic YXNlYXBpOlBhc3N3MHJkMTIz' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: X-SDS-PORTAL-AUTH-TOKEN=; X-SDS-AUTH-TOKEN=; XSRF-TOKEN=681f63ede95bb58d285b14854f18f1a8' \
  -H 'Host: 10.192.233.18:4443' \
  -H 'Postman-Token: 3c5326f9-f81a-44e9-9a09-c0809e76774f,cf78e675-1885-4906-a958-874744ef890b' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache'

**Response**
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error>
    <code>10001</code>
    <description>An error occurred while encoding/decoding of tokens</description>
    <details>Unable to decode token.</details>
    <retryable>false</retryable>
</error>

**Comment by captntuttle** [comment]
https://10.192.233.18:4443/login -> returns X-SDS-AUTH-TOKEN
https://10.192.233.18/login -> returns XSRF-TOKEN

The issue with your request to 4443 _could_ be that you are including the cookie in the request. Try removing the cookie from the request to port 4443.

**Comment by munishase** [comment]
https://10.192.233.18:4443/login -> returns X-SDS-AUTH-TOKEN
I think this token is returned in header with key name X-SDS-AUTH-TOKEN

and 
https://10.192.233.18/login -> returns XSRF-TOKEN token is returned body with saying any key name.

I made changes and seems it started working. Thank you mate.

**Comment by captntuttle** [comment]
Glad to hear it's working! I'm going to close the issue. Feel free to open it back up if you feel otherwise.
