### ISSUE TITLE
Dell ECS APIs

### ISSUE THREAD

**Issue by munishase** [EMCECS/ECS-CommunityEdition#502]
Please help me by providing Dell ECS api for
- creating customer/tenants?
- S3 access key?
- Storage bucket?

Looking forward?

**Comment by holgerjakob** [comment]
Hi
I've used http://doc.isilon.com/ECS/3.3/API/ so far. 
The 3.4 in the help of the virtual ecs points to an internal website and I don't have access to a production one at the moment.

Best regards, Holger

**Comment by captntuttle** [comment]
@munishase the docs posted by @holgerjakob should get you what you need. Please let me know if not.
