### ISSUE TITLE
we have noticed file system utilization is almost reached on community edition and is anyway can clean up

### ISSUE THREAD

**Issue by DipindasThayyil** [EMCECS/ECS-CommunityEdition#508]
admin@luna uuid-9021b21d-ac84-46f3-ae38-a9f3a6a69c93]$ sudo docker exec -it  77c8c173e816  bash
luna:/ # df  -hh
Filesystem           Size  Used Avail Use% Mounted on
overlay               14G   11G  3.4G  75% /
tmpfs                 32G  4.0K   32G   1% /dev
tmpfs                 32G     0   32G   0% /sys/fs/cgroup
/dev/mapper/cl-root   14G   11G  3.4G  75% /etc
/dev/sdb1            1.0T 1011G   14G  99% /dae/uuid-9021b21d-ac84-46f3-ae38-a9f3a6a69c93
devtmpfs              32G     0   32G   0% /dev/random
shm                   64M     0   64M   0% /dev/shm
luna:/ # cd cd /dae/uuid-9021b21d-ac84-46f3-ae38-a9f3a6a69c93^C
luna:/ # cd /dae/uuid-9021b21d-ac84-46f3-ae38-a9f3a6a69c93
luna:/dae/uuid-9021b21d-ac84-46f3-ae38-a9f3a6a69c93 # ls
0000  0004  0008  0012  0016  0020  0024  0028  0032  0036  0040  0044  0048  0052  0056  0060  0064  0068  0072  0076  0080  0084  0088  0092  0096  0100
0001  0005  0009  0013  0017  0021  0025  0029  0033  0037  0041  0045  0049  0053  0057  0061  0065  0069  0073  0077  0081  0085  0089  0093  0097
0002  0006  0010  0014  0018  0022  0026  0030  0034  0038  0042  0046  0050  0054  0058  0062  0066  0070  0074  0078  0082  0086  0090  0094  0098
0003  0007  0011  0015  0019  0023  0027  0031  0035  0039  0043  0047  0051  0055  0059  0063  0067  0071  0075  0079  0083  0087  0091  0095  0099
luna:/dae/uuid-9021b21d-ac84-46f3-ae38-a9f3a6a69c93 # du -sh
1011G   .
luna:/dae/uuid-9021b21d-ac84-46f3-ae38-a9f3a6a69c93 #

**Comment by laszlolaszlo** [comment]
I have the same problem. We uploaded 2 GB file with S3 Browser and leaved the 4 node ECS cluster alone. Until one month all space is filled up with:
User Data: 2.20 GiB
System Metadata: 256.50 GiB
Protection Overhead: 334.00 GiB
Geo Copy: 9.62 GiB
Garbage: 18.05 GiB

Version: ECS Object Version 3.4.0.0.113609.ff7267c.0.2.bugfix_STORAGE_25556_TaskScheduler_3_4_ce_patch

**Comment by martin-duerre** [comment]
Hello, the problem persists with ECS CE 3.5.0.0.

**Comment by nikhil-vr** [comment]
Please try it with 3.7 build and report if issue persists , please re-open if persists.
