### ISSUE TITLE
Access is denied due to invalid or expired credentials

### ISSUE THREAD

**Issue by 1ranjanasingh** [EMCECS/ECS-CommunityEdition#509]
I am using Dell EMC ECS v3.4.0.0 all in one single node deployment.  I have created object users and buckets.  whenever I try to access using rest api or S3 api, I get access deny.

**Rest API error using postman:**
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error>
    <code>401</code>
    <description>Unauthorized</description>
    <details>Access is denied due to invalid or expired credentials</details>
</error>

**S3 API Error using Pivotal Ops Manager 2.8.3**
Access Denied for bucket 'f1-blobstore', type: BlobstoreVerifier

**Events on ECS**
User f1-object-user1 failed to login. Access is denied due to invalid or expired credentials 

I am using right object username and password.  Do I need to add certificate or token for authentication to work?
Notifies: @captntuttle

**Comment by nikhil-vr** [comment]
Please use the latest version and report if issue persists
