### ISSUE TITLE
Not able to upload any file to ECS community edition v3.2.2.0 through S3 browser

### ISSUE THREAD

**Issue by amitpanchal303** [EMCECS/ECS-CommunityEdition#510]
Not able to upload any file to ECS community edition v3.2.2.0, getting below through S3 browser, task is getting failed and i can see below error message in events.

Unable to write data to the transport connection: AN existing connection was forcible closed by remote host 
---
Notifies: @captntuttle

**Comment by nikhil-vr** [comment]
closing as an older , use the latest version and re-open if issue persists
