### ISSUE TITLE
Failed to initialize Directory Tables . ECS:3.0.0.1-legacy-final

### ISSUE THREAD

**Issue by shampavman** [EMCECS/ECS-CommunityEdition#511]
I"m trying to bring up a single node configuration of ECS.
I'm constantly seeing failure while executing step2

> ./step2_object_provisioning.py --ECSNodes=172.18.6.1 --Namespace=pNameSpace --ObjectVArray=pO
> VArray --ObjectVPool=pOBVpool --DataStoreName=pdatastore --VDCName=pvdc --UserName=puser
> ...
> ...
> Waiting on Directory Tables to Initialize...
> curl -s http://172.18.6.1:9101/stats/dt/DTInitStat
> Directory Tables 100.0% ready. (192 total 0 unready 0 unknown)
> Directory Tables 100.0% ready. (192 total 0 unready 0 unknown)
> <cut for brevity>
> **Directory Tables failed to initialize.**

After this, i see that the code  tries to get a secret key for the VDC but keeps failing 

> Executing REST API command: curl -s -k -X GET -H 'Content-Type:application/json'     -H 'X-SDS-AUTH-TOKEN: BAAcV1hWM2RXVUxDOHl1Q1VCK2RDaDVnVXhnV0dvPQMAjAQASHVybjpzdG9yYWdlb3M6VmlydHVhbERhdGFDZW50ZXJEYXRhOmY5Zjc3NTA3LWUwM2ItNDE4NC04ZjQ4LTNkOGMxZWIzOGJkNgIADTE1ODQwMDE2MzU0OTQDAC51cm46VG9rZW46MDY0N2U2MGEtMDk1Yy00ZDZmLWE5MjYtOWU5NzExM2E4NTZkAgAC0A8='     -H 'ACCEPT:application/json'      https://172.18.6.1:4443/object/vdcs/vdc/local/secretkey
> Method <function InsertVDC at 0x7f6d11741230> threw error 'key'
> Sleep for 60 seconds before retry
> 

This is retrying from almost 5 hrs. :)

I looked at the ssm.log and i keep seeing the following errors:

> 2020-03-12T15:37:37,624 [TaskScheduler-SSManager-ParallelExecutor-121-ac120601:170c8b43655:c24:4] ERROR  ChunkClientImpl.java (line 257) chunk creation failed 293dcbc6-b10b-4f2f-85b5-835bb50203b2, write context: [writerId: 172.18.6.1-1095-BPLUSTREE-BFW-1-writer-1, cos: urn:storageos:VirtualArray:aa3ea0fe-f51f-45f5-9ae7-c0cd80147255, level: 1, type: BPLUSTREE, skipChunkSequenceCounter: false, repoMergeChunkId: null], error com.emc.storageos.data.object.exception.ObjectControllerException: create chunk 293dcbc6-b10b-4f2f-85b5-835bb50203b2 failed, request id ac120601:170c8b43f3c:cc:2405, serverIp 172.18.6.1, status **ERROR_NO_SPACE sleep 5000 millis before retry**
> <cut for brevity>
> 2020-03-12T15:37:47,672 [SSStateMachinesHolder-000]  INFO  RoutingClientBase.java (line 753) Retry on failure - DT not initialized, request ac120601:170c8b43f3c:c7f:606, ip 172.18.6.1:1095, starting attempt# 12 requestId ac120601:170c8b43f3c:c7f:606, commandType REQUEST_CREATE_COMMODITY_DEVICE_TO_OWNER, to 172.18.6.1:1095

df -h output doesnt say there that i'm out of space
df -h
Filesystem       Size  Used Avail Use% Mounted on
/dev/emcpowera1   65G   44G   20G  70% /
tmpfs             64M   14M   51M  22% /dev
tmpfs             13G     0   13G   0% /sys/fs/cgroup
/dev/emcpowera1   65G   44G   20G  70% /dae
/dev/sdag1       100G   91G   10G  91% /dae/uuid-784bd840-2999-4fa0-b130-e00f71a5a2e3
devtmpfs          13G  8.0K   13G   1% /dev/random
/dev/emcpowera1   65G   44G   20G  70% /var/log
shm               64M     0   64M   0% /dev/shm
tmpfs             13G     0   13G   0% /run/secrets/credentials.d
tmpfs             13G     0   13G   0% /proc/scsi
tmpfs             13G     0   13G   0% /sys/firmware

I have no clue where this is taking it from.
Any help would be really put me on a good track. Can't seem to find out what the issue is for the might of me!

Some other details:
I have already tried with the latest ECS CE release as well, i was again hitting the error while creating a VDC.
the error i saw there was also similar:

> com.emc.storageos.data.object.exception.ObjectControllerException: **Can't find enough storage devices for 1 segments, [] devices blacklisted, [f443f12e-604c-11ea-abb4-0242c625ecd6] devices do not have capacity info**

So after finding out no way i thought i will downgrade to an older release and try and there also it is not working..
Kindly let me know which logs would help here because i'm not sure which are the relevant logs either

**Comment by nikhil-vr** [comment]
Please use the latest version and report if issue persists
