### ISSUE TITLE
Error 3001 (http: 403): This operation is forbidden due to license check failure.. UNSTRUCTURED license is not found. Please add license before proceeding.

### ISSUE THREAD

**Issue by agregory999** [EMCECS/ECS-CommunityEdition#513]
### Expected Behavior

After Step2 we should go to the browser and see storage pools and VDC as defined in deploy.xml

### Actual Behavior
Step2 hangs forever, and going to the browser console works, but storage pool isnt there and cannot be created due to licensing error.

### Steps to Reproduce Behavior

1.  Install 3.4 as per document
2. Run Step2 and wait until it starts hanging (10 min or so)
3.  Open UI and attempt to create storage pool

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @captntuttle

**Comment by padthaitofuhot** [comment]
Please run these three commands in this exact order and report back (yes, run the `-l` command twice):
```
ecsconfig licensing -l
ecsconfig licensing -a
ecsconfig licensing -l
```
Thanks!
