### ISSUE TITLE
Support for CentOS 7.8

### ISSUE THREAD

**Issue by mikeyd810** [EMCECS/ECS-CommunityEdition#514]
### Expected Behavior
bootstrap.sh -y -g -c deploy.yml

Completes and reboots 

### Actual Behavior
fails to install docker and pull correct packages after host update due to going from CentOS 7.6 to 7.8 as part of the update.  

### Steps to Reproduce Behavior

1. Deploy CentOS 7.6 minimal VM
2. Git Clone ECS Community Edition
3. edit deploy file and run the bootstrap.sh command

### Relevant Output and Logs
Failed to capture current logs but I was able to get around this by copying centos77.plugin.sh to centos78.plugin.sh and then adding a stanza in the os-router.plugin.sh to support CentOS 7.8
```
# Output and Logs go here
```

---
Notifies: @captntuttle

**Comment by mikeyd810** [comment]
Was able to replicate this so here's the log data and output from the bootstrap

> [./bootstrap.sh] We're going to start working with Docker now. If you elected
> [./bootstrap.sh] to build your own ecs-install image rather than pull one from
> [./bootstrap.sh] the EMC Dockerhub repo, it will add some time to your initial
> [./bootstrap.sh] bootstrap.
> [./bootstrap.sh]
> [./bootstrap.sh] Check if Docker login needed
> [./bootstrap.sh] Testing docker installation
> [./bootstrap.sh] Docker was installed correctly
> [./bootstrap.sh] Running post-install scripts for centos linux release 7.6.1810 (core)
Removed symlink /etc/systemd/system/multi-user.target.wants/postfix.service.
> [./bootstrap.sh] Creating host paths
> [./bootstrap.sh] Copying deploy.yml
> [ui/pull_image.sh] Cleaning up...
> Cleaning up...
> [ui/pull_image.sh] Cleaning up...
> [ui/pull_image.sh]      [build tmp containers]
> Cleaning up...
>      [build tmp containers]
sudo: docker: command not found
> [ui/pull_image.sh]      [ecs-install data containers]
>      [ecs-install data containers]
sudo: docker: command not found
> [ui/pull_image.sh]      [exited containers]
>      [exited containers]
sudo: docker: command not found
> [ui/pull_image.sh]      [dangling layers]
>      [dangling layers]
sudo: docker: command not found
> [ui/pull_image.sh] Pulling image emccorp/ecs-install:latest
> Pulling image emccorp/ecs-install:latest
> [ui/pull_image.sh] ERROR: Failed to pull the installer image. Check the log for details.
sudo: docker: command not found
> ERROR: Failed to pull the installer image. Check the log for details.
> [./bootstrap.sh] ERROR: We couldn't pull the ecs-install image for some reason. Please check the logs.
> [./bootstrap.sh] ERROR: If it's something simple, such as the ecs-install:latest image missing from
> [./bootstrap.sh] ERROR: your custom Docker registry, or if your Internet access isn't working, then
> [./bootstrap.sh] ERROR: you may be able to solve the problem by first solving one of the above issues.
> [./bootstrap.sh] ERROR: If you still need more help after trying the above, you can reach us on GitHub.

**Comment by laszlolaszlo** [comment]
Hello,
I've got the same problem with fresh Centos 7.8 minimal install. 
[llaszlo@ecsdev ECS-CommunityEdition]$ ./bootstrap.sh -y -c deploy.yml
`[llaszlo@ecsdev ECS-CommunityEdition]$ ./bootstrap.sh -y -c deploy.yml
> 
>  ECS Community Edition Install Node Bootstrap 2.9.2r
>  ECS Software Image emccorp/ecs-software-3.4.0:3.4.0.0
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> Escalating privileges
>     You may be presented with the system sudo banner and asked
>     for your password depending on the Linux flavor and default
>     sudo configuration for your system.
> 
> 
> ERROR: OS unknown and not supported: centos linux release 7.8.2003 (core)`

I tried to modify the bootstrap_plugins/os-router.plugin.sh file. I added a new condition to route_os() function:
`case "${os}" in

        centos\ linux\ release\ 7.4*)
            source ${plugins}/centos74.plugin.sh
            ;;
        centos\ linux\ release\ 7.5*)
            source ${plugins}/centos75.plugin.sh
            ;;
        centos\ linux\ release\ 7.6*)
            source ${plugins}/centos76.plugin.sh
            ;;
        centos\ linux\ release\ 7.7*)
            source ${plugins}/centos77.plugin.sh
            ;;
        centos\ linux\ release\ 7.8*)
            source ${plugins}/centos77.plugin.sh
            ;;

        # Die on unknowns
        *)
            die "OS unknown and not supported: $os"
            ;;
    esac`

After that I ran the deploy again whit success. I think centos77.plugin.sh file is just fine for Centos 7.8

**Comment by jasoncwik** [comment]
Yes, that is the correct fix. Thank you!
