### ISSUE TITLE
Install fails on vm

### ISSUE THREAD

**Issue by rodriguise** [EMCECS/ECS-CommunityEdition#52]
The install script bails:

[root@localhost ecs-single-node]# python step1_ecs_singlenode_install.py --disks sdb --ethadapter eno16777736 --hostname ecssinglenode
Traceback (most recent call last):
  File "step1_ecs_singlenode_install.py", line 720, in <module>
    main()
  File "step1_ecs_singlenode_install.py", line 687, in main
    logger.info("Starting Step 1: Configuration of Host Machine to run the ECS Docker Container: {}".format(docker_image_name))
UnboundLocalError: local variable 'docker_image_name' referenced before assignment
[root@localhost ecs-single-node]#

System:

[root@localhost ecs-single-node]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
[root@localhost ecs-single-node]# uname -a
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ecs-single-node]#

**Comment by APeter0807** [comment]
Added a fix for this issue; pushed said fix to master branch.
