### ISSUE TITLE
The OVA cannot be downlaoded 

### ISSUE THREAD

**Issue by KT1986HK** [EMCECS/ECS-CommunityEdition#523]
may I know how to download the ecs 3.4 ova file? 
I clicked the link but it returns a timeout response. 

the link i have clicked to download the ova: http://131118670375936839.public.ecstestdrive.com/public/dellemc-ecsce-3.4.0.0-install-node.ova

seems all 3.2/3.3/3.4 ova files have this problem.

Thanks.
KT 

### Actual Behavior
(Please put additional output and logs in the section for that below)

### Steps to Reproduce Behavior

1.
2.
3.

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @captntuttle

**Comment by evv1978z** [comment]
ecstestdrive.com fail and all link from this service too.
Can anybody recover this site?

**Comment by jasoncwik** [comment]
ECS Test Drive is currently down. It should be back up in a couple days. Sorry for the inconvenience.

**Comment by jasoncwik** [comment]
Link works now.
