### ISSUE TITLE
3.5 OVA availability

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ECS-CommunityEdition#524]
### Expected Behavior
Extend our monitoring client to ECS 3.5 version and the new performance related API Calls.
Requires deploying ECS 3.5 OVA

### Actual Behavior
(Please put additional output and logs in the section for that below)
Only able to download 3.4 OVA

### Steps to Reproduce Behavior

1.
2.
3.

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @captntuttle

**Comment by odcw** [comment]
Hi
ECS 3.5 community is it plan ?

**Comment by holgerjakob** [comment]
Could you directly jump to 3.6 instead?

**Comment by odcw** [comment]
of course I saw testdrive is already in 3.6 ;-)

**Comment by martin-duerre** [comment]
With a lot of new features coming to ecs 3.5 and 3.6, will there be a community edition for one of the releases?

**Comment by martin-duerre** [comment]
@jasoncwik @spiegela @bernard357 @bozakov 
Hello @captntuttle, does not seem to be involved in the ECS Repos anymore. Are there any plans going to 3.5 or 3.6 with the community edition?

Kind regards
Martin

**Comment by holgerjakob** [comment]
With the upgrade of one of our customers to 3.6, our rest api based monitoring solution breaks. It would be really nice if the community edition were not years behind with it's releases. Impossible to buy a cluster just to keep the rest api client up to date unfortunately.

**Comment by padthaitofuhot** [comment]
We're working on 3.5.1.2 currently.  I cannot comment on 3.6.0.0 yet.

**Comment by amarcionek** [comment]
I understand these things take time, but I'm adding another request for a more recent release. As an ISV, being able to test and dev on the latest version is crucial to our business.

**Comment by drude-dell** [comment]
When the OVA version of this be available? I deliver training and need to be able to demo 3.5 or 3.5 ECS functionality to our customer.

**Comment by drude-dell** [comment]
The current 3.5 release that is on github fails when you form step1 during the install and configuration
