### ISSUE TITLE
Error running step1

### ISSUE THREAD

**Issue by romanShieldfc** [EMCECS/ECS-CommunityEdition#534]
### Expected Behavior
Step1 to finish successfully 

### Actual Behavior
(Please put additional output and logs in the section for that below)
getting this Error:

[centos@ip- ECS-CommunityEdition_old]$ step1
ecs-install> Initializing data container, one moment ..DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Command errored out with exit status 1:
command: /usr/bin/python2 /usr/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-dN_FXK/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"''
cwd: None
Complete output (67 lines):
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting setuptools>=40.6.0
Using cached setuptools-44.1.1-py2.py3-none-any.whl (583 kB)
Collecting wheel
Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting cffi>=1.12
Downloading cffi-1.14.5.tar.gz (475 kB)
Collecting pycparser
Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
Installing collected packages: setuptools, wheel, pycparser, cffi
Running setup.py install for cffi: started
Running setup.py install for cffi: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gkTECm/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gkTECm/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jR2wgG/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-dN_FXK/overlay --compile --install-headers /tmp/pip-build-env-dN_FXK/overlay/include/python2.7/cffi
cwd: /tmp/pip-install-gkTECm/cffi/
Complete output (48 lines):
unable to execute 'gcc': No such file or directory
unable to execute 'gcc': No such file or directory

No working compiler found, or bogus compiler options passed to
the compiler from Python's standard "distutils" module.  See
the error messages above.  Likely, the problem is not related
to CFFI but generic to the setup.py of any Python package that
tries to compile C code.  (Hints: on OS/X 10.8, for errors about
-mno-fused-madd see http://stackoverflow.com/questions/22313407/
Otherwise, see https://wiki.python.org/moin/CompLangPython or
the IRC channel #python on irc.freenode.net.)

Trying to continue anyway.  If you are trying to install CFFI from
a build done in a different context, you can ignore this warning.

running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/cffi
copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/error.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/pkgconfig.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
copying cffi/_embedding.h -> build/lib.linux-x86_64-2.7/cffi
copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-2.7/cffi
running build_ext
building '_cffi_backend' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/c
gcc -fno-strict-aliasing -Os -fomit-frame-pointer -g -DNDEBUG -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gkTECm/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gkTECm/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jR2wgG/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-dN_FXK/overlay --compile --install-headers /tmp/pip-build-env-dN_FXK/overlay/include/python2.7/cffi Check the logs for full command output.
----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python2 /usr/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-dN_FXK/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.
ecs-install> ui.tgz failed to build.
. OK
ecs-install> Applying and validating deploy.yml...
/usr/local/bin/entrypoint.sh: line 167: ecsdeploy: not found
/usr/local/bin/entrypoint.sh: line 232: ecsdeploy: not found

### Steps to Reproduce Behavior

1.run sudo ./bootstrap.sh -c deploy.yml
2.run step1

### Relevant Output and Logs
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

---
Notifies: @Oohdark30 @padthaitofuhot

**Comment by drude-dell** [comment]
Is there any update on what the fix is?

**Comment by daydrim** [comment]
Hello. I have the same issue with OVA installation are there any news what dependencies should be installed to achieve the step1 success?

**Comment by daydrim** [comment]
#504

**Comment by mpolitze** [comment]
I managed to work around this issue pretty much as described in the comment https://github.com/EMCECS/ECS-CommunityEdition/issues/504#issuecomment-575189446. 

However I could *not* get the current master nor the 3.6 version to start up the management interface on my VM. Best I could do was running version 9717ae3ebfc00bc1ff97c3bd2c97868faf6203ff.

To work around various issues i did:

1. Pin all versions in `ui/resources/docker/ecs-install-requirements.txt`
```
click==6.7
dotmap==1.2.20
futures==3.1.1
httplib2==0.10.3
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.9.6
pager==3.3
paramiko==2.3.0
ptpython==0.41
cryptography==2.8
pycrypto==2.6.1
pyOpenSSL==17.3.0
python-ecsclient==1.1.6
PyYAML==3.12
requests==2.18.4
sarge==0.1.4
simplejson==3.11.1
six==1.11.0
urwid==1.3.1
urwid_timed_progress==1.1.1
pykwalify==1.6.0
```
2. Add build dependencies `build-base libffi-dev openssl-dev python2-dev` in `ui/resources/docker/Rockerfile`:
```diff
@@ -23,7 +23,7 @@ ENV pip_proxy={{ .PipProxy }}

 # Add required system packages and setup the environment
 RUN apk update \
-    && apk --no-cache add python2 py-pip openssh-client sshpass openssl ca-certificates libffi \
+    && apk --no-cache add build-base libffi-dev openssl-dev python2-dev python2 py-pip openssh-client sshpass openssl ca-certificates libffi \
                              libressl pigz jq less opentracker aria2 mktorrent ansible \
     && mv /etc/profile.d/color_prompt /etc/profile.d/color_prompt.sh \
     && ln -s /usr/local/src/ui/ansible /ansible \
```
3. Edit `bootstrap_plugins/os-router.plugin.sh` and copy lines for centos 7.8 to centos 7.9, because centos 7.8 automatically updates to 7.9:
```diff
@@ -58,6 +58,9 @@ route_os() {
         centos\ linux\ release\ 7.8*)
             source ${plugins}/centos78.plugin.sh
             ;;
+        centos\ linux\ release\ 7.9*)
+            source ${plugins}/centos78.plugin.sh
+            ;;
         # Die on unknowns
         *)
             die "OS unknown and not supported: $os"
```
4. Run bootstrapping with rebuilding the docker images: `./bootstrap.sh -g -c deploy.yml --build-from http://dl-cdn.alpinelinux.org/alpine/`

Leaving this here... so maybe this helps someone else getting around the issues.

Would be really nice if people could look into this and make sure version 3.6. can be installed correctly.
