### ISSUE TITLE
Remote Syslog Server

### ISSUE THREAD

**Issue by nasara109** [EMCECS/ECS-CommunityEdition#535]
I am using Dell EMC ECS v3.4.0.0 all in one single node deployment.

Want to send logs to remote syslog server , but there is a error

Error 7000 (http: 500): An error occurred in the API Service. An error occurred in the API service. Cause: Could not get Fabric LM Client ERROR_INTERNAL.

**Comment by nikhil-vr** [comment]
Some features may not be available with community edition , please try it on 3.7 and re-open if issue persists
