### ISSUE TITLE
DELLEMC-ECSCE-3.6.0.1-OVA - cant load Dashboard

### ISSUE THREAD

**Issue by Raffiolly** [EMCECS/ECS-CommunityEdition#539]
### Expected Behavior
After server is deplyed the dashboard page is at "loading" status 

### Actual Behavior
Build a new Linux VM with the OVF + the yml config file, rebooted the VM , still dashboard is not loading.

* any one came accross this issue as well ?

**Comment by igorus512** [comment]
Also hit this problem - dashboard is loading forever, Grafana is not available as well (expected that we can use grafana in ECS 3.6 CE).

**Comment by nikhil-vr** [comment]
Patch should be working onit
