### ISSUE TITLE
dell-ecsce-3.6.2.0-install-node.ova : errors in ova-step1

### ISSUE THREAD

**Issue by lriva94** [EMCECS/ECS-CommunityEdition#544]
### Expected Behavior
ova-step1 works fine with no error when deploying more than 1 node

### Actual Behavior

run ova-step1: errors when trying to copy /var/cache/emc/ecs-install/cache.torrent and /var/cache/emc/ecs-install/os_CentOS_7/package_cache.tgz to all nodes

### Steps to Reproduce Behavior

1. Create the install node using dell-ecsce-3.6.2.0-install-node.ova
2. Clone the created VM one time (to have 2 nodes)
3. start the 2 VMs and set the IP addresses
4. On install node run videploy and feed the file with the two IP addresses (1st as install node and member, 2nd as member): this works fine
5. run ova-step1

### Relevant Output and Logs
ova-step1
....
PLAY [Common | Ping data nodes before doing anything else] ************************************************************************************************

TASK [ping] ***********************************************************************************************************************************************
ok: [10.52.69.172]
ok: [10.52.69.174]

PLAY [Installer | Slice nodes into OS groups for package install] *****************************************************************************************

TASK [group_by] *******************************************************************************************************************************************
ok: [10.52.69.172]
ok: [10.52.69.174]

PLAY [CentOS 7 | Synchronize cache] ***********************************************************************************************************************

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Fetch torrent package names] *********************************************************************************
changed: [10.52.69.172 -> 10.52.69.172]
changed: [10.52.69.174 -> 10.52.69.172]

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Make yum cache paths for torrent packages] *******************************************************************
changed: [10.52.69.174] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
changed: [10.52.69.174] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Copy torrent packages to nodes] ******************************************************************************
ok: [10.52.69.174] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)
ok: [10.52.69.174] => (item=/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm)

TASK [CentOS_7_sync_caches_prep : CentOS 7 | Install torrent packages on nodes] ***************************************************************************
ok: [10.52.69.174] => (item=[u'/var/cache/yum/x86_64/7/base/packages/c-ares-1.10.0-3.el7.x86_64.rpm', u'/var/cache/yum/x86_64/7/epel/packages/aria2-1.34.0-5.el7.x86_64.rpm'])

TASK [common_sync_caches_by_torrent : include_vars] *******************************************************************************************************
ok: [10.52.69.172]
ok: [10.52.69.174]

TASK [common_sync_caches_by_torrent : Selinux | Set selinux permissive] ***********************************************************************************
changed: [10.52.69.174]
changed: [10.52.69.172]

TASK [common_sync_caches_by_torrent : Common | Create ecs-install host directory on nodes] ****************************************************************
ok: [10.52.69.174]

TASK [common_sync_caches_by_torrent : Common | Create ecs-install cache directory on nodes] ***************************************************************
ok: [10.52.69.174]

TASK [common_sync_caches_by_torrent : Common | Copy cache torrent digest to nodes] ************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/var/cache/emc/ecs-install/cache.torrent'
fatal: [10.52.69.174]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find or access '/var/cache/emc/ecs-install/cache.torrent'"}

TASK [common_sync_caches_by_torrent : Common | Torrent sync caches with nodes] ****************************************************************************

PLAY [CentOS 7 | Install cached packages] *****************************************************************************************************************

TASK [CentOS_7_baseline_install : include_vars] ***********************************************************************************************************
ok: [10.52.69.172]

TASK [CentOS_7_baseline_install : CentOS 7 | Set selinux permissive] **************************************************************************************
ok: [10.52.69.172]

TASK [CentOS_7_baseline_install : CentOS 7 | Add SSL proxy cert] ******************************************************************************************

TASK [CentOS_7_baseline_install : CentOS 7 | Stop and disable unused services] ****************************************************************************
ok: [10.52.69.172] => (item=mta)

TASK [CentOS_7_baseline_install : CentOS 7 | Configure DNS] ***********************************************************************************************
changed: [10.52.69.172]

TASK [CentOS_7_baseline_install : CentOS 7 | Unpack package_cache.tgz] ************************************************************************************
fatal: [10.52.69.172]: FAILED! => {"changed": false, "failed": true, "msg": "Source '/var/cache/emc/ecs-install/os_CentOS_7/package_cache.tgz' does not exist"}

PLAY [Installer | Disable torrent ffx] ********************************************************************************************************************

TASK [file] ***********************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ************************************************************************************************************************************************
10.52.69.172               : ok=9    changed=3    unreachable=0    failed=1
10.52.69.174               : ok=10   changed=3    unreachable=0    failed=1
localhost                  : ok=1    changed=0    unreachable=0    failed=0

Playbook run took 0 days, 0 hours, 0 minutes, 11 seconds
Operation failed.

# Output and Logs go here
```
It seems that some files necessary for the installation and configuration of member nodes are not present in the OVA.
---
Notifies: @Oohdark30 @padthaitofuhot

**Comment by DDmkuhns** [comment]
I ran into this same exact issue today with DELL-ECSCE-3.6.2.0-OVA.ova installing a two node environment.

This looks just like https://github.com/EMCECS/ECS-CommunityEdition/issues/473
Tried the workaround there and that seems to have worked.
