### ISSUE TITLE
Deployment Error on step2

### ISSUE THREAD

**Issue by CrazyVolnay** [EMCECS/ECS-CommunityEdition#545]
### Context
Deploying the latest (DELL-ECSCE-3.6.2.0-OVA.ova) OVA using All-in-One Single-Node Deployments procedure
Logued as root (not mentionned if needed to run the install steps as admin or root user)
Changed nodes IP in install_node and storage_pools > members sections with the node IP
Changed DNS and NTP to match environment
Changed ecs_block_devices from /dev/vda to /dev/sdb
No error after saving the yml file.
Ran ova-step1, without error. According to the documentation, I should receive EMC ECS license agreement on the screen, but no such screen appeared, the step1 finished without error
Ran ova-step2. The deployment fails here with the following output : 

[root@localhost ~]# ova-step2
> Pinging Management API Endpoint until ready
> Pinging endpoint 10.10.10.1... (CTRL-C to break)
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: ECS API internal error. If ECS services are still bootstrapping, this is likely temporary.
> WAIT: ECS API internal error. If ECS services are still bootstrapping, this is likely temporary.
> WAIT: ECS API internal error. If ECS services are still bootstrapping, this is likely temporary.
> WAIT: ECS API internal error. If ECS services are still bootstrapping, this is likely temporary.
> PONG: api_endpoint=10.10.10.1 username=root diag_endpoint=10.10.10.1 dt_total=0 dt_unready=0 dt_unknown=0

> Installing licensing in ECS VDC(s)
> Using default license
> Adding licensing to VDC: vdc1
>       OK
> Added default license to ECS

> Pinging Management API Endpoint until ready
> Pinging endpoint 10.10.10.1... (CTRL-C to break)
> PONG: api_endpoint=10.10.10.1 username=root diag_endpoint=10.10.10.1 dt_total=0 dt_unready=0 dt_unknown=0

> Creating Storage Pool: vdc1/sp1
>       OK
> Adding Data Stores to Storage Pool:
>       vdc1/sp1/10.10.10.1
Traceback (most recent call last):
  File "/usr/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.9.1.post0', 'console_scripts', 'ecsconfig')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/ecsconfig.py", line 661, in sp
    tasks = add_all()
  File "/usr/bin/ecsconfig.py", line 637, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/bin/ecsconfig.py", line 629, in add_one
    sp_tasks.append(sp_add_node(sp_id, node))
  File "/usr/bin/ecsconfig.py", line 606, in sp_add_node
    return conf.api_client.data_store.create(**kwargs)
  File "/usr/lib/python2.7/site-packages/ecsclient/common/provisioning/data_store.py", line 217, in create
    return self.conn.post('vdc/data-stores/commodity', json_payload=payload)
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Error while registering 1 commodity node(s) - Bad request body: https://10.10.10.1:4443/vdc/data-stores/commodity 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo

Trying to reach GUI, but getting Error 999 (http: 500): An unexpected error occurred, please check the ECS logs for more information. List data stores operation failed on almost all pages

Any clue about what I'm missing ?

---
Notifies: @Oohdark30 @padthaitofuhot

**Comment by tmassano** [comment]
I had to wait 10-15 minutes after step 1, before step two.

Originally when step 2 failed, I started the install over on a fresh node. I dont know if step two messed something up starting it too early.

**Comment by uhonermann** [comment]
Exactly the same error, here.
Used current OVA.

Any ideas ?

**Comment by MichelZ** [comment]
Same issue here. Doesn't look like ECS Community edition is alive :(

**Comment by nikhil-vr** [comment]
Normally this error happens when the storagepool initialize taking more time . could you please try accessing the ECS UI and create VDC/RG ..on UI ?

**Comment by MichelZ** [comment]
Thanks @nikhil-vr, I was able to resolve this. I've set static addresses on the nodes but didn't disable DHCP, so they got 2 addresses each and likely confused. 
I've also added the nodes to DNS.

This seems to have fixed my issue

**Comment by Tobias-08** [comment]
@MichelZ I'm having exactly the same problem. I'm using static address, too. What do you mean with disabling DHCP (where?)?

Thanks!

**Comment by dongnak** [comment]
@nikhil-vr UI is stuck also. :(
