### ISSUE TITLE
videploy setup and deploy failure

### ISSUE THREAD

**Issue by rfsonders** [EMCECS/ECS-CommunityEdition#546]
### Expected Behavior
Following the OVA single node install here.
https://github.com/EMCECS/ECS-CommunityEdition/blob/master/docs/source/installation/OVA_Installation.md

Static IP configured with nmtui
Port 22 opened

### Actual Behavior
(Please put additional output and logs in the section for that below)

> Updating /opt/emc/ecs-install/deploy.yml from deploy.yml
> Recreating ecs-install data container
ecs-install> Initializing data container, one moment ..DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
You are using pip version 19.0.3, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
. OK
ecs-install> Applying and validating deploy.yml...
The deployment file at '/opt/emc/ecs-install/deploy.yml' is not valid.
Schema validation failed:
 - Key 'ecs_block_devices' was not defined. Path: '/facts/node_defaults'.
 - Key 'description' was not defined. Path: '/facts/node_defaults'.
 - Key 'is_protected' was not defined. Path: '/facts/node_defaults'.
 - Key 'is_cold_storage_enabled' was not defined. Path: '/facts/node_defaults'.
The deployment file at '/opt/emc/ecs-install/deploy.yml' is not valid.
Schema validation failed:
 - Key 'ecs_block_devices' was not defined. Path: '/facts/node_defaults'.
 - Key 'description' was not defined. Path: '/facts/node_defaults'.
 - Key 'is_protected' was not defined. Path: '/facts/node_defaults'.
 - Key 'is_cold_storage_enabled' was not defined. Path: '/facts/node_defaults'.

[admin@ecs01 ~]$

### Steps to Reproduce Behavior

1.
2.
3.

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @Oohdark30 @padthaitofuhot

**Comment by tmassano** [comment]
Make sure you select OK and the end of nmtui.
I rebbot after that, and when it comes back up verify it with
ip a

**Comment by nikhil-vr** [comment]
Is there any issue with deploy.yml ? could you please validate it.

**Comment by nikhil-vr** [comment]
Please try with 3.7 OVA ,  and its not a re-producible issue , please let me know if you see further issue
