### ISSUE TITLE
Used Capacity goes to 100 % even if you don't write data

### ISSUE THREAD

**Issue by lriva94** [EMCECS/ECS-CommunityEdition#554]
### Expected Behavior
Used capacity must grow only if data is added

### Actual Behavior
(Please put additional output and logs in the section for that below)
Used capacity grows (system metadata) until it reaches 100%, and any connection to the GUI fails with the following error on the login screen:
java.net.SocketTimeoutException: Read timed out

### Steps to Reproduce Behavior

1. Install ECS Community Edition 3.7 with any number of nodes
2. Just let the nodes alive
3. With a 6 nodes installation with 200 GiB each, the full capacity is reached after 5 weeks

### Relevant Output and Logs
```
# Output and Logs go here
```
sudo docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED       STATUS       PORTS     NAMES
14818bdf3b06   emccorp/ecs-software:latest   "/opt/vipr/boot/boot…"   5 weeks ago   Up 3 weeks             ecs-storageos

df -h
Filesystem               Size  Used Avail Use% Mounted on
devtmpfs                  12G     0   12G   0% /dev
tmpfs                     12G     0   12G   0% /dev/shm
tmpfs                     12G  1.2G   11G  10% /run
tmpfs                     12G     0   12G   0% /sys/fs/cgroup
/dev/mapper/centos-root   50G   26G   25G  51% /
**/dev/sdb1                200G  191G  9.9G  96% /ecs/uuid-7d982823-aca5-472f-8c34-6c80548bb0ec**
/dev/sda1               1014M  238M  777M  24% /boot
/dev/mapper/centos-home   39G   50M   39G   1% /home
tmpfs                    2.4G     0  2.4G   0% /run/user/1000
[admin@ecs1-02 ~]$

---
Notifies: @Oohdark30 @padthaitofuhot

**Comment by nikhil-vr** [comment]
Space reclamation process is not optimized for the smaller system , hence the issue , also it is not advised to restart nodes as would result early seals of chunks and occupy space.   You could always uninstall and re-install. If you would like to keep it longer please have some large disks added,
