### ISSUE TITLE
Unable to deploy ova on escx 7 U3: Line 28: Unsupported hardware family 'vmx-14'.

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ECS-CommunityEdition#555]
### Expected Behavior
Able to deploy ova

### Actual Behavior
in the last step to deploy the ova, the following error appears:
Line 28: Unsupported hardware family 'vmx-14'.

When I use the ovftool to convert the machine to an ovf, the following appears:
Error:
 - Line 28: Unsupported hardware family 'vmx-14'.
 - The guest operating system 'centos7_64Guest' is not supported.

### Steps to Reproduce Behavior

1. use an esxi 7 hypervisor
2. deploy the latest ova
3. last step fails

### Relevant Output and Logs
Line 28: Unsupported hardware family 'vmx-14'.

Error:
 - Line 28: Unsupported hardware family 'vmx-14'.
 - The guest operating system 'centos7_64Guest' is not supported.
# Output and Logs go here
```

---
Notifies: @Oohdark30 @padthaitofuhot

**Comment by nikhil-vr** [comment]
It is related to the vmware ESX version , you might be using an older version ,  please look at the version compatibility. 

https://kb.vmware.com/s/article/2007240
