### ISSUE TITLE
OVA Links Broken

### ISSUE THREAD

**Issue by CRogers1145** [EMCECS/ECS-CommunityEdition#556]
The Download Links for the OVAs are broken.

eg.
https://130751444065420395.public.ecstestdrive.com/ecs-ce/DELL-ECSCE-3.7-OVA.ova 

Is it possible to get the current release links updated.

**Comment by nikhil-vr** [comment]
Link is working now , you can try now , it was down due to some maintenance.

**Comment by CRogers1145** [comment]
Awesome, thank you.

Thought the appliance may have been depreciated.
