### ISSUE TITLE
OVA download link appears to be broken

### ISSUE THREAD

**Issue by jsonar-cpapke** [EMCECS/ECS-CommunityEdition#564]
The link for the latest (and previous) OVAs seem to be broken for me. For example https://130751444065420395.public.ecstestdrive.com/ecs-ce/DELL-ECSCE-3.8-OVA.ova just times out for me.

Would it be possible to get that fixed? Thanks!

---
Notifies: @nikhil-vr

**Comment by nikhil-vr** [comment]
Link is down due to planned maintenance, will update once it's back.

**Comment by chrismuench** [comment]
do you know when it might be available again?  I need to test some software against ECS, and this is the only way that I can.

**Comment by mprantoniol** [comment]
Hi, the link still broked

**Comment by nikhil-vr** [comment]
Power maintenance is until 24th , so should be back by tomorrow.

**Comment by nikhil-vr** [comment]
Please re-try link is working

**Comment by jsonar-cpapke** [comment]
It is working now, thanks!
