### ISSUE TITLE
ECS Community Edition Install Node 2.9.1 (ECS 3.8.0.3) can not install .ova on VMware vSphere Client version 6.5

### ISSUE THREAD

**Issue by thangtq546** [EMCECS/ECS-CommunityEdition#575]
Hi,

I'm creating VMs using .ova file with version ECS Community Edition Install Node 2.9.1 (ECS 3.8.0.3) on VMware vSphere Client version 6.5.
I am currently encountering an error: 
`Line 28: Unsupported hardware family 'vmx-17'`

I understand that with this version, it is not compatible with VMware vSphere Client version 6.5.
I read the Release Notes but couldn't find information on the specific supported versions of VMware vSphere Client version.

Can someone support me with ECSCE versions are supported which VMware vSphere Client versions?
Specifically, which versions of VMware vSphere Client are supported by ECS Community Edition Install Node 2.9.1 (ECS 3.8.0.3)?
Where can I find this information in the documentation?

Thanks for your supporting!
---
Notifies: @nikhil-vr

**Comment by MichelZ** [comment]
Here's a quick google for vmx-17:
https://kb.vmware.com/s/article/1003746

Seems like ESX7 is the minimum required

**Comment by thangtq546** [comment]
> Here's a quick google for vmx-17: https://kb.vmware.com/s/article/1003746
> 
> Seems like ESX7 is the minimum required

Thanks for your informartion!
Do you know in which document the VMware vSphere Client version supporting ECS Community Edition is mentioned?

**Comment by MichelZ** [comment]
It is not mentioned AFAIK, but as 6.5 has been out of support for over a year now, you'd be better off migrating away from it
