### ISSUE TITLE
Step 2 on install never completes

### ISSUE THREAD

**Issue by grantrat1** [EMCECS/ECS-CommunityEdition#579]
Single node install
step1 seems to complete normally, I wait for 10 minutes or more after rebooting.
step2 starts to run but hangs at:
WAIT: 

### Expected Behavior
Completes normally

### Actual Behavior
(Please put additional output and logs in the section for that below)
WAIT: API service is not alive. This is likely temporary.
WAIT: API service is not alive. This is likely temporary.

etc
etc
continues for hours

### Steps to Reproduce Behavior

1.
2.
3.

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @nikhil-vr

**Comment by dongnak** [comment]
@grantrat1 did you resolve this issue? please, help me
