### ISSUE TITLE
Stop installing deprecated version of Docker

### ISSUE THREAD

**Issue by jasoncwik** [EMCECS/ECS-CommunityEdition#59]
The current install script installs Docker 1.4.1 and as of 12/15 this version can no longer connect to the docker registry.  We should stop installing Docker and use the version bundled with the OS.

**Comment by LVLAaron** [comment]
This is fairly terrible. I manually installed docker with yum and edited the install scripts to not remove and add a specific version. Let's get this fixed.

**Comment by jasoncwik** [comment]
Yes, I already have a fix for this.  Should be committed today.

**Comment by LVLAaron** [comment]
Excellent. Thanks for the quick response!

**Comment by APeter0807** [comment]
Fixed in merge from Develop (#62)

**Comment by LVLAaron** [comment]
Confirmed. Fired up a brand new CentOS 7 box. Thanks guys.
