### ISSUE TITLE
Automatically update /etc/fstab during step1

### ISSUE THREAD

**Issue by jasoncwik** [EMCECS/ECS-CommunityEdition#66]
After partitioning and mounting the disks, we need to update /etc/fstab so the data disks get mounted after reboot.

e.g.
```
/dev/sdb1               /ecs/uuid-1             xfs     rw,noatime,seclabel,attr2,inode64,noquota 0 0
```

Please use those mount options and not `defaults` since we want to ensure we get `noatime` for performance reasons.

**Comment by APeter0807** [comment]
Is now handled by default in #106.
