### ISSUE TITLE
Hangs at a31868e32794: Layer already being pulled by another client. Waiting

### ISSUE THREAD

**Issue by bellitech** [EMCECS/ECS-CommunityEdition#68]
The step1 script stops at the same location every time. I've rebooted and restarted to no avail. I am running CentOS Linux release 7.2.1511 (Core). Docker version is 1.8.2-el7.centos.

**Comment by jasoncwik** [comment]
This appears to be an issue with docker and/or docker hub. If you can pull the image manually, the script should continue. Please try:

systemctl restart docker
docker pull emccorp/ecs-software-2.1

If you're still having problems try running the docker daemon in debug mode. This may show any issues downloading:

systemctl stop docker
docker -d -D

Then run the pull from another window. 

Note that if you're an EMC employee behind the corporate firewall you will need to install some CA certificates.

**Comment by bellitech** [comment]
How do I get those certificates and instructions to install them?

John Belliveau
EMC, Federal 
240-687-3918

**Comment by jasoncwik** [comment]
I just committed this to the develop branch.  Can you test it out?

https://github.com/EMCECS/ECS-CommunityEdition/tree/develop/emc-ssl-cert

**Comment by bellitech** [comment]
Thanks, again, and Happy New Year!  I added the certificate, and it worked.
