### ISSUE TITLE
TypeError Updating the /etc/hostname file with the Parameter Hostname

### ISSUE THREAD

**Issue by amarcionek** [EMCECS/ECS-CommunityEdition#7]
Get the following error when running the step1_ecs_singlenode_install.py script

`[12/Aug/2015 12:14:52] INFO [root:182] Updating the /etc/hostname file with the Parameter Hostname
(Adding) Hostname does not Exist: ['ecs']`
`[12/Aug/2015 12:14:52] ERROR [root:210] must be string or buffer, not list
Traceback (most recent call last):
  File "step1_ecs_singlenode_install.py", line 188, in hosts_file_func
    hostname_file.write(hostname)
TypeError: must be string or buffer, not list`
`[12/Aug/2015 12:14:52] CRITICAL [root:211] Aborting program! Please review log.`

**Comment by amarcionek** [comment]
Sorry, should have included the command line:

`python step1_ecs_singlenode_install.py --disks sdb --ethadapter eno16777736 --hostname ecs`

**Comment by ryandotclair** [comment]
Issue I believe is with this part in the Step1 python script:

```
hostname_file.write(hostname)
```
It should be:

```
hostname_file.write(str(hostname))
```
Replace it and see if that works for you as it did for me.

**Comment by amarcionek** [comment]
I've confirmed this fixed my issue. Sorry it took so long!
