### ISSUE TITLE
Management Console Port isn't correct

### ISSUE THREAD

**Issue by tlehr1967** [EMCECS/ECS-CommunityEdition#95]
Doccumentation indicates it is listening on port 443, comments in the step1 script say 443
Python Code trys to test it on port 4443
Actual ECS container is listening on port 64443

**Comment by tlehr1967** [comment]
inside the container, the file application.conf in  /opt/storageos/ecsportal/conf has:

https_port=64443

**Comment by jasoncwik** [comment]
Right.  _portalsvc_ runs on that port, but nginx runs on 443 and 4443 and proxies requests for objcontrolsvc, portalsvc, and others.

```
ecs-obj-1-1:~ # netstat -anp | grep LISTEN | grep -e 'portalsvc\|nginx'
tcp        0      0 10.1.83.51:80           0.0.0.0:*               LISTEN      178210/nginx.conf   
tcp        0      0 127.0.0.1:4443          0.0.0.0:*               LISTEN      178210/nginx.conf   
tcp        0      0 10.1.83.51:4443         0.0.0.0:*               LISTEN      178210/nginx.conf   
tcp        0      0 10.1.83.51:443          0.0.0.0:*               LISTEN      178210/nginx.conf   
tcp        0      0 :::64443                :::*                    LISTEN      173234/ecsportalsvc 
```

What is the issue you're seeing?  It's normal to see connection errors to port 4443 during step1 while we wait for the authsvc to come up.

**Comment by tlehr1967** [comment]
Well, perhaps the proxy isn't working .. the only way I can ever get the Mgmt console to come up is to go to port 64443, or make the changed I mentioned in the previous post.  I have waited to hours ( until the install script gave up ) for it to come up .

**Comment by jasoncwik** [comment]
nginx doesn't come up until the base system is initialized.  I think this is a symptom of some other issue and #96 .  Can you get on WebEx with @APeter0807 so he can troubleshoot?  I'll close this and keep #96  open.
