### ISSUE TITLE
Default Account / Password isn't working

### ISSUE THREAD

**Issue by tlehr1967** [EMCECS/ECS-CommunityEdition#96]
Default management account root:ChangeMe doesn't work once the management console comes up

**Comment by APeter0807** [comment]
Could you provide a bit more detail as to the installation procedure you were using (single/multi-node, docker/gce/vagrant, configuration/arguments, etc.)? It would certainly help us replicate and then fix the issue.

**Comment by tlehr1967** [comment]
Both single and multinode docker versions


Todd Lehr | Global Architect
EMC² | 300 Conshohocken State Rd. Suite 700 | West Conshohocken, PA 19428<x-apple-data-detectors://1/1>

(O) 610-234-4737<tel:610-234-4737> | (M) 484-354-7758<tel:484-354-7758>
* todd.lehr@emc.com<mailto:todd.lehr@emc.com> |
Sent from my handhelld


On Feb 2, 2016, at 11:36 AM, Aaron Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you provide a bit more detail as to the installation procedure you were using (single/multi-node, docker/gce/vagrant, configuration/arguments, etc.)? It would certainly help us replicate and then fix the issue.

**Comment by APeter0807** [comment]
I see where you might be running into problems;

Installing on the EMC network in particular tends to result in a couple of access issues; did you try using adding the certificate in the `emc-ssl-cert` directory? If so and the issue persists, you may need to change your firewall rules; a bash script to do so is currently in the top directory of the `arg_updates` branch, or you could manually add the necessary ports as listed in `Documentation/ECSTroubleshooting.md` in that same branch.

**Comment by tlehr1967** [comment]
This was installed not on the EMC network, I have a LAB at home that I am
working with ..  if you want, you can call me on my cell as I logged a
number of issues yesterday I am running intoi.

**Comment by tlehr1967** [comment]
logged into the shell in the container and changed the root passwd back to ChangeMe and I am able to log into the management console again

**Comment by jasoncwik** [comment]
@tlehr1967 can you get on a webex with @APeter0807 .  Something went wrong during the install.

**Comment by APeter0807** [comment]
Issue was related to irewalld being disabled and necessary listening ports remaining closed as a result.

Script to fix this issue is included in repository and relevant ports outlined in documentation as of 35160ca . Next update to master should include specific reference to `firewalld.sh` in `ECS-Troubleshooting.md`

**Comment by APeter0807** [comment]
Fixed and properly noted with #106.
